### PR TITLE
Fixes the invariant not called on extern(C++) issue

### LINKED ISSUE #20924: invariant not called on extern(C++) classes
Found while working on DMD itself, which uses `extern(C++)` classes for its AST.

```D
extern(C++) class C
{
    invariant { assert(0); }
    void f() {}
}

void main()
{
    auto c = new C();
    c.f();
}
```

Expected behavior: the same as you get when you change it to `extern(D) class C`: Assertion failure
Actual behavior: the program runs, exits with status 0

If this is intentional, it should be documented somewhere. Either in https://dlang.org/spec/class.html#invariants or https://dlang.org/dmd-linux.html#switch-check if it's considered an implementation detail.

### PR DESCRIPTION
**Pull request by abulgit**
Fix: [#20924 ](https://github.com/dlang/dmd/issues/20924)

In D, invariants are class/struct invariants that check the consistency of an object. They're supposed to be checked:
    1. At the end of a constructor
    2. At the start and end of public methods
    3. At the start of public const/immutable methods
In this case, the invariant contains assert(0), which should throw an assertion failure. With extern(D) classes, this assertion is properly triggered, but with extern(C++) classes, it's not.

**Root Cause of this issue:**  In the `addPreInvariant `and `addPostInvariant `methods in `func.d`, there was an explicit check to skip invariant validation for C++ classes through the condition `!(cd && cd.isCPPclass())`.

**The Fix:** Removed the conditional check that was excluding C++ classes from invariant validation, allowing invariants to be checked for all classes regardless of linkage.

**The Changes Made**
1. Modified `addPreInvariant` and `addPostInvariant `in `func.d` to remove the exclusion of C++ classes.
2. Created a test file to verify that invariants are now checked for extern(C++) classes as well as extern(D) classes.

### CODE REVIEW

File: compiler/src/dmd/func.d [hunk 1]
```diff
@@ -821,14 +821,14 @@ extern (C++) class FuncDeclaration : Declaration
     {
         auto ad = isThis();
         ClassDeclaration cd = ad ? ad.isClassDeclaration() : null;
```
Comment (thewilsonator) [inline compiler/src/dmd/func.d:823]: `cd` is now an unused variable and can be removed

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Thanks for the quick PR!

File: compiler/test/runnable/invariant_test.d [hunk 2]
```diff
@@ -0,0 +1,67 @@
+/*
```
Comment (thewilsonator) [inline compiler/test/runnable/invariant_test.d:1]: https://github.com/dlang/dmd/issues/20924#issuecomment-2719334263 also please merge this file into `testinvariant.d` and add a comment above the test case which (GitHub) Issue number that test is fixing

Comment (abulgit) [reply compiler/test/runnable/invariant_test.d]: Okay, I fixed all the suggested changes.
1. `cd `is an unused variable that is removed.
2. Replace the use of `std.stdio.writeln` with the suggested `try-catch-assert(0)` pattern for both the C++ and D class tests.
3. Removed the `TEST_OUTPUT` section as it's no longer needed
4. merge the test file into `compiler/test/runnable/testinvariant.d`.

File: compiler/test/runnable/testinvariant.d [hunk 3]
```diff
@@ -1,241 +1,63 @@
-// PERMUTE_ARGS:
```
Comment (thewilsonator) [inline compiler/test/runnable/testinvariant.d:1]: append this new tests to this file, not replace its contents.

File: compiler/test/runnable/testinvariant.d [hunk 4]
```diff
@@ -1,241 +1,63 @@
...
+/*
+REQUIRED_ARGS: -betterC
```
Comment (thewilsonator) [inline compiler/test/runnable/testinvariant.d:2]: is `-betterC` actually required for this test?

Comment (abulgit) [reply compiler/test/runnable/testinvariant.d]: nope, Okay, I think I misunderstood this test thing. 
I will fix it now.

File: compiler/test/runnable/testinvariant.d [hunk 5]
```diff
@@ -238,4 +283,5 @@ void main()
     test16384();
     test13113();
     test13147();
-}
+    test20924();
+}
```
Comment (thewilsonator) [inline compiler/test/runnable/testinvariant.d:287]: add a newline at end of file

**Review by thewilsonator — APPROVED** [review]

File: compiler/test/runnable/testinvariant.d (hunk 4 above)
Comment (abulgit) [reply compiler/test/runnable/testinvariant.d]: This is my first PR in this Repo, that's why I messed up

Comment (thewilsonator) [reply compiler/test/runnable/testinvariant.d]: That's totally fine, thats what review is for.

File: compiler/test/runnable/testinvariant.d (hunk 5 above)
Comment (abulgit) [reply compiler/test/runnable/testinvariant.d]: is it okay now?

Comment (thewilsonator) [reply compiler/test/runnable/testinvariant.d]: should be, fyi this is checked by the `pre-commit` checker. Though it fails for line 249 of the test file due to trailing whitespace. Just delete that line.

Comment (abulgit) [reply compiler/test/runnable/testinvariant.d]: Okay, I removed line 249.

**Comment by denizzzka** [comment]
Will it not break if C++ inheritance will be used?
