### PR TITLE
Fix Issue #22769: ICE on IFTI call inside interpolated string

### LINKED ISSUE #22769: ICE on IFTI call inside interpolated string
As of dmd 2.112:

```D
int foo()() => 0;

void bar() 
{   
    cast(void) i"$(foo)";
}
```

```
[onlineapp.d-mixin-5(5)] template: foo()()
Illegal instruction (core dumped)
```

### PR DESCRIPTION
**Pull request by oCHIKIo**
When I dug into the ICE crash, I discovered a fascinating blind spot in the compiler. It turns out that when an interpolated string like i"$(foo)" is parsed, it's quietly packaged into a tuple of expressions. Usually, that's fine, but wrapping it in cast(void) told the compiler to ignore the output. The property resolver took that cast(void) instruction at face value, looked at the tuple as a whole, and completely forgot to peek inside! Because of this oversight, the uninstantiated test template foo skipped past the safety checks and plunged straight into the code generator, which panicked and caused the compiler to crash. To fix this, I taught the compiler's property resolver to open up the tuple and recursively resolve every single element hidden inside before moving forward. Once the compiler started checking the elements properly, the crash completely vanished.

### CODE REVIEW

File: compiler/test/compilable/issue22769.d [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// https://issues.dlang.org/show_bug.cgi?id=22769
```
Comment (dkorpel) [inline compiler/test/compilable/issue22769.d]: That's not the right link

File: compiler/test/compilable/issue22769.d [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+int foo()() => 0;
+
+void bar() 
+{   
+    cast(void) i"$(foo)";
+}
+
+void baz()
+{
+    import std.meta : AliasSeq;
```
Comment (dkorpel) [inline compiler/test/compilable/issue22769.d]: The test suite may not import Phobos

**Comment by dkorpel** [comment]
I'm not sure handling TupleExp in resolveProperties is the right place to fix, because the issue is not limited to cast(void). This is closer to my actual code:

```D
int foo()() => 0;

struct OutBuffer
{
    void opOpAssign(string op, T...)(T args) {}
}

void bar() 
{   
    OutBuffer buf;
    buf ~= i"$(foo)";
}
```

Does this PR handle that as well? Maybe it's a separate issue for a separate PR, but a single unified fix would be nicer.

**Comment by oCHIKIo** [comment]
> I'm not sure handling TupleExp in resolveProperties is the right place to fix, because the issue is not limited to cast(void). This is closer to my actual code:
> 
> ```d
> int foo()() => 0;
> 
> struct OutBuffer
> {
>     void opOpAssign(string op, T...)(T args) {}
> }
> 
> void bar() 
> {   
>     OutBuffer buf;
>     buf ~= i"$(foo)";
> }
> ```
> 
> Does this PR handle that as well? Maybe it's a separate issue for a separate PR, but a single unified fix would be nicer.

@dkorpel good catch, the issue indeed goes beyond cast(void). I've pushed an overhaul that perfectly resolves your OutBuffer assignment case and removes the Phobos dependency in the tests.
Yes, resolvePropertiesX is statically the correct place for this fix. It acts as the gateway for IFTI resolution. By teaching it to peek inside the TupleExp generated by an interpolated string, we guarantee that items like foo are instantiated before they are punted to downstream expressionSemantic evaluations like your opOpAssign overload.

to prevent broad AST resolution regressions across the test suite, I ve made the hook strictly targeted:

Targeted IFTI Recursion: resolvePropertiesX now recursively evaluates elements within a TupleExp, but only if they are uninstantiated templates (EXP.template_) or unresolved overload sets. Standard tuple elements (like AliasSeq!foo) are entirely bypassed, preserving normal resolution behavior.
Flattened AST Blocks: Resolving interpolation items inside tuples can generate nested AST blocks. Appending expandTuples immediately flattens them, completely eliminating the segfault originally thrown natively by TypeTuple upon receiving nested constructs.
Let me know what you think of this architecture.

**Comment by oCHIKIo** [comment]
I redesigned the fix to be more targeted and safe. It moves the resolution logic directly into the lowering of interpolated strings, so expressions inside i"..." are now resolved for IFTI immediately. The compiler's type checker was also updated to recursively validate all tuple elements, which prevents crashes by turning unhandled templates into clean error messages. i updated the tests to cover assignment cases and removed all Phobos imports.

**Comment by oCHIKIo** [comment]
Apologies for the massive git noise in the previous push! I accidentally ran a broad amend command while my local environment was in a dirty state, which caused a huge number of unrelated changes to be included in the history. I have now forcefully reset the branch to be properly based on upstream/master and reapplied only the two relevant file changes. I'm still getting the hang of managing complex git histories on large projects like this, so I appreciate your patience while I fixed the mistake.

**Comment by oCHIKIo** [comment]
@dkorpel the CI is now fully green on all platforms. whenever you have a chance, let me know if this is good to merge

**Comment by dkorpel** [comment]
> Apologies for the massive git noise

No worries, and the code change looks really good now!

Only thing left - the link in the test and the commit message are still wrong, we're using GitHub issues now instead of Bugzilla.  Is there some stale documentation out there that makes you use the old convention?

**Comment by oCHIKIo** [comment]
I updated the link in the test to point to GitHub and removed "Bugzilla" from the commit message.
As for the stale documentation, it's actually the dlang-bot! When you open a PR, the bot leaves an automated comment saying: "Please add the word "Bugzilla" to issue references. For example, Fix Bugzilla Issue..." Since I'm new to the repo, I just followed what the bot told me to do. It looks like the bot's template hasn't been updated since the migration! am i wrong?

**Review by dkorpel — APPROVED** [review]

**Comment by dkorpel** [comment]
You're right, I'm just conditioned to completely ignore dlang-bot since it has been useless for so long.

**Comment by oCHIKIo** [comment]
If nobody is actively maintaining `dlang-bot` right now, I’d actually be happy to take a look at modernizing it. It feels pretty counterproductive that maintainers have to manually catch bad advice being handed out by the project's own automation. 
At a minimum, it should be updated to enforce/encourage GitHub Issue linking instead of Bugzilla syntax. But if fixing the bot is welcome, I could probably add some other modern productivity helpers too while I'm at it, such as:

1. **Auto-linking Bugzilla to GitHub Issues:** If someone accidentally uses the old syntax in a PR, the bot could automatically reply with the properly migrated GitHub Issue link to help them find what they're actually looking for.
2. **Commit squashing/formatting checks:** Having the bot statically analyze the PR to warn if "git noise" (like overly messy histories) is detected *before* maintainers have to comment on it.
3. **Automated Changelog verification:** The bot mentions manual changelogs but could be wired to actually verify the `.dd` file presence if the PR labels dictate a non-trivial change.

If that sounds useful, I can poke around `dlang/dlang-bot` and see what I can polish up!

**Comment by dkorpel** [comment]
dlang bot is so old and GitHub has changed so much since the bot's inception that it I'd just can the whole thing, as none of its existing capabilities have been useful lately. We can create modern solutions from scratch for whatever functionality we want to add, like the things you mentioned, or the upcoming [GSoC benchmark project](https://dlang.github.io/GSoC/gsoc-2026/perf_reg_test.html).

**Comment by oCHIKIo** [comment]
@dkorpel   That makes total sense regarding the bot. Starting fresh with modern GitHub Actions/Apps would definitely yield a cleaner, more maintainable architecture than trying to patch up legacy bot code.
Speaking of the GSoC benchmark project, I am actually planning to apply for GSoC with Dlang this year and I'm very interested in getting involved. Since you mentioned it, would you mind if I reached out to you briefly (via email, LinkedIn, or Discord/Slack) to ask a few quick questions about the project goals and how I can best prepare my application?
