### PR TITLE
Always make a copy when constructing mutable struct literals

### LINKED ISSUE #22585: Static initializer passed by reference to copy ctor
```d
struct S
{
    int a, b, c, d, e, f, g, h, i = 1;

    this(ref S s)
    {
        s.i = 2;
    }
}

struct T
{
    S s;
}

void f(S) {}

void main()
{
    bool b;
    f((b ? T.init : T.init).s);
}
```

Member access in D is a lvalue and will be passed by reference. The result is a segfault when trying to write read-only data.

### PR DESCRIPTION
**Pull request by limepoutine**
Fixes #22585, which is a superset of #22134. Due to (unfortunately) Rice's theorem, it's impossible to determine if an expression references a struct's static initializer symbol, so we have to disable all mutable references to it.

The performance impact is surprisingly small. Only 3 functions in druntime are affected.

### CODE REVIEW

File: compiler/test/runnable/structlit_rvalue.d [hunk 1]
```diff
@@ -1,15 +1,67 @@
-void refCounted(ProcessPipes val)
```
Comment (thewilsonator) [inline compiler/test/runnable/structlit_rvalue.d:1]: is there something wrong with the original test case? why remove it>?

Comment (limepoutine) [reply compiler/test/runnable/structlit_rvalue.d:1]: It's renamed somewhat excessively into the `assignCopyOf` case, not really removed.

**Review by thewilsonator — APPROVED** [review]
