### PR TITLE
Fix 18127 - ImportC: redeclaration of struct in different translation unit doesn’t check compatibility

### LINKED ISSUE #18127: ImportC: redeclaration of struct in different translation unit doesn’t check compatibility
### CC List

* Walter Bright (@WalterBright)
* Adam D. Ruppe

### Description

````markdown
// a.c
struct Foo {
    int x;
};
// b.c
struct Foo {
    int x, y;
};
//d.d
import a;
import b;

static assert(a.Foo.sizeof != b.Foo.sizeof); // Fails

The two structs are assumed to be the same type, size etc. and merged into one instead of iterating over their fields and ensuring all match (in other words, checking for compatibility before assuming they are the same).
````

### PR DESCRIPTION
**Pull request by drpriver**
Fixes: https://github.com/dlang/dmd/issues/18127

When merging struct definitions from different C imports, check that the structs are actually compatible according to the C rules. If they are not, issue an error.

### CODE REVIEW

File: compiler/src/dmd/dsymbolsem.d [hunk 1]
```diff
@@ -3091,10 +3091,242 @@ private extern(C++) final class DsymbolSemanticVisitor : Visitor
...
+                        // — there shall be a one-to-one correspondence between
+                        //   their members such that each pair of corresponding
+                        //   members are declared with compatible types;
+                        //
+                        if (!a_field.type.equals(b_field.type) && !isCCompatibleUnnamedStruct(a_field.type, b_field.type))
+                        {
+                            // Already errored, just bail
+                            incompatError();
+                            if(a_field.type.isTypeError()) return false;
+                            if(b_field.type.isTypeError()) return false;
```
Comment (thewilsonator) [inline compiler/src/dmd/dsymbolsem.d:3194]: space between `if` and `(`

File: compiler/src/dmd/dsymbolsem.d [hunk 2]
```diff
@@ -3091,10 +3091,242 @@ private extern(C++) final class DsymbolSemanticVisitor : Visitor
...
+                    // an anonymous id starting with __tag.
+                    if (!ats.sym.ident.toString().startsWith("__tag"))
+                        return false;
+                    if (!bts.sym.ident.toString().startsWith("__tag"))
+                        return false;
+                    return isCCompatible(ats.sym, bts.sym);
+                }
+
+                // Get the name of a type, while avoid exposing "__tagXXX" anonymous structs
+                static const(char)* typeName(Type t)
```
Comment (thewilsonator) [inline compiler/src/dmd/dsymbolsem.d:3111]: this functions in only called from within `isCCompatible` so make it a nested function of it.

File: compiler/src/dmd/dsymbolsem.d [hunk 3]
```diff
@@ -3091,10 +3091,242 @@ private extern(C++) final class DsymbolSemanticVisitor : Visitor
...
+                            return ts.sym.isUnionDeclaration() ? "(anonymous union)".ptr: "(anonymous struct)".ptr;
+                    }
+                    return t.toChars();
+                }
+
+                //
+                // Checks if two structs are compatible
+                // Implements the rules according to C23 6.2.7
+                //
+                static bool isCCompatible(StructDeclaration a, StructDeclaration b)
```
Comment (thewilsonator) [inline compiler/src/dmd/dsymbolsem.d:3125]: this function and isCCompatibleUnnamedStruct are together about the same length of the rest of `override void visit(StructDeclaration sd)`. Please move it out of here and make it a private static member of the visitor.

File: compiler/src/dmd/dsymbolsem.d (hunk 1 above)
Comment (drpriver) [reply compiler/src/dmd/dsymbolsem.d]: Fixed.

File: compiler/src/dmd/dsymbolsem.d (hunk 2 above)
Comment (drpriver) [reply compiler/src/dmd/dsymbolsem.d]: Moved.

File: compiler/src/dmd/dsymbolsem.d (hunk 3 above)
Comment (drpriver) [reply compiler/src/dmd/dsymbolsem.d]: Done.

**Review by thewilsonator — APPROVED** [review]
Thanks!
