### PR TITLE
Fix #18235 - Add offending member to "no size because of forward reference" error

### LINKED ISSUE #18235: Add offending member to "no size because of forward reference" error
### Description

````markdown
I don't have a testcase (I hit it on a complex codebase), but improvement is needed for the "no size because of forward reference" error reported by `AggregateDeclaration.determineSize` (https://github.com/dlang/dmd/blob/4414c2aeaa968ed0ce638a8162d3254dbf2ee2f5/compiler/src/dmd/aggregate.d#L237).

The error now reads:
`Error: struct `A` no size because of forward reference`
It is unclear what the forward reference is. Is there a forward reference inside struct `A`? Is struct `A` referenced elsewhere (if yes, where?) which constitutes the forward reference?

What helped me find the fwd reference quickly in the code, is hacking the compiler to add extra diagnostics. All paths that lead to the error (`goto LFail` or the "fallthrough" before `Lfail`) should store which struct member field is causing trouble, such that it can be reported upon error.

1. `determineSize` https://github.com/dlang/dmd/blob/4414c2aeaa968ed0ce638a8162d3254dbf2ee2f5/compiler/src/dmd/aggregate.d#L218
2. `determineFields` https://github.com/dlang/dmd/blob/4414c2aeaa968ed0ce638a8162d3254dbf2ee2f5/compiler/src/dmd/aggregate.d#L224
3. `finalizeSize` https://github.com/dlang/dmd/blob/4414c2aeaa968ed0ce638a8162d3254dbf2ee2f5/compiler/src/dmd/aggregate.d#L226

In my case, I added extra error output inside `finalizeSize` (https://github.com/dlang/dmd/blob/4414c2aeaa968ed0ce638a8162d3254dbf2ee2f5/compiler/src/dmd/dstruct.d#L297) which got me to the actual code problem.

````
Perhaps change this code:
```diff
        for (size_t i = 0; i < members.length; i++)
        {
            Dsymbol s = (*members)[i];
            s.setFieldOffset(this, &fieldState, isunion);
+          if (type.ty == Terror)
+          {
+               error(loc, "error on member `%s`", s.toPrettyChars);
+               errors = true;
+               return;
+           }
        }
-        if (type.ty == Terror)
-        {
-            .error(loc, "finalizeSize err");
-            errors = true;
-            return;
        }
```

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

File: compiler/src/dmd/dstruct.d [hunk 1]
```diff
@@ -171,11 +171,12 @@ extern (C++) class StructDeclaration : AggregateDeclaration
...
             Dsymbol s = (*members)[i];
             s.setFieldOffset(this, &fieldState, isunion);
-        }
-        if (type.ty == Terror)
-        {
-            errors = true;
-            return;
+            if (type.ty == Terror)
+            {
+                errorSupplimental(loc, "error on member `%s`", s.toPrettyChars);
```
Comment (ntrel) [inline compiler/src/dmd/dstruct.d:176]:
```suggestion
                errorSupplemental(loc, "error on member `%s`", s.toPrettyChars);
```
