### PR TITLE
Fix #18281 - ICE on attempt to compare deref of two functions ptr

### LINKED ISSUE #18281: ICE on attempt to compare deref of two functions ptr
### Description

The following input

```
void function(int) a;
void function(int) b;

void main()
{
    const c = *a == *b;
    // assert(*a); // rejected during sema
}     
```

crashes dmd in the backend:

> TYD func
> 
> Program received signal SIGILL, Illegal instruction.
> 0x00005555559d1756 in dmd.backend.cod3.jmpopcode(dmd.backend.el.elem*) ()

I think however that the program is semantically invalid and should be rejected during exp-semantics, just like the commented assertion is.

### PR DESCRIPTION
**Pull request by dkorpel**
Closes #18281

### CODE REVIEW

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -13877,6 +13888,12 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
         if (exp.e2.op == EXP.call)
             exp.e2 = (cast(CallExp)exp.e2).addDtorHook(sc);
 
+        if (exp.e1.type.isTypeFunction() || exp.e1.type.isTypeFunction())
```
Comment (thewilsonator) [inline compiler/src/dmd/expressionsem.d:13891]:
```
expressionsem.d(13891:42)[warn]: Left side of logical or is identical to right side.
```
I presume you meant 
```diff
-if (exp.e1.type.isTypeFunction() || exp.e1.type.isTypeFunction())
+if (exp.e1.type.isTypeFunction() || exp.e2.type.isTypeFunction())
```

Comment (dkorpel) [reply compiler/src/dmd/expressionsem.d]: Indeed, thanks!
