### PR TITLE
druntime: Only use async-signal safe fork in GC

### LINKED ISSUE #21834: druntime: fork based garbage collector and async safety
@schveiguy - I was going to post in the PR thread, but felt it better to brain dump here.

> > I'll have to dig up the PR that introduced the forking GC to see whether the rationale for using __fork is to be found there.
> 
> Initial PR [dlang/druntime#2604](https://github.com/dlang/druntime/pull/2604)
> 
> Subsequent PR that got accepted [dlang/druntime#3514](https://github.com/dlang/druntime/pull/3514)

I'm starting to recall this rabbit hole that briefly looked into circa 2021.

The current sitution in druntime for the COLLECT_FORK GC is this :
- Linux platforms call `clone()` to fork
- macOS platforms call an undocumented, private/internal `__fork` function.
- Every other platform uses regular `fork()` with some weak form of guard around the call to prevent the internal GC atfork handlers from aquiring the GC lock.

https://github.com/dlang/dmd/blob/73846450e54832ae0d40b9bf505fb165124cd9cd/druntime/src/core/internal/gc/impl/conservative/gc.d#L3194-L3221

AFAIU, for the D fork GC implementation to be truly viable, it needs access to an async-safe version of fork - and according to Posix standard the only safe fork is one that doesn't call `pthread_atfork` handlers - otherwise, you'll just be chasing unicorns dealing with all platform-specific edge cases that result in deadlocks.

For instance, we have no control over whether libc fork acquires any internal locks for malloc/threading/... - so if the process crashes inside a handler (and we have no control over user-installed atfork handlers outside of druntime), there's no way to recover.

- On Posix, this is `_Fork()` ([link](https://pubs.opengroup.org/onlinepubs/9799919799/functions/fork.html)), only added in issue 8 of the IEEE spec, so few systems have bothered implementing it, and certainly is non-existent on systems older than 2021 (Ubuntu 20.04 is in support until 2030, for example).
- On Linux, there is `clone()` ([link](https://www.man7.org/linux/man-pages/man2/clone.2.html))
- On macOS, this doesn't exist, but druntime uses `__fork` ([link](https://github.com/apple-oss-distributions/Libc/blob/63976b830a836a22649b806fe62e8614fe3e5555/sys/fork.c#L68-L71)) instead, which doesn't exist in old versions such as 10.6 - I'm aware of the Go using `__fork` at one point in time too, but it looks like they got told off by the developers working at Apple and they call two [seemingly random undocumented libc functions](https://github.com/golang/go/blob/master/src/runtime/sys_darwin.go#L213-L243) in C main start-up instead. 🤷 
- On FreeBSD, there is `_Fork` ([link](https://man.freebsd.org/cgi/man.cgi?fork(2))), only added in FreeBSD 13.1, but I guess we don't care for older EOL systems, or if we do care, there's always `syscall(SYS_fork)` ([link](https://github.com/freebsd/freebsd-src/blob/main/lib/libc/sys/POSIX2x_Fork.c#L40))

On everything else, this doesn't exist, **but we know** that a proper implementation of `_Fork` at the very least _should_ just forward to a fork syscall and do nothing else - however other valid behaviours would include blocking all signals before and after the syscall, 

- On NetBSD, there is `syscall(SYS_fork)` ([link](https://github.com/NetBSD/src/blob/trunk/lib/libc/gen/pthread_atfork.c#L57-L60)), the value of the macro is 2.
- On OpenBSD, there is `syscall(SYS_fork)` ([link](https://github.com/openbsd/src/blob/91574edd58d3cc5917bcb4b660d0fbb362e99ca9/lib/libc/sys/w_fork.c#L65)), the value of the macro is 2.
- On Solaris, there is `syscall(SYS_forksys, 0, 0)` ([link](https://github.com/illumos/illumos-gate/blob/489f6310fe8952e87fc1dce8af87990fcfd90f18/usr/src/lib/libc/amd64/sys/forkx.S#L32)), the value of the macro is 142.
- On DragonFlyBSD, there is `syscall(SYS_fork)` ([link](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/6098912863ed4c7b3f70d7483910ce2956cf4ed3/lib/libc/sys/fork.c#L49)), the value of the macro is 2.
- On macOS, syscall has been deprecated since 10.12, and even then SYS_fork doesn't follow the C calling convention, so can't be called directly from D, rather some inline asm wrapper around to fetch the real return value -> too much hassle to really bother with.

As it's always interesting to see what other runtimes are doing, I stumbled across Mono's implementation of a crash-safe fork.

https://github.com/mono/mono/blob/0f53e9e151d92944cacab3e24ac359410c606df6/mono/metadata/threads.c#L6441-L6455

### PR DESCRIPTION
**Pull request by ibuclaw**
Removes the use of `fork` for Posix and the undocumented `__fork` for OSX, now the fork-based GC is only ran if linux/clone or Posix/_Fork is available, this removes the need to have `pthread_atfork` handler guards, as they are guaranteed to never be called.

### CODE REVIEW

File: druntime/src/core/internal/gc/impl/conservative/gc.d [hunk 1]
```diff
@@ -50,6 +50,18 @@ import core.thread;
...
+version (OSX)
+{
+    version (GNU)
+    {
+        import gcc.config : Have___fork;
+        enum OSX_Internal_Fork = Have___fork;
+    }
+    else
+    {
+        enum OSX_Internal_Fork = true;
```
Comment (iains) [inline druntime/src/core/internal/gc/impl/conservative/gc.d]: why default to true?

The property is of the OS, not the compiler - so if we have an LLVM-based impl. on Darwin9 or 10, __fork() would still be missing.

I guess the question would then be how to detect that in those case?

**Review by iains — COMMENTED** [review]
just one question

File: druntime/src/core/internal/gc/impl/conservative/gc.d (hunk 1 above)
Comment (schveiguy) [reply druntime/src/core/internal/gc/impl/conservative/gc.d]: Looks like the original always used `__fork`, see change under `version(COLLECT_FORK)` below.

So this strictly is just making a change for GNU only, and leaving the original code intact.

Whether that's correct or not, I don't know. LDC maintains a ported version of druntime, but looks like it's not modified: https://github.com/ldc-developers/ldc/blob/83362a71810a4c2d7ddcf7fec030aa2ca5bc7467/runtime/druntime/src/core/internal/gc/impl/conservative/gc.d#L104

**Comment by schveiguy** [comment]
Would it be more readable to use an alias based on the configuration instead of adding a new config enumeration?

```d
static if(Have___fork) alias OSX_fork = __fork;
else alias OSX_fork = fork;

// now use OSX_fork everywhere
```

Not sure of the name though.

File: druntime/src/core/internal/gc/impl/conservative/gc.d (hunk 1 above)
Comment (iains) [reply druntime/src/core/internal/gc/impl/conservative/gc.d]: agreed that this maintains the status quo, and perhaps no one has ever tried to build LDC on an older system (although macports, at least does build LLVM/clang there)

Comment (schveiguy) [reply druntime/src/core/internal/gc/impl/conservative/gc.d]: I think collect fork support on OSX is more recent than any of those OSes (original was Linux only, and circa 2016 I think?). One could always just disable the feature if you want to build for that system, parallel collect is an optimization option.

Comment (ibuclaw) [reply druntime/src/core/internal/gc/impl/conservative/gc.d]: If LDC wanted to support other Darwin's then they'd add their own version branch.

I went with default true, as:
1. It's already the current assumption that it exists.
2. DMD doesn't support macOS prior to 10.9 - the first version with native TLS support.  I guess that will be the same with LDC too.

**Comment by schveiguy** [comment]
A further question, is this change actually valid on those OSes? Wouldn't calling `fork` incur the same problems we are avoiding by calling `__fork`? A better change might just be to disable the fork collector if it's not available.

File: druntime/src/core/internal/gc/impl/conservative/gc.d (hunk 1 above)
Comment (ibuclaw) [reply druntime/src/core/internal/gc/impl/conservative/gc.d]: @schveiguy right, though maybe opt-in would be more build friendly than disable. Those `COLLECT_FORK` and `COLLECT_PARALLEL` versions set at the top of this file could be moved to the makefiles - but that may be a thought best to defer until later.

**Comment by ibuclaw** [comment]
> A further question, is this change actually valid on those OSes? Wouldn't calling `fork` incur the same problems we are avoiding by calling `__fork`? A better change might just be to disable the fork collector if it's not available.

I think it may be that `gcopt=fork:1` is not tested within gdc's testsuite.  I'll have to dig up the PR that introduced the forking GC to see whether the rationale for using `__fork` is to be found there.  The introduction of `COLLECT_FORK` code long predates the atfork handlers in the GC for example.

**Comment by iains** [comment]
I don't have many data-points yet - but it does appear that (despite the potential issues) fork() is currently working on the cases I've tried - of course, possible race conditions mean that one would need more samples before being sure.

**Comment by ibuclaw** [comment]
> I'll have to dig up the PR that introduced the forking GC to see whether the rationale for using __fork is to be found there. 

Initial PR https://github.com/dlang/druntime/pull/2604

Subsequent PR that got accepted https://github.com/dlang/druntime/pull/3514

**Comment by ibuclaw** [comment]
> A further question, is this change actually valid on those OSes? Wouldn't calling `fork` incur the same problems we are avoiding by calling `__fork`? A better change might just be to disable the fork collector if it's not available.

Ah, yes. I forgot about adding in the `fork_needs_lock` guards.

**Comment by ibuclaw** [comment]
@schveiguy @iains - retracted the original change, and replaced with the complete removal of both `__fork` and `fork` from the fork-based GC.  Opting instead to one use one of `clone` on linux or `_Fork` if available on any other Posix system, which as far as I know is just FreeBSD (soft depends on #21836) - this means there's no need for the `fork_needs_lock` guard/hack anymore, as the pthread atfork handlers are guaranteed to not be called.

I've tested the `_Fork` path on Linux, and it passes the full druntime GC testsuite.

**Comment by iains** [comment]
out of curiosity - what do platforms without either clone or _Fork use?

**Comment by ibuclaw** [comment]
> out of curiosity - what do platforms without either clone or _Fork use?

Just the regular mark/sweep GC without forking - the `--DR-gcopt=fork:1` config option just gets ignored. It may still do parallel marking though.

**Comment by ibuclaw** [comment]
@schveiguy any other nits/concerns wrt this approach?

**Comment by schveiguy** [comment]
I'm reading the `HaveFork` and `AllocSupportsFork` changes, and I'm completely confused as to the logic for this.

It seems that if `HaveFork` was true, we were just using `calloc` to allocate bits. But if it was false, then we are using OS mmap facilities.

And for Windows (i.e. VirtualAlloc exists), then we are... not using calloc? I am completely lost on the logic. I know this is not your mess, and you are also trying to make sense of it, but I don't understand the point of this whole thing.

And on top of this, in the fallback case, we *still use malloc* as the "OS" mapping facility!

So what is the point of this whole `HaveFork` thing? It appears like it was there since the original forking GC was integrated.

**Comment by ibuclaw** [comment]
> I'm reading the `HaveFork` and `AllocSupportsFork` changes, and I'm completely confused as to the logic for this.
> 

I share your confusion. The attempt was to rename it to something more representative of what it's meant to mean.

> It seems that if `HaveFork` was true, we were just using `calloc` to allocate bits. But if it was false, then we are using OS mmap facilities.
> 

No, inverse is the case.  `HaveFork` means we are using  `os_mem_map`.

> And for Windows (i.e. VirtualAlloc exists), then we are... not using calloc? I am completely lost on the logic. I know this is not your mess, and you are also trying to make sense of it, but I don't understand the point of this whole thing.
> 
> And on top of this, in the fallback case, we _still use malloc_ as the "OS" mapping facility!
> 
> So what is the point of this whole `HaveFork` thing? It appears like it was there since the original forking GC was integrated.

`HaveFork` is only set to `true` for the `mmap` allocation strategy, as that is the only function where a fork'd child can share newly allocated memory with its parent, IIUC.  (Didn't check whether this also applies to COLLECT_PARALLEL too).

I was thrown by why it would be false in the first place (i.e: if there's `valloc` available, then `fork` will exist too).

However, the observed behaviour of setting `HaveFork = true` for all other allocators resulted in live memory being freed by the GC.

**Comment by ibuclaw** [comment]
> > I'm reading the `HaveFork` and `AllocSupportsFork` changes, and I'm completely confused as to the logic for this.
> 
> I share your confusion. The attempt was to rename it to something more representative of what it's meant to mean.
> 
> > It seems that if `HaveFork` was true, we were just using `calloc` to allocate bits. But if it was false, then we are using OS mmap facilities.
> 
> No, inverse is the case. `HaveFork` means we are using `os_mem_map`.
> 

The `share` variable is only set to true if `COLLECT_FORK` and `config.fork` is true.  However the `HaveFork` gate should ensure that a fork never occurs elsewhere in the bowels of the conservative gc.

Yes, it's a bit of a mess.

**Comment by rainers** [comment]
As Iain said `HaveFork` just specifies that os_mem_map() supports allocating memory that is shared between processes. So the new name is an improvement, but pedantically it is not tied to whether fork is used by the concurrent GC. The latter just happens to use shared memory to communicate information back from the fork to the running process.

So a more accurate name might be AllocSupportsShared, and this could be combined with the existence of a fork variant (that doesn't execute handlers to avoid deadlocks i.e clone or _Fork), to determine whether a forking GC could run.

Would be nicer if the variants of fork could be moved into core.internal.gc.os, too, but that's a bit troublesome as `clone` works differently compared to `_Fork`, so probably for another PR.

**Review by rainers — APPROVED** [review]

**Comment by schveiguy** [comment]
Whoa, ok, now that you explain that, I see it. I honestly didn't notice that there was a second parameter to `os_mem_map`.

But there is a huge disconnect here! If `HaveFork` was false, and we have a Posix system, then if you ran a forked collect you would then expect the child process to affect the mark bits but it wouldn't?

> So a more accurate name might be AllocSupportsShared

Yes, can we switch to this? It's way more descriptive!

**Comment by schveiguy** [comment]
I might even suggest that instead of the share parameter, we have a differently named function. It's kind of insane that these are the same function, but only define the second parameter when this is supported? This just seems like a different function to me...

**Comment by rainers** [comment]
> But there is a huge disconnect here! If `HaveFork` was false, and we have a Posix system, then if you ran a forked collect you would then expect the child process to affect the mark bits but it wouldn't?

Yes, that's why Iains' gate `shouldFork = AllocSupportsFork && config.fork;` is good. The other way around, i.e. having shared memory, but no fork, currently creates shared memory, but doesn't run concurrently as `clone` and `_Fork` are only "detected" in `markFork`.

BTW: `core.internal.gc.os` always imports `mmap` from `core.sys.posix.sys.mman` for version Posix, so the definition of `HaveFork` is pretty much coupled to Posix. We could keep `HaveFork` in addition to `AllocSupportsShared`, but move it up to where `wait_pid` is declared with some conditionals matching what is happening in `markFork`, and add it to the gate above.

> I might even suggest that instead of the share parameter, we have a differently named function.

Fine with me. That would require a matching `os_mem_unmap_shared` function.

**Comment by ibuclaw** [comment]
> > But there is a huge disconnect here! If `HaveFork` was false, and we have a Posix system, then if you ran a forked collect you would then expect the child process to affect the mark bits but it wouldn't?
> 
> Yes, that's why Iains' gate `shouldFork = AllocSupportsFork && config.fork;` is good.

I tested the forking GC with valloc and malloc, which is what prompted me to add that.  Obviously the combination was never checked.

File: druntime/src/core/internal/gc/os.d [hunk 2]
```diff
@@ -116,13 +120,13 @@ else static assert(false, "No supported allocation methods available.");
 static if (is(typeof(VirtualAlloc))) // version (GC_Use_Alloc_Win32)
 {
     /**
-    * Indicates if an implementation supports fork().
+    * Indicates if an allocation method supports between processes.
```
Comment (rainers) [inline druntime/src/core/internal/gc/os.d]: "sharing memory" missing here.

**Comment by ibuclaw** [comment]
Defining a separate function makes the enum semi-redundant. Can just check for the existence of `os_mem_map_shared` instead of `AllocSupportedShared`

File: druntime/src/core/internal/gc/os.d (hunk 2 above)
Comment (ibuclaw) [reply druntime/src/core/internal/gc/os.d]: Yes, hands slower than head.

**Comment by ibuclaw** [comment]
I've put just the `AllocSupportsShared` changes with here #21872, as it's likely starting to detract from the main reason for this PR. :-)

**Review by schveiguy — APPROVED** [review]
