### PR TITLE
[stable] Try to fix #21331

### LINKED ISSUE #21331: [REG2.111] Colliding lambda symbol mangles
Since v2.111, DMD might emit multiple different lambdas with the same mangle. This isn't caught by DMD, but LDC emits a warning at least if the colliding lambdas happen to be codegen'd into the same object file. We hit such a case at Symmetry.

After a long dustmite session and simplifying stuff manually, the ~220-lines testcase still depends a little bit on Phobos (but just `std.meta` and `std.traits`):
<details>

```D
import std.meta : anySatisfy, staticMap, AliasSeq, Filter;
import std.traits : isCallable, FunctionTypeOf, Parameters, ReturnType;

struct ParamTypeMaps(maps...) {
    alias typeMaps = maps;
}

struct TypeMaps(ParamMaps) {
    alias paramMaps = ParamMaps.typeMaps;
}

template findParamMap(TargetType, paramMaps...) {
    alias paramMap = findParamMapSingle!(TargetType, paramMaps);
    static if (paramMap.length)
        alias findParamMap = paramMap;
    else
        alias findParamMap = resolveParamTypeMap!TargetType;
}

template findParamMapSingle(TargetType, paramMaps...) {
    enum returnsTargetType(alias paramMap) = is(ReturnType!paramMap == TargetType);
    alias findParamMapSingle = Filter!(returnsTargetType, paramMaps);
}

alias resolveParamTypeMap(TargetType) = findParamMapSingle!TargetType;

enum hasParamMap(TargetType, paramMaps...) = findParamMap!(TargetType, paramMaps).length;

template mapParam(alias fun, size_t idx, TMs) {
    alias Param = BetterParams!fun[idx .. idx + 1];
    alias paramMap = findParamMap!(Param, TMs.paramMaps);
    static if (paramMap.length) {
        enum paramName = __traits(identifier, Param);
        mixin("
\t\t\tParam[0] mapParam(@getParamUDAs!(fun, idx) @getParamUDAs!(paramMap, 0) Parameters!paramMap[0] " ~ paramName ~ ") {
\t\t\t\treturn paramMap[0](" ~ paramName ~ ");
\t\t\t}
\t\t");
    }

    auto mapParam(Param _args) {
        return _args[0];
    }
}

template needsTranslation(alias fun, TMs) {
    enum needsParamMap(ParamT) = hasParamMap!(ParamT, TMs.paramMaps);
    enum needsTranslation = anySatisfy!(needsParamMap, Parameters!fun);
}

template translateFunction(alias fun, TMs) if (needsTranslation!(fun, TMs)) {
    enum funName = __traits(identifier, fun);
    alias PS = BetterParams!fun;
    string translateStr() {
        string[] lambdaArgs;
        string[] mappedArgs;
        foreach (i, param; PS) {
            enum paramName = __traits(identifier, PS[i .. i + 1]);
            lambdaArgs ~= "BetterParams!(mapParam!(fun, " ~ i.stringof ~ ", TMs))";
            mappedArgs ~= "mapParam!(fun, " ~ i.stringof ~ ", TMs)(" ~ paramName ~ ")";
        }

        string ret = "auto " ~ funName ~ "(";
        foreach (a; lambdaArgs)
            ret ~= a ~ ", ";
        ret ~= ")\n{\n";
        ret ~= "\tfun(";
        foreach (a; mappedArgs)
            ret ~= a ~ ", ";
        ret ~= ");\n";
        ret ~= "};";
        ret ~= "\nalias translateFunction = " ~ funName ~ ";";
        return ret;
    }

    mixin(translateStr);
}

template translateFunction(alias fun, TMs) if (!needsTranslation!(fun, TMs)) {
    alias translateFunction = fun;
}

template getParamUDAs(alias fun, size_t paramIdx) {
    alias P = BetterParams!fun[paramIdx .. paramIdx + 1];
    alias getParamUDAs = __traits(getAttributes, P);
}

template getSILtype(alias fn, size_t paramIdx) {
    enum isSILtype() = false;
    alias types = Filter!(isSILtype, getParamUDAs!(fn, paramIdx));
}

template BetterParams(func...) {
    static if (is(FunctionTypeOf!func P == __parameters))
        alias BetterParams = P;
}

template paramTypeNameOverride(alias fn, size_t paramIdx) {
    alias silType = getSILtype!(fn, paramIdx);
    enum paramTypeNameOverride = "";
}

template ParameterNames(alias fun) {
    alias Ps = BetterParams!fun;
    enum paramName(size_t i) = __traits(identifier, Ps);
    alias ParameterNames = staticMap!(paramName, staticIota!(0, Ps.length));
}

void createFunctionOverloadImpl(alias handler)() {
    alias paramNames = ParameterNames!handler;
    alias PS = Parameters!handler;

    foreach (i, argName; paramNames) {
        string typeNameOverride = paramTypeNameOverride!(handler, i);
        auto dg = () => convertParam!(PS[i])();
    }
}

template isPubliclyVisible(alias sym) {
    enum v = __traits(getVisibility, sym);
    enum isPubliclyVisible = v == "public" ;
}

struct Handlers {
    void registerType(T, TMs)() {
        new Accessor!(T, TMs);
    }
}

template MethodSpec(T, string n, size_t i = 0) {
    alias Type = T;
    enum name = n;
    enum overload = i;
}

template getMethod(T, string name, size_t overload) {
    alias getMethod = __traits(getOverloads, T, name, true)[overload];
}

alias getMethod(alias method) = getMethod!(method.Type, method.name, method.overload);

auto callMethod(alias method)(BetterParams!(getMethod!method)) {}

template isBindableMethod(alias method) {
    alias resolvedMethod = getMethod!method;
    enum isBindableMethod = isPubliclyVisible!resolvedMethod;
}

template AllBindableOverloads(T, string fn) {
    alias member = __traits(getMember, T, fn);
    static if (isCallable!member)
        alias AllBindableOverloads = Filter!(isBindableMethod, MethodSpec!(T, fn));
    else
        alias AllBindableOverloads = AliasSeq!();
}

template OverloadSetSpec(Os...) {
    alias Overloads = Os;
}

template BindableOverloadSets(T, string fn) {
    alias overloads = AllBindableOverloads!(T, fn);
    static if (overloads.length) {
        alias BindableOverloadSets = OverloadSetSpec!overloads;
    } else {
        template makeOverloadSet() {}
        alias BindableOverloadSets = staticMap!makeOverloadSet;
    }
}

template AllBindableOverloadSets(T) {
    alias bindableOverloadSets(string fn) = BindableOverloadSets!(T, fn);
    alias AllBindableOverloadSets = staticMap!(bindableOverloadSets, __traits(allMembers, T));
}

class Accessor(T, TMs) {
    this() {
        foreach (overloadSet; AllBindableOverloadSets!T) {
            foreach (method; overloadSet.Overloads) {
                alias translatedMethod = translateFunction!(callMethod!method, TMs);
                alias TranslatedPs = BetterParams!translatedMethod;
                createFunctionOverloadImpl!((TranslatedPs _args) {})();
            }
        }
    }
}

template getOverloads(alias symbol) {
    alias parent = __traits(parent, symbol);
    enum name = __traits(identifier, symbol);
    alias getOverloads = __traits(getOverloads, parent, name);
}

bool convertParam(DesiredParamT)() {
    return false;
}

template staticIota(size_t begin, size_t len) {
    static if (len == 0) {
        alias staticIota = AliasSeq!();
    } else static if (len == 1) {
        alias staticIota = AliasSeq!(begin);
    } else static if (len == 2) {
        alias staticIota = AliasSeq!(begin, begin + 1);
    } else {
        alias staticIota =
            AliasSeq!(staticIota!(begin, len / 2),
                      staticIota!(begin + len / 2, len - len / 2));
    }
}



ubyte integerToUbyte(int ) {
    return 0;
}

void registerHandlersDateTime(Handlers handlers) {
    import std.datetime : Date;
    alias PMs = ParamTypeMaps!integerToUbyte;
    alias TMs = TypeMaps!PMs;
    handlers.registerType!(Date, TMs);
}
```

</details>

With v2.110, we have a single definition for a particular lambda symbol:
```
$ ~/dlang/dmd-2.110.0/linux/bin64/dmd -c lang.d
$ objdump -t lang.o | grep _D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
0000000000000000 l    d  .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb	0000000000000000 .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
0000000000000000  w    F .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb	000000000000000b _D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
```

With v2.111, we have 2 definitions in that single object file:
```
$ ~/dlang/dmd-2.111.0/linux/bin64/dmd -c lang.d
$ objdump -t lang.o | grep _D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
0000000000000000 l    d  .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb	0000000000000000 .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
0000000000000000  w    F .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb	000000000000000b _D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
0000000000000000  w    F .text._D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb	000000000000000b _D4lang__T26createFunctionOverloadImplS_DQBn__T8AccessorTS3std8datetime4date4DateTSQDd__T8TypeMapsTSQDu__T13ParamTypeMapsS_DQEs14integerToUbyteFiZhZQBqZQClZQEf6__ctorMFZ20__lambda_L182_C45_14FNaNbNiNfsiEQFpQFoQFi9DayOfWeekZvZQIhFZ17__lambda_L115_C19FNaNbNiNfZb
```

---

This is a horrible bug. E.g., faking this:
```D
int foo() { return 1; }

pragma(mangle, foo.mangleof)
int foo2() { return 2; }

void main() {
    assert(foo() == 1);
    assert(foo2() == 2); // fails - the first `foo()` 'wins' - the linker seems to concatenate the sections, so the code for `foo2` is still there but never reached
}
```

### PR DESCRIPTION
**Pull request by kinke**
See https://github.com/dlang/dmd/pull/17102#issuecomment-2851124927 and following.

### CODE REVIEW

File: compiler/test/compilable/test21331.sh [hunk 1]
```diff
@@ -0,0 +1,11 @@
+#!/usr/bin/env bash
+
+objfile="${OUTPUT_BASE}${OBJ}"
+$DMD -c -m${MODEL} -of${objfile} ${EXTRA_FILES}/${TEST_NAME}.d
+
+nm ${objfile} | grep -E '16__lambda_L13_C17.+15__lambda_L5_C19'
+nm ${objfile} | grep -E '16__lambda_L13_C17.+17__lambda_L5_C19_1'
+nm ${objfile} | grep -E '18__lambda_L13_C17_1.+15__lambda_L5_C19'
+nm ${objfile} | grep -E '18__lambda_L13_C17_1.+17__lambda_L5_C19_1'
```
Comment (kinke) [inline compiler/test/compilable/test21331.sh:9]: I gave up on a testcase for the actual issue, wrt. empty tuples in parameter UDAs being 'optimized' later and affecting `toPrettyChars()`.

Instead, I went with this - v2.111 produces these symbols:
```
_D9test21331__T1SSQq3barFZ16__lambda_L13_C17ZQBe3fooMFZ__T15__lambda_L5_C19TiZQuFNaNbNiNfiZi
_D9test21331__T1SSQq3barFZ16__lambda_L13_C17ZQBe3fooMFZ__T17__lambda_L5_C19_1TiZQwFNaNbNiNfiZi
_D9test21331__T1SSQq3barFZ18__lambda_L13_C17_1ZQBg3fooMFZ__T17__lambda_L5_C19_2TiZQwFNaNbNiNfiZi
_D9test21331__T1SSQq3barFZ18__lambda_L13_C17_1ZQBg3fooMFZ__T17__lambda_L5_C19_3TiZQwFNaNbNiNfiZi
```

I.e., the inner lambda got renamed to `_2` and `_3` when the outer one was renamed to `_1`. Using the parent mangle avoids this and makes the inner one start without suffix again.

File: compiler/src/dmd/expressionsem.d [hunk 2]
```diff
@@ -5688,6 +5689,7 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
                 func.localsymtab = new DsymbolTable();
             }
             symtab = func.localsymtab;
+            parentMangle = cast(string) mangleExact(func).toDString();
```
Comment (kinke) [inline compiler/src/dmd/expressionsem.d:5692]: This one is cached (in `FuncDeclaration.mangleString`).

**Review by thewilsonator — APPROVED** [review]

**Comment by yanok** [comment]
Is merging blocked on failed CI tasks? They seem to be irrelevant. Can we rebase and retry?

**Comment by kinke** [comment]
Yeah those failures are obviously unrelated and fixed in the meantime.

The only thing I'm unsure about is whether getting the mangle of the parent might have unexpected side effects, like extra semantic analysis for the parent.

**Comment by kinke** [comment]
I *guess* what could happen is that parent function mangles are now generated earlier, potentially before semantic analysis of the parent is completed. And as they are cached in `FuncDeclaration.mangleString`, the final mangle might be based on incomplete attribute inference.

The first variant, using the class-ref identity of the parent, seems safer in that regard. So I rather tend towards the original variant.

**Comment by thewilsonator** [comment]
This good to go?

**Comment by kinke** [comment]
No; I was hoping @yanok would give some feedback wrt. reverting to the original variant.

**Comment by yanok** [comment]
> I _guess_ what could happen is that parent function mangles are now generated earlier, potentially before semantic analysis of the parent is completed. And as they are cached in `FuncDeclaration.mangleString`, the final mangle might be based on incomplete attribute inference.

Yes, that might be the case. But did we see anything like this in the wild? With a proper dependency tracking I believe asking for a mangle should trigger all the inference and complain if it has to be changed later... but that's not the case with the current implementation...
 
> The first variant, using the class-ref identity of the parent, seems safer in that regard. So I rather tend towards the original variant.

I had some concerns about multiple `TemplateInstance` instances for the same template with the same arguments. But of course the code is smart enough to only analyze the same instantiation once, so that's not an issue.

**Comment by yanok** [comment]
I'm going to test building Weka code with the first version of the fix today, will post an update here.

**Comment by yanok** [comment]
> Yes, that might be the case. But did we see anything like this in the wild?

To answer my own question: yes, I do indeed see mangles of symbols loosing attributes wrt to unpatched ldc version, so the version with parent's mangle has undesired side-effects indeed.

Still verifying the version with the ref comparison, the first results are good.

**Comment by yanok** [comment]
I did  testing with the ref comparison (the version in the first commit), so far so good. So I guess that's the version we want to proceed with.

In the long run, we probably want to shift the uniqueness logic from `generateIdWithLoc` to the callers: there are only a handful of places there adding suffixes to ids is the desirable behavior: static foreach, foreach unrolling, anything else?

**Comment by kinke** [comment]
Perfect Ilya, thx a lot for testing! So I guess this is ready now; the commits are to be squashed (I left the 2nd variant in, just so that it's in the history of this PR).

> In the long run, we probably want to shift the uniqueness logic from generateIdWithLoc to the callers: there are only a handful of places there adding suffixes to ids is the desirable behavior: static foreach, foreach unrolling, anything else?

Yeah I *guess* it's only statically unrolled loops which require the suffices for all nested lambdas.
