### PR TITLE
SAOC 2025: fix #20092: importC: can't take address of some compound-literals

### LINKED ISSUE #20092: importC: can't take address of some compound-literals
### CC List

* Walter Bright (@WalterBright)
* 

### Description

````markdown
void fn()
{ 
	int *a = &(int[1]){0};
	int *b = &(int){0};
}

test.c(3): Error: `[0]` is not an lvalue and cannot be modified
test.c(4): Error: cannot modify constant `0`

array one works if & is removed

int one should be the same as taking the address of a local variable typed "int"
````

### PR DESCRIPTION
**Pull request by Emmankoko**
This PR proposes a fix for:
https://issues.dlang.org/show_bug.cgi?id=23053

@dkorpel gave me an insight into using `copyToTemp` which led to using `extractSideEffect` which creates a temporary var and then we take the address for the pointer.
for globals, I couldn't trust on them since we strictly needs `static,` `const` and `ctfe` and symbol table push.

### CODE REVIEW

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -5271,8 +5271,47 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
             error(cle.loc, "cannot convert initializer `%s` to expression", toChars(init));
             return setError();
         }
-        result = e;
-        return;
+
+        // leave these to be handled by their respective functions
```
Comment (thewilsonator) [inline compiler/src/dmd/expressionsem.d:5275]: this is for ImportC right? why is this not guarded by `if (sc.inCfile)` (or whatever it is called)?

File: compiler/src/dmd/expressionsem.d [hunk 2]
```diff
@@ -5271,8 +5271,47 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
...
+            result = e;
+            return;
+        }
+
+        if (sc.func)
+        {
+            Expression e0;
+            auto ve = extractSideEffect(sc, "__cl", e0, e, true);
+
+            // ship (int a = 5, a) so a doesn't forward ref
```
Comment (thewilsonator) [inline compiler/src/dmd/expressionsem.d]: skip?

File: compiler/src/dmd/expressionsem.d (hunk 1 above)
Comment (dkorpel) [reply compiler/src/dmd/expressionsem.d:5275]: CompoundLiteralExp is a C-only AST node

Comment (thewilsonator) [reply compiler/src/dmd/expressionsem.d:5275]: Ah, OK.

**Review by thewilsonator — APPROVED** [review]
Apart from the comment typo, this looks good.

File: compiler/src/dmd/expressionsem.d (hunk 2 above)
Comment (Emmankoko) [reply compiler/src/dmd/expressionsem.d]: I really intended to mean `ship`. like export that. initially when I was exporting only the `varExp`, I was getting a forward reference error so it looked like after doing `int a = 5`, and exporting `a` only, when `AddrExp` is resolving it, it doesn't find the declaration of a. so I had to make them coupled together using the comma expression. 

so maybe if `ship` looks like a bad word, I can use `export` ??
