### PR TITLE
Fix : Improved error message on override mismatch

### LINKED ISSUE #20489: Improve error message on override mismatch
### Description

````markdown
When trying to override an inherited method, there are three kinds of error:
- No base class method with the given name exists.
- There are base class methods with that name, but all are final.
- There is at least one overridable base class method with that name, but the signature is incompatible.

In the first case, try typo correction.

In the second case, tell the user there are no non-final methods available. Also try typo correction.

In the third case, when signatures are incompatible, print both the signatures and point out the difference in a diff style manner. That is, in the derived class’s method that tries to override, use red for stuff to be removed and green for stuff that would have to be added.
If there is an overload in the base class that has exactly as many parameters as the would-be overload, only do the diff for the overloads with the right number of parameters; otherwise do the diff for all base class overloads with the right name.

Example case:
```
Error: function `pure nothrow @nogc @safe int app.D.f(int delegate(int) pure nothrow @nogc @safe body)` does not override any function, did you mean to override `pure nothrow @nogc @safe int app.B.f(scope int delegate(int) pure nothrow @nogc @safe)`?
```
Better:
```
Error: function `pure nothrow @nogc @safe int app.D.f(int delegate(int) pure nothrow @nogc @safe body)` does not override any function, did you mean to override `pure nothrow @nogc @safe int app.B.f(scope int delegate(int) pure nothrow @nogc @safe)`?
Did you intend to override like this:
pure nothrow @nogc @safe int f(scope int delegate(int) pure nothrow @nogc @safe)
                               ^^^^^ (addition)
```
````

### PR DESCRIPTION
**Pull request by abulgit**
Fix : https://github.com/dlang/dmd/issues/20489
The error message is better now.

### CODE REVIEW

File: compiler/src/dmd/funcsem.d [hunk 1]
```diff
@@ -983,6 +983,43 @@ void funcDeclarationSemantic(Scope* sc, FuncDeclaration funcdecl)
...
+                            {
+                                bool hasScopeDifference = false;
+
+                                for (size_t i = 0; i < params1.length; i++)
+                                {
+                                    auto p1 = params1[i];
+                                    auto p2 = params2[i];
+
+                                    // Check for scope difference
+                                    if ((p1.storageClass & STC.scope_) != (p2.storageClass & STC.scope_))
```
Comment (thewilsonator) [inline compiler/src/dmd/funcsem.d:1006]: since you are in a `for`loop you can convert this into 
```
if ((p1.storageClass & STC.scope_) == (p2.storageClass & STC.scope_))
    continue;
```
and reduce the nesting.

File: compiler/src/dmd/funcsem.d [hunk 2]
```diff
@@ -983,6 +983,43 @@ void funcDeclarationSemantic(Scope* sc, FuncDeclaration funcdecl)
...
+                                    {
+                                        if (p2.storageClass & STC.scope_)
```
Comment (thewilsonator) [inline compiler/src/dmd/funcsem.d:1008]: ditto

Comment (abulgit) [reply compiler/src/dmd/funcsem.d]: Yes, I reduced the Nesting.

**Review by thewilsonator — APPROVED** [review]
