### PR TITLE
Fix #19163 - ICE with delegate in UDA

### LINKED ISSUE #19163: ICE with delegate in UDA
### CC List

* Dennis
* Ketmar Dark

### Description

````markdown
the following code gives
Internal error: backend/cgcod.c 1666
in 2.071 and master:


struct NameAttribute {
  int delegate () foo;
}

static NameAttribute getNamedAttribute(alias S) () {
  NameAttribute res;
  foreach (attr; __traits(getAttributes, S)) {
    static if (is(typeof(attr) == NameAttribute)) res = attr;
  }
  return res;
}

struct MyStruct {
  @NameAttribute({ return 42; }) int a;
}

void PrintAll(T) (T arg) {
  foreach (m; __traits(allMembers, T)) {
    enum nameAttr = getNamedAttribute!(__traits(getMember, T, m));
  }
}

void main () {
  PrintAll(MyStruct());
}
````

### PR DESCRIPTION
**Pull request by vindexbit**
Related issue: #19163

`dmd` sometimes lowered a delegate literal in a UDA (retrieved via `__traits(getAttributes)`) as only a function pointer (one word) and then assigned it into a delegate slot (two words).

### CODE REVIEW

File: compiler/test/compilable/issue19163.d [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+{
+    return __traits(getAttributes, S)[0];
+}
+
+struct MyStruct
+{
+    @NameAttribute({ return 42; }) int a;
+}
+
+void main()
```
Comment (thewilsonator) [inline compiler/test/compilable/issue19163.d]: compilable tests shouldn't have their test function be called `main`

**Review by thewilsonator — APPROVED** [review]
otherwise looks good

File: compiler/test/compilable/issue19163.d [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+void test()
+{
+    TestStruct m;
+    enum nameAttr = getNamedAttribute!(m.a);
+}
+
+void main()
+{
+    test();
+}
```
Comment (thewilsonator) [inline compiler/test/compilable/issue19163.d]: remove the `main` function entirely

**Comment by vindexbit** [comment]
This command shows a suspiciously large number of fails:
`HOST_DMD=../../generated/linux/release/64/dmd ./run.d compilable`
```
...
FAILED targets:
- compilable/issue15574.sh
- compilable/test14894.sh
- compilable/issue19243.sh
- compilable/issue19724.sh
- compilable/test6461.sh
- compilable/issue24830.sh
```

**Review by thewilsonator — APPROVED** [review]
