### PR TITLE
Fix 22397 - Internal Error: array literal with UDA cause failure

### LINKED ISSUE #22397: DMD 2.112.0 fails to compile an array variable initialization with an array literal and a UDA
After upgrading DMD from v2.111.0 to v2.112.0 (on Debian 13.2, x86_64) I have found an issue, which I have isolated in the following code snippet:

```D
void main()
{
	enum var = true;
	@var string[] list = ["A", "B", "C"];
}
```
v2.111.0 compiles the code as expected but v2.112.0 halts with the following message:

> Internal Error: array literal ["A", "B", "C"] (...) should have been lowered to a _d_arrayliteralTX template

Removing the `var` UDA fixes the problem.

### PR DESCRIPTION
**Pull request by MadhurKumar004**
The backend expect dynamic array literals to be lowered to runtine calls by the frontend. when a variable declaration have a UDA, the lowering logic get bypassed or not get triggered, causing an assertion failure in 'e2ir.d'.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by dkorpel — CHANGES_REQUESTED** [review]
Lowering array literals is deliberately done in a GC pass instead of expression semantic to avoid lowering literals that are going to constant folded away. It needs to be investigated how UDAs affect this logic resulting in a missed lowering.

**Comment by dkorpel** [comment]
Note that the array lowering and `@nogc` share the same pass, revealing a related issue:

```D
void main() @nogc
{
       string[] b = ["A", "B", "C"]; // @nogc error, correct behavior
    @1 string[] a = ["A", "B", "C"]; // no error, incorrect behavior
}
```

**Comment by MadhurKumar004** [comment]
@dkorpel review please.

**Comment by dkorpel** [comment]
Please add the `@nogc` test case and make it pass:

```
FAILED targets:
- runnable\test22070_2.c
- compilable\test23342.i
- fail_compilation\test21247b.d
- fail_compilation\test21247.d
```

**Comment by MadhurKumar004** [comment]
@dkorpel i have added the @nogc test case. 
As for the other tests, they are independent of this commit.

**Comment by dkorpel** [comment]
The test failures are introduced by this PR's code changes

**Comment by MadhurKumar004** [comment]
@dkorpel  Apology for the mistake earlier.
i have fixed the issues you mentioned. Please review

**Review by dkorpel — APPROVED** [review]
Looks good, what did you change to fix the errors?

File: compiler/src/dmd/nogc.d [hunk 1]
```diff
@@ -76,14 +77,34 @@ public:
...
-                doCond(ei.exp);
+                if (!(v.storage_class & STC.manifest) && !v.isDataseg() && v._init && !v.isCsymbol())
+                {
+                    if (ExpInitializer ei = v._init.isExpInitializer())
+                    {
+                        doCond(ei.exp);
+                    }
+                }
+            }
+
```
Comment (dkorpel) [inline compiler/src/dmd/nogc.d]:
```suggestion

```

File: compiler/src/dmd/nogc.d [hunk 2]
```diff
@@ -76,14 +77,34 @@ public:
...
+                }
+            }
+            
+            else if (AttribDeclaration ad = d.isAttribDeclaration())
+            {
+                // Don't recurse into anonymous declarations (unions/structs)
+                // as their members aren't meant to be processed here
+                if (ad.isAnonDeclaration())
+                    return;
+
```
Comment (dkorpel) [inline compiler/src/dmd/nogc.d]:
```suggestion

```

**Review by dkorpel — COMMENTED** [review]
Remove trailing whitespaces

**Comment by MadhurKumar004** [comment]
I added `!v.isCsymbol()` to skip C symbols and `ad.isAnonDeclaration()` to skip the anonymous unions/struct members.
Also removed the trailing whitespaces

**Comment by dkorpel** [comment]
Thank you!
