### PR TITLE
fix for wrong location for incompatible argument error

### LINKED ISSUE #21167: Wrong location for incompatible argument error
```d
void f(int, int, int){}

void main()
{
	f(
		1,
		"foo",
		3
	);
	
}
```

Output:

```
test.d(5): Error: function `f` is not callable using argument types `(int, string, int)`
test.d(5):        cannot pass argument `"foo"` of type `string` to parameter `int __param_1`
test.d(1):        `test.f(int __param_0, int __param_1, int __param_2)` declared here
```

The error is reported on line 5 (the function being called), but it would be more useful to report it on line 7 (the argument which does not match).

### PR DESCRIPTION
**Pull request by Iskaban10**
fix #21167

### CODE REVIEW

File: compiler/src/dmd/templatesem.d [hunk 1]
```diff
@@ -5678,7 +5678,7 @@ void functionResolve(ref MatchAccumulator m, Dsymbol dstart, Loc loc, Scope* sc,
         MATCH mfa = callMatch(fd, tf, tthis_fd, argumentList, 0, errorHelper, sc);
         //printf("test1: mfa = %d\n", mfa);
         if (failMessage)
-            errorHelper(failMessage);
+            errorHelper(failMessage, Loc.initial);
```
Comment (thewilsonator) [inline compiler/src/dmd/templatesem.d]: `argloc`? otherwise why is this function's parameter list changed?

Comment (Iskaban10) [reply compiler/src/dmd/templatesem.d]: I was using an extra parameter to pass the error argument location. Else it is difficult to get the location of the error. This one seems to be a mistake in line 5681.

**Comment by CyberShadow** [comment]
Thanks, just wondering if you saw the prior work in https://github.com/dlang/dmd/pull/22370

**Comment by Iskaban10** [comment]
> Thanks, just wondering if you saw the prior work in #22370
Yes, I did see the previous PR that was made.

**Review by thewilsonator — APPROVED** [review]
