### PR TITLE
Fix hash collision in CSE

### LINKED ISSUE #20985: `runnable\exe1.c` heisenbugs on Win64
```
2025-03-13T11:26:51.8646407Z Assertion failed: j == 61440 && k == 3840, file runnable\exe1.c, line 1449
2025-03-13T11:26:51.8646872Z 
2025-03-13T11:26:51.8646878Z 
2025-03-13T11:26:51.8646883Z 
2025-03-13T11:26:51.8668823Z 
2025-03-13T11:26:51.8668857Z 
2025-03-13T11:26:51.8669090Z ==============================
2025-03-13T11:26:51.8669832Z Test 'runnable\exe1.c' failed: caught signal: -1073740791
```

1. <https://github.com/dlang/phobos/actions/runs/13833435713/job/38702803087> failed (on Windows x64 only).
2. I bumped the PR with an empty commit.
3. <https://github.com/dlang/phobos/actions/runs/13845655978/job/38743400562> passes.

GitHub says, `exe1.c` was last changed 5 days ago, so there’s no indication this has been fixed in the meantime.

#### CI logs

- [original-run.txt](https://github.com/user-attachments/files/19237720/original-run.txt)
- [bump-run.txt](https://github.com/user-attachments/files/19237719/bump-run.txt)

### PR DESCRIPTION
**Pull request by limepoutine**
In `cgcs.d`, assignment ops clobber CSE of a symbol, but weirdly do not clobber any larger common expressions referencing it. The checks to avoid false matches are a kludge. Instead, this PR now requires all leaf nodes to have already been merged by CSE before eliminating a larger expression. As a result, DMD's CSE is now immune to hash collision (in terms of correctness). This hopefully fixes #20985 (worked for a few hundred builds on my machine yet still unsure).

On the downside, DMD's optimization is slightly weaker again. I think maybe very few people will care.

### CODE REVIEW

**Comment by limepoutine** [comment]
#20985 is much easier to reproduce under low memory like today's Azure pipelines, which very well hints at hash collision as the root cause?

**Comment by rainers** [comment]
As mentioned in the bug report, the failures are reproducible with cs_comphash() always returning 0, i.e. always causing collisions. Have you tested your change with that?

**Comment by limepoutine** [comment]
This can pass the whole test suite with `hash_t cs_comphash(const elem* e) => 0;`. I have no idea how to write a test enforcing that however.

**Comment by rainers** [comment]
> On the downside, DMD's optimization is slightly weaker again. I think maybe very few people will care.

AFAIU only for expressions where the hashes happen to match, which is very unlikely and non-deterministic anyway.

> This can pass the whole test suite with `hash_t cs_comphash(const elem* e) => 0;`. 

Good to know.

> I have no idea how to write a test enforcing that however.

Probably not worth the trouble. Do we have a test that CSE elimination works at all?

**Review by rainers — APPROVED** [review]
Prepend the commit message with Fix #20985 to auto-close the issue and include it in the changelog.

**Comment by limepoutine** [comment]
> Do we have a test that CSE elimination works at all?

No, I stubbed out all CSE code and tests are still green.

File: compiler/src/dmd/backend/cgcs.d [hunk 1]
```diff
@@ -513,31 +513,40 @@ void ecom(ref CGCS cgcs, ref elem* pe)
...
-                    }
-                    ehash.Ecount++;
-                    pe = ehash;
-
-                    debug if (debugx)
-                        printf("**MATCH** %p with %p\n",e,pe);
-
-                    el_free(e);
-                    return;
+                    if (e.E1 != ehash.E1)
```
Comment (rainers) [inline compiler/src/dmd/backend/cgcs.d]: On second look: AFAICT the comment above "Make sure leaves are already merged as common subexpressions" means we should check Ecount on e.E1 and e.E2 to be non-zero. Is this no longer necessary and the comment can be removed? Or should the check be restored?

Comment (limepoutine) [reply compiler/src/dmd/backend/cgcs.d]: I grepped for `identifier.Belem=` and `ref elem*` and did not find a case before `comsubs` where an elem is referenced twice, so I just assumed all elem's must be unique prior to this pass. I think it is safer to restore the check as `comsubs` is only used by unoptimized builds.

Comment (limepoutine) [reply compiler/src/dmd/backend/cgcs.d]: Restored.
