### PR TITLE
Fix #21637 - ICE in tuple comparison with conditional expression

### LINKED ISSUE #21637: ICE in tuple comparison
This is the most reduced i can get it so far:

```d
import std.datetime.date;
import std.typecons;

struct Thing {
        Nullable!Date a;
}

void main() {
        enum CompareTo = Date(2000, 1, 1);
        auto thing = Thing(
                Date.fromISOString("20000101").tupleof == CompareTo.tupleof ? Nullable!Date() : Nullable!Date()
        );
}
```

Compile that with upstream dmd master, no flags required (i noticed it using `-preview=fieldwise` but that just rewrites the comparison to use tupleof, so doing that in the source gets the same result)

```
---
ERROR: This is a compiler bug.
Please report it via https://github.com/dlang/dmd/issues
with, preferably, a reduced, reproducible example and the information below.
DustMite (https://github.com/CyberShadow/DustMite/wiki) can help with the reduction.
---
DMD v2.106.0-rc.1-2160-gc397436871
predefs  DigitalMars LittleEndian D_Version2 all D_SIMD Posix ELFv1 linux CRuntime_Glibc CppRuntime_GNU CppRuntime_Gcc D_InlineAsm_X86_64 X86_64 D_LP64 D_PIC assert D_PreConditions D_PostConditions D_Invariants D_ModuleInfo D_Exceptions D_TypeInfo D_HardFloat
binary    /home/me/d/pull-request-stuff/dmd/generated/linux/release/64/dmd
version   v2.106.0-rc.1-2160-gc397436871
config    /home/me/d/pull-request-stuff/dmd/generated/linux/release/64/dmd.conf
DFLAGS    -I/home/me/d/pull-request-stuff/dmd/generated/linux/release/64/../../../../druntime/import -I/home/me/d/pull-request-stuff/dmd/generated/linux/release/64/../../../../../phobos -L-L/home/me/d/pull-request-stuff/dmd/generated/linux/release/64/../../../../../phobos/generated/linux/release/64 -L--export-dynamic -fPIC
---
core.exception.AssertError@src/dmd/backend/dtype.d(304): Assertion failure
----------------
??:? _d_assertp [0xa03dd0]
src/dmd/backend/dtype.d:304 nothrow @nogc @safe dmd.backend.type.TYPE* dmd.backend.dtype.type_fake(uint) [0x918f0b]
src/dmd/backend/elem.d:617 nothrow @trusted dmd.backend.el.elem* dmd.backend.elem.exp2_copytotemp(dmd.backend.el.elem*) [0x91d7c2]
src/dmd/backend/cgelem.d:3675 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.elstruct(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x90d1cb]
src/dmd/backend/cgelem.d:6209 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.optelem(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x912f28]
src/dmd/backend/cgelem.d:5752 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.optelem(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x911f09]
src/dmd/backend/cgelem.d:3524 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.elstruct(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x90cd4b]
src/dmd/backend/cgelem.d:6209 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.optelem(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x912f28]
src/dmd/backend/cgelem.d:5749 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.optelem(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x911ee6]
src/dmd/backend/cgelem.d:5749 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.optelem(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x911ee6]
src/dmd/backend/cgelem.d:6239 nothrow @trusted dmd.backend.el.elem* dmd.backend.cgelem.doptelem(dmd.backend.el.elem*, dmd.backend.cc.Goal) [0x912f6c]
src/dmd/backend/blockopt.d:461 nothrow @trusted void dmd.backend.blockopt.blockopt(ref dmd.backend.goh.GlobalOptimizer, int) [0x91557c]
src/dmd/backend/dout.d:1010 nothrow @trusted void dmd.backend.dout.writefunc2(dmd.backend.cc.Symbol*, ref dmd.backend.goh.GlobalOptimizer) [0x8f88b6]
src/dmd/backend/dout.d:855 nothrow @trusted void dmd.backend.dout.writefunc(dmd.backend.cc.Symbol*) [0x8f8274]
src/dmd/glue.d:971 void dmd.glue.FuncDeclaration_toObjFile(dmd.func.FuncDeclaration, bool) [0x890c73]
src/dmd/toobj.d:190 _ZN9toObjFile9ToObjFile5visitEP15FuncDeclaration [0x8ab9d1]
src/dmd/func.d:1050 _ZN15FuncDeclaration6acceptEP7Visitor [0x7866c1]
src/dmd/toobj.d:905 void dmd.toobj.toObjFile(dmd.dsymbol.Dsymbol, bool) [0x8ab938]
src/dmd/glue.d:1420 void dmd.glue.genObjFile(dmd.dmodule.Module, bool, bool) [0x89295b]
src/dmd/glue.d:339 void dmd.glue.generateCodeAndWrite(dmd.dmodule.Module[], const(char)*[], const(char)[], const(char)[], bool, bool, bool, bool, bool) [0x88eeca]
src/dmd/main.d:768 int dmd.main.tryMain(ulong, const(char)**, out dmd.globals.Param) [0x680c6c]
```

All kinds of things will remove the error: adding an explicit ctor to the `Thing` struct removes it, for example. Comparing against an `auto` instead of `enum` does it. Not using Nullable removes it. Changing a branch to `assert(0)` removes it. So it is quite finicky, but this reduction is a lot smaller than the original 3k line program lol

### PR DESCRIPTION
**Pull request by dkorpel**
Closes #21637

The prompt for this was `Fix https://github.com/dlang/dmd/issues/21637`

> In `elcond`, when restructuring `((a,b) ? c : d)` into `(a, (b ? c : d))`, `Ety` was copied to the new inner OPcond but `ET` was not. This left the OPcond with TYstruct Ety but null ET, causing `elstruct` to return early and `exp2_copytotemp` to crash with `assert(ty != TYstruct)`.

### CODE REVIEW

File: compiler/src/dmd/backend/cgelem.d [hunk 1]
```diff
@@ -2139,6 +2139,7 @@ private elem* elcond(elem* e, Goal goal)
             e.E2 = e1;
             e1.Eoper = OPcond;
             e1.Ety = e.Ety;
+            e1.ET = e.ET;
```
Comment (dkorpel) [inline compiler/src/dmd/backend/cgelem.d:2142]: For reference, `Ety` is the tag like `TYint` or `TYstruct` and `ET` is a `type*` with info about struct members. Hence the ICE happening when a struct type from a comma expression was used in a ternary operator.

**Review by thewilsonator — APPROVED** [review]
