### PR TITLE
Fix error location for binary operations to point at operator instead of first operand

### LINKED ISSUE #21166: Wrong location for invalid binary operation error
```d
auto r =
	"foo"
	+
	"bar";
```

Output:
```
test.d(2): Error: invalid array operation `"foo" + "bar"` (possible missing [])
test.d(2):        did you mean to concatenate (`"foo" ~ "bar"`) instead ?
```

The error is reported on line 2 (the first operand), but it really should be reported on line 3 (the infix binary operator).

### PR DESCRIPTION
**Pull request by abulgit**
Closes: https://github.com/dlang/dmd/issues/21166

The issue was that in the binary expression parsing functions (`parseAddExp()`, `parseMulExp()`, etc.), the location was being captured at the beginning of the function, which corresponds to the first operand's location.
I modified all of these functions to capture the location just before processing each operator, ensuring that error messages are reported at the correct location. I applied this consistently across all binary expression parsing functions.
Added Testcases - `fail_compilation/fix21166.d`, also Fixed some Existing Tests.

### CODE REVIEW

File: compiler/src/dmd/parse.d [hunk 1]
```diff
@@ -9068,26 +9068,28 @@ class Parser(AST, Lexer = dmd.lexer.Lexer) : Lexer
...
     {
-        const loc = token.loc;
         auto e = parseUnaryExp();
 
         while (1)
         {
             switch (token.value)
             {
             case TOK.mul:
+                const loc = token.loc;
```
Comment (thewilsonator) [inline compiler/src/dmd/parse.d:9078]: instead of this, just declare it once, after the call to `parseUnaryExp` 
```diff
-const loc = token.loc;
auto e = parseUnaryExp();
+const loc = token.loc;
```

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Ditto throughout as applicable (e.g if you have moved it  past a `check[Required]Parens` call or into a while loop, then I assume it needs to be there).

Otherwise looks good.

File: compiler/src/dmd/parse.d [hunk 2]
```diff
@@ -9203,12 +9209,14 @@ class Parser(AST, Lexer = dmd.lexer.Lexer) : Lexer
             }
             if (tv != TOK.is_)
                 break;
+            const loc = token.loc;
```
Comment (thewilsonator) [inline compiler/src/dmd/parse.d:9212]: style complains with 
```
dmd/parse.d(9212:19)[warn]: Variable loc is never used.
```

File: compiler/src/dmd/parse.d (hunk 1 above)
Comment (abulgit) [reply compiler/src/dmd/parse.d]: Yeah, that approach is more efficient and cleaner. Thanks!

**Review by thewilsonator — APPROVED** [review]
