### PR TITLE
[stable] Fix #21359 - Merge more types in `substWildTo()`

### LINKED ISSUE #21359: [REG2.111] `-allinst` can cause corrupt `TypeInfo_AssociativeArray` symbols
`bla.d`:
```D
void registerAll() {
    import carbon; // must be nested apparently
}
```

`carbon.d`:
```D
struct SumType(Types...)
{
    static foreach (T; Types)
        T values_;
}

SumType!(string[int]) convertObserver;

void hackAroundLinkerError() {
    auto t = typeid(const(immutable(char)[][])); // NOTE: replacing `immutable(char)[]` with `string` makes a difference!
}
```

Now the fun part, using DMD v2.111.0 - checking the TypeInfo for `string[int]` (mangled as `_D14TypeInfo_HiAya6__initZ`). Without `-allinst`:
```
$ dmd -c bla.d
$ nm bla.o | grep _D14TypeInfo_HiAya6__initZ
# => okay, no symbols as expected - we compile a function with a nested import, no actual body
```

Now with `-allinst`:
```
$ dmd -c bla.d -allinst
$ nm bla.o | grep _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
# => oh wow, 3 definitions for the same symbol in the same object file?!
$ objdump -r -s --section=.data._D14TypeInfo_HiAya6__initZ bla.o
RELOCATION RECORDS FOR [.data._D14TypeInfo_HiAya6__initZ]:
OFFSET           TYPE              VALUE
0000000000000000 R_X86_64_64       _D25TypeInfo_AssociativeArray6__vtblZ
0000000000000000 R_X86_64_64       _D25TypeInfo_AssociativeArray6__vtblZ
0000000000000000 R_X86_64_64       _D25TypeInfo_AssociativeArray6__vtblZ
0000000000000008 R_X86_64_64       _D12TypeInfo_Aya6__initZ
0000000000000008 R_X86_64_64       _D12TypeInfo_Aya6__initZ
0000000000000010 R_X86_64_64       _D12TypeInfo_Aya6__initZ
0000000000000010 R_X86_64_64       _D10TypeInfo_i6__initZ
0000000000000010 R_X86_64_64       _D10TypeInfo_i6__initZ
0000000000000018 R_X86_64_64       _D62TypeInfo_S6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn6__initZ
0000000000000018 R_X86_64_64       _D62TypeInfo_S6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn6__initZ
0000000000000018 R_X86_64_64       _D10TypeInfo_i6__initZ
0000000000000020 R_X86_64_64       _D62TypeInfo_S6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn6__initZ
# => oh wow, something is obviously extremely wrong!
```

Comparing with v2.110 (where the symbol is mangled as `_D15TypeInfo_HixAya6__initZ`?):
```
$ nm -U bla.o.allinst.110 | grep TypeInfo
0000000000000000 V _D13TypeInfo_xAya6__initZ
0000000000000000 V _D15TypeInfo_HixAya6__initZ
0000000000000000 V _D15TypeInfo_xHiAya6__initZ
$ nm -U bla.o.allinst.111 | grep TypeInfo
0000000000000000 V _D11TypeInfo_xi6__initZ
0000000000000000 V _D13TypeInfo_xAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D62TypeInfo_S6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn6__initZ
0000000000000000 W _D6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn11__xopEqualsMxFKxSQCtQCp__TQBrTiTQBoZQCbZb
0000000000000000 W _D6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn9__xtoHashFNbNeKxSQCsQCo__TQBqTiTQBnZQCaZm
```

Compiling `carbon.d` with the actual code on the other hand works fine, and `-allinst` doesn't affect the emitted TypeInfo symbols AFAICT. For reference:
```
$ nm -U carbon.o.110 | grep TypeInfo
0000000000000000 V _D13TypeInfo_xAya6__initZ
0000000000000000 V _D14TypeInfo_AxAya6__initZ
0000000000000000 V _D14TypeInfo_xAAya6__initZ
0000000000000000 V _D15TypeInfo_HixAya6__initZ
0000000000000000 V _D15TypeInfo_xHiAya6__initZ
0000000000000000 V _D37TypeInfo_S6carbon__T7SumTypeTHiAyaZQp6__initZ
$ nm -U carbon.o.111 | grep TypeInfo
0000000000000000 V _D11TypeInfo_xi6__initZ
0000000000000000 V _D13TypeInfo_xAya6__initZ
0000000000000000 V _D14TypeInfo_AxAya6__initZ
0000000000000000 V _D14TypeInfo_HiAya6__initZ
0000000000000000 V _D14TypeInfo_xAAya6__initZ
0000000000000000 V _D37TypeInfo_S6carbon__T7SumTypeTHiAyaZQp6__initZ
0000000000000000 V _D62TypeInfo_S6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn6__initZ
0000000000000000 W _D6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn11__xopEqualsMxFKxSQCtQCp__TQBrTiTQBoZQCbZb
0000000000000000 W _D6object25TypeInfo_AssociativeArray__T5EntryTiTAyaZQn9__xtoHashFNbNeKxSQCsQCo__TQBqTiTQBnZQCaZm
```

---

For a Symmetry code base, this regression means we get a segfault immediately at program startup, when generating an AA literal: https://github.com/symmetryinvestments/dmd-umbrella/pull/6#issuecomment-2835567931

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

File: compiler/test/compilable/test21359.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
+#!/usr/bin/env bash
+
+objfile="${OUTPUT_BASE}${OBJ}"
+$DMD -c -m${MODEL} -allinst -of${objfile} ${EXTRA_FILES}/${TEST_NAME}a.d -I${EXTRA_FILES}
+
+# This test is brittle and might break in the future.
```
Comment (rainers) [inline compiler/test/compilable/test21359.sh:6]: How about checking for duplicate symbols in general:
```
! nm -j bla.o | uniq -d | read
```
worked for the test case.

Comment (rainers) [reply compiler/test/compilable/test21359.sh:6]: > I wanted to check that the symbol we are looking for is emitted once at least.

Ok.

> Of course other fail_compilation tests now fail, with uglier 'forward reference' errors coming from the glue layer now, without a Loc. :(

These are messages from the glue layer. I guess you can avoid them if the nextOf().merge().deco check is only added for case Taarray.

Comment (rainers) [reply compiler/test/compilable/test21359.sh:6]: > but that special case is obviously ugly...

I think it would be ok if implemented as a `cast Tfunction` instead of extra checks in the generic case.

File: compiler/src/dmd/typesem.d [hunk 2]
```diff
@@ -3316,8 +3316,14 @@ Type merge(Type type)
             goto default;
 
         default:
-            if (type.nextOf() && !type.nextOf().deco)
-                return type;
+            if (auto next = type.nextOf())
+            {
+                // don't try to merge TypeFunctions (can shift forward-reference errors from the frontend to the glue layer, without Loc)
```
Comment (rainers) [inline compiler/src/dmd/typesem.d:3321]: >  don't try to merge TypeFunctions

seems a bit misleading, maybe add "with incomplete return type"

File: compiler/test/compilable/test21359.sh (hunk 1 above)
Comment (kinke) [reply compiler/test/compilable/test21359.sh:6]: I guess it could be beneficial to move the `if (type.deco) return type;` before the `switch` though - the switch seems to be exclusively reserved for skipping the merge and returning `type` as-is.

Comment (rainers) [reply compiler/test/compilable/test21359.sh:6]: Ah, sorry, missed that.

Then my suggestion to only change the AA case could be an option:
```D
        case Taarray:
            if (!type.isTypeAArray().index.merge().deco)
                return type;
            if (!type.nextOf().merge().deco)
                return type;
            break;
```
as I see deco being used in a lot of places to check for resolved semantic. More regressions looming...

The bad types come from `makeNakedAssociativeArray`. `substWildTo` doesn't return a merged type in some cases. Adding `.merge()` in `makeNakedAssociativeArray` helps bla.d, but probably fixing it in `substWildTo` is better:

https://github.com/dlang/dmd/blob/8d90d93c00f3bca8589b84c750ac85b2d87ad1a5/compiler/src/dmd/typesem.d#L7349
shoud return `t.merge()`.

Comment (kinke) [reply compiler/test/compilable/test21359.sh:6]: Thx for digging further!

> but probably fixing it in `substWildTo` is better

Yeah I guess there we also don't need a special case for TypeFunctions (no qualified TypeFunctions I hope, only qualified function pointers/delegates). After a superficial glance, those seem to be an ugly special case, e.g., there are 3 occurrences of this comment in that file: https://github.com/dlang/dmd/blob/8d90d93c00f3bca8589b84c750ac85b2d87ad1a5/compiler/src/dmd/typesem.d#L2748-L2753

**Review by rainers — APPROVED** [review]
Indeed, the special cases around deco make changes rather brittle. I guess this change is the one with the least unexpected side effects while making substWildTo more consistent.
