### PR TITLE
fix #22153 cannot use forward declaration of static function when building a library

### LINKED ISSUE #22153: importc: cannot use forward declaration of static function when building a library
While trying to build phobos as a library with a single call, dmd errors out with
```
error : no definition found for static `deflate_stored` in this module, statics defined in one module cannot be referenced from another
```

This boils down to compiling this C code with `-lib`:
```C
static void static_fun();

void lib_fun()
{
	static_fun();
}

static void static_fun()
{
}
```
yields:
```
Error: no definition found for static `static_fun` in this module, statics defined in one module cannot be referenced from another
```

Also note the missing file and line number.

### PR DESCRIPTION
**Pull request by Emmankoko**
in importC, when building a static library with `-lib`, forward declarations do not get their function refs resolved even if implemented in the same module. the backend however still sticks to using the non-body declaration and hence stops importC from being able to build static libraries. transferring the function def to the top declaration as a replacement method fixes it.

@dkorpel @thewilsonator 

closes #22153 #20152

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/importc.d [hunk 1]
```diff
@@ -575,16 +575,50 @@ Dsymbol handleSymbolRedeclarations(ref Scope sc, Dsymbol s, Dsymbol s2, ScopeDsy
...
+            }
+
             fd.overnext = fd2;
 
             /* If fd2 is covering a tag symbol, then fd has to cover the same one
              */
             auto ps = cast(void*)fd2 in sc._module.tagSymTab;
             if (ps)
-                sc._module.tagSymTab[cast(void*)fd] = *ps;
+                sc._module.tagSymTab[cast(void*)fd2] = *ps;
```
Comment (rainers) [inline compiler/src/dmd/importc.d:619]: This looks like a no-op to me now.

Comment (Emmankoko) [reply compiler/src/dmd/importc.d:619]: oh right. we are handling with the new decls in focus. I should revert it back to `fd`.
