### PR TITLE
fix #18101 wrong code generated for bitfield assignment to ?:

### LINKED ISSUE #18101: wrong code generated for bitfield assignment to ?:
### CC List

* basile-z

### Description

````markdown
The generated code is as if a.x and a.y were regular fields instead of bitfields.

struct A { int x: 3; int y: 5; } a;

struct A test(int val, int choice, struct A a)
{
    (choice ? a.x : a.y) = val;
    return a;
}

Affects D and ImportC.
````

### PR DESCRIPTION
**Pull request by WalterBright**
It issues an error now.

Blocking https://github.com/dlang/dmd/pull/21625

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -16180,7 +16180,9 @@ private Expression toLvalueImpl(Expression _this, Scope* sc, const(char)* action
         // convert (econd ? e1 : e2) to *(econd ? &e1 : &e2)
         CondExp e = cast(CondExp)(_this.copy());
         e.e1 = _this.e1.toLvalue(sc, action).addressOf();
+        checkAddressable(e.e1, sc);
         e.e2 = _this.e2.toLvalue(sc, action).addressOf();
+        checkAddressable(e.e2, sc);
```
Comment (ibuclaw) [inline compiler/src/dmd/expressionsem.d:16185]: I suspect this is just painting lipstick on the pig. Iif it's not addressable, then it should fail the `toLvalue` conversion done before this check.

Comment (WalterBright) [reply compiler/src/dmd/expressionsem.d:16185]: The difficulty is `(c ? a.x : a.y) = 3;` is an lvalue, while taking the address of it is not. So it's going to be a kludge somewhere.

Comment (ibuclaw) [reply compiler/src/dmd/expressionsem.d:16185]: Well, conditional expressions are not lvalues in C (6.5.15 [note 110] A conditional expression does not yield an lvalue).

As for lvalue conditional expressions in D, I think we should fix the rewrite to not use `*(c ? &a : &b)`

Depending on whether `val` has a side effect, either
```d
(c ? a = val : b = val);
// or
auto tmp = val(), (c ? a = tmp : b = tmp);
```

Comment (ibuclaw) [reply compiler/src/dmd/expressionsem.d:16185]: The more I stare, the more I think `checkAddressable` and `toLvalue` just do the same thing.  I'll have a look into possibly merging them later.

Comment (ibuclaw) [reply compiler/src/dmd/expressionsem.d:16185]: Anyway, I'm getting distracted. #21678.
