### PR TITLE
[internal/traits] Fix regression in `hasElaborateDestructor`

### LINKED ISSUE #10950: Possible regression in `hasElaborateDestructor` detection since DMD 2.111.0
I've found what seems to be a regression related to the `hasElaborateDestructor` trait.
When compiling and running the following code with **DMD 2.110.0**, I get this output:

```
~C(0)
a.b.len=1
b.c.len=0
exit
~B(): c.len=0
~A(): b.len=1
~B(): c.len=1
~C(1)
```

However, when compiled with **DMD 2.111.0**, I get:

```
No destructor found for B
No destructor found for C

~C(1)
a.b.len=1
b.c.len=0
exit
~B(): c.len=0
~A(): b.len=1
```

So it seems that in 2.111.0 the compiler incorrectly determines that `B` and `C` have no destructors, even though they clearly do.

Here’s the minimal reproducible example:

```D
import core.lifetime : moveEmplace;
import core.stdc.stdio : printf;
import core.stdc.stdlib : malloc, realloc, free;

import std.algorithm : max;
import std.traits : hasElaborateDestructor, isImplicitlyConvertible;

void main()
{
    A a;
    B b;
    b.c ~= C(1);
    a.b ~= b;

    printf("a.b.len=%ld\n", a.b.len);
    printf("b.c.len=%ld\n", b.c.len);
    printf("exit\n");
}

struct Array(T, size_t step = 64)
{
    @disable this(this);
    this(size_t cap) @trusted nothrow @nogc {
        buf = (cast(T*)malloc(T.sizeof * cap))[0..cap];
    }

    ~this() nothrow @nogc {
        if (buf) {
            static if (hasElaborateDestructor!T) {
                foreach (ref item; buf[0..len]) destroy(item);
            }
            else pragma(msg, "No destructor found for ", T);
            free(buf.ptr);
        }
    }

    void reserve(size_t elements) @trusted nothrow @nogc {
        if (buf.length - len >= elements) return;
        const newLen = buf.length + max(elements, step);
        if (!buf)
            buf = (cast(T*)malloc(T.sizeof * newLen))[0..newLen];
        else
            buf = (cast(T*)realloc(buf.ptr, T.sizeof * newLen))[0..newLen];
    }

    void put(U)(auto ref scope U item) @trusted
        if (isImplicitlyConvertible!(U, T))
    {
        reserve(1);
        () @trusted { item.moveEmplace(buf[len++]); }();
    }

    alias opOpAssign(string op : "~") = put;

private:
    T[] buf;
    size_t len;
}

struct A {
    Array!B b;
    ~this() nothrow @nogc {
        printf("~A(): b.len=%ld\n", b.len);
    }
}

struct B {
    Array!C c;
    ~this() nothrow @nogc {
        printf("~B(): c.len=%ld\n", c.len);
    }
}

struct C {
    int foo;
    ~this() nothrow @nogc {
        printf("~C(%d)\n", foo);
    }
}
```

**Expected behavior:**
`hasElaborateDestructor!B` and `hasElaborateDestructor!C` should return `true` (as in 2.110.0), since both types define destructors.

**Actual behavior:**
Starting with 2.111.0, both are incorrectly reported as having no destructors.

### PR DESCRIPTION
**Pull request by ntrel**
Fixes https://github.com/dlang/phobos/issues/10950.

I had to use `version (CoreUnittest)` to test the fix because it is dependent on the order of declarations. So it can't use a `unitest {}`.

### CODE REVIEW

File: druntime/src/core/internal/traits.d [hunk 1]
```diff
@@ -365,6 +350,29 @@ private bool hasDtor(string[] members)
     static assert(!hasElaborateDestructor!S6);
 }
 
+// https://github.com/dlang/dmd/issues/21967
+version (unittest)
```
Comment (jmdavis) [inline druntime/src/core/internal/traits.d]: 1. Never use `version(unittest)` in either druntime or Phobos. It tends to cause problems when third party code uses `version(unittest)`. For druntime, the correct thing to use is `version(CoreUnittest)`.

2. The test that I would suggest is something like
```
version(CoreUnittest)
{
    static assert(hasElaborateDestructor!Issue22524);
    enum issue22524Before = hasElaborateDestructor!Issue22524;
    static assert(issue22524Before);

    struct Issue22524
    {
        ~this() {}
    }

    static assert(hasElaborateDestructor!Issue22524);
    enum issue22524After = hasElaborateDestructor!Issue22524;
    static assert(issue22524After);
}
```

File: druntime/src/core/internal/traits.d [hunk 2]
```diff
@@ -294,30 +294,14 @@ template hasElaborateDestructor(S)
     }
     else static if (is(S == struct))
     {
-        // Once https://issues.dlang.org/show_bug.cgi?id=24865 is fixed, then
-        // this should be the implementation, but until that's fixed, we need the
-        // uncommented code.
-        // enum hasElaborateDestructor = __traits(hasMember, S, "__xdtor");
-
-        enum hasElaborateDestructor = hasDtor([__traits(allMembers, S)]);
+        enum hasElaborateDestructor = __traits(compiles, (S s) => (cast() s).__xdtor);
```
Comment (jmdavis) [inline druntime/src/core/internal/traits.d]: This is certainly a more clever fix than I was thinking of doing. Of course, it really should be the solution with `hasMember`, but the compiler seems incapable of dealing with `__xdtor` properly with either `hasMember` or `allMembers` at the moment. :|

**Review by jmdavis — APPROVED** [review]

**Comment by jmdavis** [comment]
It looks like the failures are unrelated, though there are enough of them that it's possible that one of them is related, since I didn't dig through all of them.

**Comment by ntrel** [comment]
dmd's `runnable/b6400.d` test is failing, I have no idea why.

File: druntime/src/core/internal/traits.d (hunk 2 above)
Comment (limepoutine) [reply druntime/src/core/internal/traits.d]: This has the side effect of instantiating `opDispatch` speculatively, which is likely why b6400 fails...

Comment (ntrel) [reply druntime/src/core/internal/traits.d]: That was the problem, thanks!

**Review by thewilsonator — APPROVED** [review]

**Comment by tim-dlang** [comment]
It looks like this caused a different regression: https://github.com/dlang/dmd/issues/22609

**Comment by kinke** [comment]
It might be cleaner to add a new builtin trait for this - we already have `isPOD`, `has{Copy,Move}Constructor` and `hasPostblit`; a `hasElaborateDestructor` [**edit**: or just `needsDestruction` or so; **edit2**: hmm no, that might be misleading for class types] would fit right in there, and, if needed, could (try to) do eager sema (the `__xdtor` alias is the `AggregateDeclaration.dtor` field in the AST), as apparently already done for the `isCopyable` trait (note the `dsymbolSemantic()` for struct types): https://github.com/dlang/dmd/blob/03bf6f0f3995b935e6ae5f43c8413bd09b3fce53/compiler/src/dmd/traits.d#L577-L599
