### PR TITLE
Fix #21304 : Redundant "cannot use array to initialize _error_" message when initializing invalid array

### LINKED ISSUE #21304: Redundant "cannot use array to initialize `_error_`" message when initializing invalid array
```d
int[unknown] values = [1, 2, 3];
```

Compiler output:

```
test.d(1): Error: undefined identifier `unknown`
test.d(1): Error: cannot use array to initialize `_error_`
```

The second error is redundant, and I don't think users should ever see `_error_` anyway.

### PR DESCRIPTION
**Pull request by Ay1nDas**
Fixes #21304 
### File Changes
Added a case `Terror`. To check if t is `_error_`

### Output
- #### Current Output:
<pre>test.d(1): Error: undefined identifier `unknown` 
test.d(1): Error: cannot use array to initialize `_error_` </pre>

- ### Updated Output:
<pre>test.d(1): Error: undefined identifier `unknown`</pre>

### CODE REVIEW

File: compiler/src/dmd/initsem.d [hunk 1]
```diff
@@ -241,7 +241,8 @@ Initializer initializerSemantic(Initializer init, Scope* sc, ref Type tx, NeedIn
             break;
 
         default:
-            error(i.loc, "cannot use array to initialize `%s`", t.toChars());
+            if(t.toChars() != `_error_`)
```
Comment (thewilsonator) [inline compiler/src/dmd/initsem.d:244]: use 
```d
case Terror:
    return err();
default:
    error(i.loc, "cannot use array to initialize `%s`", t.toChars());
```

Comment (Ay1nDas) [reply compiler/src/dmd/initsem.d:244]: I did that 1st, but the BuildKite failed https://buildkite.com/dlang/dmd/builds/41178.
So, I was trying with if.

Comment (Ay1nDas) [reply compiler/src/dmd/initsem.d:244]: https://github.com/dlang/dmd/pull/21309/commits/ff2efe9cfa9400889daa229606eafab578e3f578

**Review by thewilsonator — APPROVED** [review]
