### PR TITLE
Fix #20075 - Improve error message for immutable constructor type mismatch

### LINKED ISSUE #20075: "none of the overloads of `__ctor` are callable using a `immutable` object" error message is backwards
### CC List

* Nick Treleaven (@ntrel)

### Description

````markdown
The error message for this code is misleading:

```
immutable(Foo) getFoo(int* a) {
	return immutable Foo(a);
}

struct Foo {
	@disable this();
	immutable this(immutable int* a) {}
}
```

The error is:


```
a.d(2): Error: none of the overloads of `__ctor` are callable using a `immutable` object
a.d(7):        Candidate is: `a.Foo.this(immutable(int*) a)`
```

The error message gets the situation backwards. It implies:

* That there are no overloads taking an immutable object. Actually, there is only one overload and it takes an immutable object.
* That it was called using an immutable object: Actually, a mutable object was used.

The real problem is providing a mutable object where an immutable one is expected, but the error message implies that it's the other way around.

An ideal error message would be something like: "`a` is an `int*`, but an `immutable int*` was expected."

The error message is the same if I provide `string a` as an argument. In that case I don't think it should be talking about qualifiers like `immutable` at all since there is a more obvious type error,

Also, this resurfaces a previous issue that the name `__ctor` is appearing in error messsages. https://issues.dlang.org/show_bug.cgi?id=14997 was marked fixed already.
````

### PR DESCRIPTION
**Pull request by abulgit**
Fix : https://github.com/dlang/dmd/issues/20075

The original error message incorrectly implied that:
    There were no overloads taking an immutable object, when there actually was one
     A mutable object was used, when the real issue was providing a mutable argument to an immutable constructor

The fix:
1. Changes the error message to clearly state the attempted operation: constructing an immutable object
2. Shows what argument type was provided vs what was expected
3. Makes the error message more actionable by showing the exact type mismatch
I added the testcase in compiler/test/fail_compilation/fix20075.d
I think now it is more clear error msg.

### CODE REVIEW

File: compiler/src/dmd/funcsem.d [hunk 1]
```diff
@@ -1713,8 +1713,14 @@ FuncDeclaration resolveFuncCall(Loc loc, Scope* sc, Dsymbol s,
...
             buf.argExpTypesToCBuffer(fargs);
             if (fd.isCtorDeclaration())
-                .error(loc, "none of the overloads of `%s` can construct a %sobject with argument types `(%s)`",
-                    fd.toChars(), thisBuf.peekChars(), buf.peekChars());
+            {
+                if (tthis.mod & MODFlags.immutable_)
+                    .error(loc, "none of the overloads of `%s` can construct an immutable object with argument types `(%s)`. Expected `immutable(%s)`",
+                        fd.toChars(), buf.peekChars(), buf.peekChars());
+                else
+                    .error(loc, "none of the overloads of `%s` can construct a %sobject with argument types `(%s)`",
```
Comment (rikkimax) [inline compiler/src/dmd/funcsem.d:1721]: ``%sobject``

That doesn't look right, and seems to be missing a test.

Comment (abulgit) [reply compiler/src/dmd/funcsem.d:1721]: The test case was successful in my machine.

Comment (rikkimax) [reply compiler/src/dmd/funcsem.d:1721]: You have the true case in the test suite, but not the false, ideally both should be in it.

Comment (abulgit) [reply compiler/src/dmd/funcsem.d:1721]: Got it.

Comment (abulgit) [reply compiler/src/dmd/funcsem.d:1721]: Got it.

Comment (abulgit) [reply compiler/src/dmd/funcsem.d:1721]: Hey, @rikkimax. I am trying to fix it with a different approach, but it fails some other existing fail_compilation tests every time. for example all of these
- fail_compilation\const_ctor.d
- fail_compilation\b3841.d
- fail_compilation\ctor_attr.d
- fail_compilation\diag10327.d
- fail_compilation\fail18938.d
- fail_compilation\fail21091a.d
- fail_compilation\fail21091b.d
- fail_compilation\fail217.d
- fail_compilation\fail22366.d
- fail_compilation\ice7782.d
- fail_compilation\immutable_ctor.d
- fail_compilation\needspkgmod.d
- fail_compilation\issue11070.d
- fail_compilation\operator_undefined.d
- fail_compilation\test22361.d
- fail_compilation/testrvaluecpctor.d

what should I do now?

Comment (rikkimax) [reply compiler/src/dmd/funcsem.d:1721]: From the two CI runs I have looked at only one of those expected to fail tests isn't doing what it should.

```
Test 'fail_compilation\testrvaluecpctor.d' failed: 
expected:
----
fail_compilation\testrvaluecpctor.d(16): Error: cannot define both an rvalue constructor and a copy constructor for `struct Foo`
fail_compilation\testrvaluecpctor.d(24):        Template instance `testrvaluecpctor.Foo!int.Foo.__ctor!(immutable(Foo!int), immutable(Foo!int))` creates an rvalue constructor for `struct Foo`
fail_compilation\testrvaluecpctor.d(24): Error: none of the overloads of `this` can construct a `immutable` object with argument types `(immutable(Foo!int))`
fail_compilation\testrvaluecpctor.d(18):        Candidates are: `testrvaluecpctor.Foo!int.Foo.this(ref scope Foo!int rhs)`
fail_compilation\testrvaluecpctor.d(16):                        `this(Rhs, this This)(scope Rhs rhs)`
fail_compilation\testrvaluecpctor.d(40): Error: cannot define both an rvalue constructor and a copy constructor for `struct Test`
fail_compilation\testrvaluecpctor.d(46):        Template instance `testrvaluecpctor.Test.__ctor!()` creates an rvalue constructor for `struct Test`
----
actual:
----
fail_compilation\testrvaluecpctor.d(16): Error: cannot define both an rvalue constructor and a copy constructor for `struct Foo`
fail_compilation\testrvaluecpctor.d(24):        Template instance `testrvaluecpctor.Foo!int.Foo.__ctor!(immutable(Foo!int), immutable(Foo!int))` creates an rvalue constructor for `struct Foo`
fail_compilation\testrvaluecpctor.d(24): Error: none of the overloads of `this` can construct an immutable object with argument types `(immutable(Foo!int))`. Expected `immutable(immutable(Foo!int))`
fail_compilation\testrvaluecpctor.d(18):        Candidates are: `testrvaluecpctor.Foo!int.Foo.this(ref scope Foo!int rhs)`
fail_compilation\testrvaluecpctor.d(16):                        `this(Rhs, this This)(scope Rhs rhs)`
fail_compilation\testrvaluecpctor.d(40): Error: cannot define both an rvalue constructor and a copy constructor for `struct Test`
fail_compilation\testrvaluecpctor.d(46):        Template instance `testrvaluecpctor.Test.__ctor!()` creates an rvalue constructor for `struct Test`
----
diff:
----
 fail_compilation\testrvaluecpctor.d(16): Error: cannot define both an rvalue constructor and a copy constructor for `struct Foo`
 fail_compilation\testrvaluecpctor.d(24):        Template instance `testrvaluecpctor.Foo!int.Foo.__ctor!(immutable(Foo!int), immutable(Foo!int))` creates an rvalue constructor for `struct Foo`
-fail_compilation\testrvaluecpctor.d(24): Error: none of the overloads of `this` can construct a `immutable` object with argument types `(immutable(Foo!int))`
+fail_compilation\testrvaluecpctor.d(24): Error: none of the overloads of `this` can construct an immutable object with argument types `(immutable(Foo!int))`. Expected `immutable(immutable(Foo!int))`
 fail_compilation\testrvaluecpctor.d(18):        Candidates are: `testrvaluecpctor.Foo!int.Foo.this(ref scope Foo!int rhs)`
 fail_compilation\testrvaluecpctor.d(16):                        `this(Rhs, this This)(scope Rhs rhs)`
 fail_compilation\testrvaluecpctor.d(40): Error: cannot define both an rvalue constructor and a copy constructor for `struct Test`
----
```

It's a simple update in that file.

https://github.com/dlang/dmd/blob/142d509af22cc51f08aa5bdb8bea96f5e088a3ef/compiler/test/fail_compilation/testrvaluecpctor.d#L8

Comment (abulgit) [reply compiler/src/dmd/funcsem.d:1721]: Thank u. Now i think it works

Comment (rikkimax) [reply compiler/src/dmd/funcsem.d:1721]: Ignore my original comment here, the LOC originates from before this PR.

**Review by rikkimax — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]
