### PR TITLE
fix #18614 RTInfo generation can fail for structs defined in imported modules

### LINKED ISSUE #18614: RTInfo generation can fail for structs defined in imported modules
### CC List

* Mike Franklin

### Description

````markdown
The current default implementation for template RTInfo always sets the value 0x12345678, so this should work:

////////////////
module s;

struct S
{
	int x;
	void* p;
}

///////////////
module test;

import s;

struct T
{
	int x;
	void* p;
}

void main()
{
	assert(typeid(T).rtInfo == cast(void*)0x12345678); // ok
	assert(typeid(S).rtInfo == cast(void*)0x12345678); // fails
}

////////////////
but the second assertion triggers if compiled with

dmd test.d

If you add s.d to the command line, it does not fail.
````

### PR DESCRIPTION
**Pull request by rainers**
allow RTInfo to be generated from the glue layer as similar members of the TypeInfo, e.g. xeq and xcmp.

This is simpler solution than #2480, but calling back semantic analysis from the glue layer is more of a workaround that takes advantage of the simplicity of the RTInfo template that just evaluates a __traits(getPointerBitmap).

### CODE REVIEW

File: compiler/src/dmd/semantic3.d [hunk 1]
```diff
@@ -1595,34 +1595,10 @@ private extern(C++) final class Semantic3Visitor : Visitor
 
         sc2.pop();
 
-        // Instantiate RTInfo!S to provide a pointer bitmap for the GC
-        // Don't do it in -betterC or on unused deprecated / error types
-        if (!ad.getRTInfo && global.params.useTypeInfo && Type.rtinfo &&
-            (!ad.isDeprecated() || global.params.useDeprecated != DiagnosticReporting.error) &&
```
Comment (rainers) [inline compiler/src/dmd/semantic3.d:1601]: This line is removed in the moved code as it is now unnecessary to skip deprecated structs. Scope's STC.deprecated_ takes care of muting deprecation messages.

File: compiler/src/dmd/aggregate.d [hunk 2]
```diff
@@ -145,6 +145,7 @@ extern (C++) abstract class AggregateDeclaration : ScopeDsymbol
     DtorDeclaration fieldDtor;  /// function destructing (non-inherited) fields
 
     Expression getRTInfo;   /// pointer to GC info generated by object.RTInfo(this)
+    Scope* rtInfoScope;     /// scope to be used when evaluating getRTInfo
```
Comment (thewilsonator) [inline compiler/src/dmd/aggregate.d:148]: need to update `aggregate.h` and `frontend.h`

File: compiler/src/dmd/semantic3.d [hunk 3]
```diff
@@ -1792,6 +1768,37 @@ void semanticTypeInfoMembers(StructDeclaration sd)
...
     }
+    sd.semanticRTInfo();
+}
+
+void semanticRTInfo(AggregateDeclaration ad)
+{
+    // Instantiate RTInfo!S to provide a pointer bitmap for the GC
+    // Don't do it in -betterC or on unused deprecated / error types
+    if (!ad.getRTInfo && global.params.useTypeInfo && Type.rtinfo && ad.rtInfoScope &&
+        (ad.type && ad.type.ty != Terror))
```
Comment (thewilsonator) [inline compiler/src/dmd/semantic3.d]: use an early return

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Otherwise looks good

File: compiler/src/dmd/glue/todt.d [hunk 4]
```diff
@@ -1447,6 +1447,12 @@ private extern (C++) class TypeInfoDtVisitor : Visitor
         if (!sd.members)
             return;
 
+        if (sd.semanticRun < PASS.semantic3done)
```
Comment (rainers) [inline compiler/src/dmd/glue/todt.d:1450]: This should not be checked for templates only, as an incomplete TypeInfo can replace the correct one (compiled into the source modules object file) when linking.

File: compiler/src/dmd/semantic3.d (hunk 3 above)
Comment (rainers) [reply compiler/src/dmd/semantic3.d]: done

File: compiler/src/dmd/aggregate.d (hunk 2 above)
Comment (rainers) [reply compiler/src/dmd/aggregate.d:148]: fixed

**Review by thewilsonator — APPROVED** [review]

File: compiler/test/runnable/test10443.d [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+    int x;
+    void* p;
+}
+
+void main()
+{
+    // assumes enum RTInfo(T) merges identical bitmaps
+    assert(typeid(T).rtInfo !is null); // ok
+    assert(typeid(S).rtInfo is typeid(T).rtInfo); // fails
+}
```
Comment (kinke) [inline compiler/test/runnable/test10443.d:15]: Hmm, this testcase seems to work with DMD v2.111.0 already, checked on run.dlang.io.

I'm looking at this PR since I've seen a regression for Symmetry code with LDC ~master, 2 undefined `RTInfoImpl` symbols.

**Edit**: Oh sorry, I think run.dlang.io compiles both files, not just a single one. I'm still trying to figure out what the problem was - really a wrong bitmap, or unexpectedly not folded to a single symbol?
**Edit2**: Oh okay, this is a pointer comparison only - and yields `0x1 != 0x5aff845707d0` when comparing them with v2.111.

Comment (kinke) [reply compiler/test/runnable/test10443.d:15]: Okay sorry, now I understand - it previously took a sema3 for the `StructDeclaration` to get a proper `.getRTInfo` expression, silently falling back to emitting a (likely non-compatible) non-bitmap variant if the TypeInfo was emitted without the struct getting sema3.

Comment (kinke) [reply compiler/test/runnable/test10443.d:15]: FWIW, the undefined symbols originate from C-bindings structs defined in a `.di` file (Deimos OpenSSL bindings). `-allinst` doesn't fix it (LDC's `-linkonce-templates` would work around it).

I've tried to use `ad.rtInfoScope` directly instead of `sc3`, doesn't fix it. Also tried without `start/endCTFE()`, no change. I've checked LDC's `-vv` log, and apparently the `RTInfoImpl` instantiation isn't codegen-culled, but not added to any root modules in the first place. (The TypeInfo is referenced in another template instance…)

[I guess it would work if the structs were defined in a (compiled and linked) `.d` file instead, so that the non-templated structs get codegen'd, and the `RTInfoImpl` hopefully instantiated in some root module. But it should still be possible to use/generate TypeInfos for such trivial C structs defined in non-compiled `.di` files.]

Comment (kinke) [reply compiler/test/runnable/test10443.d:15]: What works in our case is this addition:
```D
if (sc3.minst && !sc3.minst.isRoot() && sc3.minst.importedFrom)
    sc3.minst = sc3.minst.importedFrom; // a root module
```

But the `importedFrom` module could actually already have finished codegen if we're emitting multiple object files for the compiler invocation (and the TypeInfo for a non-sema3-struct is requested in a later object file)...

Comment (kinke) [reply compiler/test/runnable/test10443.d:15]: An attempt to handle this in the glue layer: https://github.com/ldc-developers/ldc/pull/5066
