### PR TITLE
Disallow discarding an assignment to a struct rvalue

### LINKED ISSUE #21507: Calling opAssign on an rvalue should be illegal
```
void main ()
{
    foo() = 42;
}

int foo()
{
    return 0;
}
```
gives the error
```
q.d(3): Error: cannot modify expression `foo()` because it is not an lvalue
    foo() = 42;
       ^
```
However,
```
void main ()
{
    foo() = S.init;
}

S foo()
{
    return S.init;
}

struct S
{
    int i;

    void opAssign(S s)
    {
        this.i = s.i;
    }
}
```
compiles just fine.

I don't see why overloading `opAssign` should behave any differently in this respect than the built-in assignment does. It just makes it so that you can accidentally assign to an rvalue and have the result disappear on you without getting any errors about doing something nonsensical.

`opOpAssign` has the same problem: https://github.com/dlang/dmd/issues/19061

### PR DESCRIPTION
**Pull request by ntrel**
More permissive version of #21717 (which already found an unintended no-op in libdparse). This allows the assignment if it returns a value which is used, so this doesn't [break libmir](https://github.com/dlang/dmd/pull/21717#issuecomment-3191656768).
Fixes https://github.com/dlang/dmd/issues/21507.

Error only applies when struct has no pointer fields - as a pointer could be written through, making the assignment meaningful. (This could be tightened to also error when there's a pointer field but it's not tail mutable). Note this is required not to break [ae.utils.array.list](https://github.com/CyberShadow/ae/blob/v0.0.3672/utils/array.d#L1072-L1093) whose `opAssign` writes through its context pointer.

My plan is to enable this for the 2024 edition, as it potentially can break existing calls of a user-defined op overload which has a (non-pointer) field but mutates a global. That should be a rare case and the compiler suggests workarounds. Note that requiring weak purity (for e.g. `opAssign`) would mean the error wouldn't detect bug-prone cases that aren't marked/inferred pure.

### CODE REVIEW

**Comment by ntrel** [comment]
The tests for e36981e showed only 3 projects in buildkite were broken, all due to them depending on older libdparse (which had a real bug). So I've made this require >= 2024 edition to enable the new error as mentioned. I pushed a fix for the C++ header (which CircleCI was failing on).

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -5274,6 +5274,16 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
         setError();
     }
 
+    void setOpOverloadAssign(Expression e)
```
Comment (WalterBright) [inline compiler/src/dmd/expressionsem.d]: Need function documentation

**Comment by WalterBright** [comment]
Can you please be clearer about what problem this addresses?

**Comment by ntrel** [comment]
@WalterBright It detects assignments which have no effect (aside from writing to globals which is rare - I haven't seen any), indicating a bug. In these cases the programmer believes it has an effect - e.g. the [libdparse one](https://github.com/dlang-community/libdparse/pull/525).

File: compiler/src/dmd/expressionsem.d (hunk 1 above)
Comment (ntrel) [reply compiler/src/dmd/expressionsem.d]: I've made it private and added a comment.

**Comment by thewilsonator** [comment]
please rebase

**Comment by ntrel** [comment]
@thewilsonator Now done.
