### PR TITLE
Fix 20334: ImportC: enums created from string literal #defines don’t implicitly convert to const(char)* in D.

### LINKED ISSUE #20334: ImportC: enums created from string literal #defines don’t implicitly convert to const(char)* in D.
### CC List

* Walter Bright (@WalterBright)

### Description

````markdown
Following D code works fine:

enum X = "X";
import core.stdc.stdio;
void main(){
    puts(X);
}

However, if that enum X is the result of a #define in a C file, you get an error:

// x.c
#define X “X”

// D code
import x;
import core.stdc.stdio;
void main(){
    puts(X); // Error
}
 // Error: function `core.stdc.stdio.puts(scope const(char*) s)` is not callable using argument types `(char[2])`
//         cannot pass argument `"X"` of type `char[2]` to parameter `scope const(char*) s`
````

### PR DESCRIPTION
**Pull request by drpriver**
Fixes: https://github.com/dlang/dmd/issues/20334

After preprocessing, #defines in C code that are just string literals are converted into D enums. As these are collected for use in D code, they should behave like D string literals and not C string literals.

### CODE REVIEW

File: compiler/src/dmd/expression.d [hunk 1]
```diff
@@ -1406,6 +1406,8 @@ extern (C++) final class StringExp : Expression
 
     /// If the string is parsed from a hex string literal
     bool hexString = false;
+    /// If the string is from a collected C macro
+    bool cMacro = false;
```
Comment (ibuclaw) [inline compiler/src/dmd/expression.d:1410]: expression.h needs update too for the benefit of gdc/ldc.

Comment (drpriver) [reply compiler/src/dmd/expression.d:1410]: Updated.

Comment (thewilsonator) [inline compiler/src/dmd/expression.d:1410]: how many bools does it take for a packed bitfield to be worth it?

Comment (drpriver) [reply compiler/src/dmd/expression.d:1410]: This is currently using space that would otherwise be unused due to padding.

**Review by thewilsonator — APPROVED** [review]
