### PR TITLE
fix #22069 Backend tail recursion optimization is broken

### LINKED ISSUE #22069: Backend tail recursion optimization is broken
This is #21400 with more detail. In short, the tail recursion optimization in the backend transforms tail recursion into a loop without doing any data flow analysis, which breaks pointers to local variables.

```d
int recurse(int* i)
{
    int j = 0;
    int* p = &j;
    if (p is i) return j;
    return recurse(p);
}

void main()
{
    int i = 1;
    recurse(&i);
}
```

Expected: stack overflow or infinite loop
Actual (with `-O`): returns

The offending pass is
https://github.com/dlang/dmd/blob/dd250bc17fd3bffb7ed961a723e8bd3d812fd0b5/compiler/src/dmd/backend/blockopt.d#L1544-L1688

Possible fixes include:
- Do proper DFA and inhibit tail recursion optimization if any local variable is passed by reference.
- Set `Fnotailrecursion` as needed during escape analysis in the frontend.
- Disable tail recursion optimization on functions that take a pointer.
- Remove tail recursion optimization altogether.

### PR DESCRIPTION
**Pull request by WalterBright**
https://github.com/dlang/dmd/issues/22069

### CODE REVIEW

File: compiler/src/dmd/backend/blockopt.d [hunk 1]
```diff
@@ -2122,3 +2128,22 @@ private void blexit(ref GlobalOptimizer go)
 
     bexits.dtor();
 }
+
+/***********************************
+ * Determine if any addresses of locals on the stack are taken.
+ * Returns:
+ *      true for addresses taken
+ */
+@trusted
```
Comment (thewilsonator) [inline compiler/src/dmd/backend/blockopt.d:2137]: does this really need to be `@trusted`?

File: compiler/test/runnable/issue22069.d [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+int recurse(int* i)
+{
+  L1:
+    int j = 0;
+    int* p = &j;
+
+    if (*i)
+    {
+	return recurse(p);
```
Comment (thewilsonator) [inline compiler/test/runnable/issue22069.d]: indentation

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/backend/blockopt.d (hunk 1 above)
Comment (WalterBright) [reply compiler/src/dmd/backend/blockopt.d:2137]: The function accesses a mutable global variable.

File: compiler/test/runnable/issue22069.d (hunk 2 above)
Comment (WalterBright) [reply compiler/test/runnable/issue22069.d]: fixed
