### PR TITLE
fix #20365 - Bitfield address escapes through ref

### LINKED ISSUE #20365: -preview=bitfields: Bit field address escapes through `ref`
### CC List

* Nick Treleaven (@ntrel)

### Description

````markdown
struct S {
    ubyte _x:4, _y:4;
    ubyte* p() => &_x;   // Error: cannot take address of bit-field `_x`
    ref ubyte x() => _x; // Compiles
}
````

### PR DESCRIPTION
**Pull request by ibuclaw**
The first part of this fix is to recognize most the places where a conversion to `ref` may occur for bitfields.

The second part is to handle `auto ref` so that those cases remove `ref` and continue to work.

The rest fixes up the error messages around the fallout to make it explicit that bitfields are the reason for rejection.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -16638,7 +16628,7 @@ private bool checkAddressVar(Scope* sc, Expression exp, VarDeclaration v)
  * Returns:
  *      true if the expression is addressable
  */
-bool checkAddressable(Expression e, Scope* sc)
+bool checkAddressable(Expression e, Scope* sc, const(char)* action)
```
Comment (thewilsonator) [inline compiler/src/dmd/expressionsem.d:16639]: need to update the docs
```diff
 * Params:
 *      e = expression to check
 *      sc = context
 +*    action = diagnostic error
```

**Review by thewilsonator — APPROVED** [review]
