### PR TITLE
Propagate NRVO variables in inliner

### LINKED ISSUE #18043: inline messes up RVO-ed object
### CC List

* Ketmar Dark

### Description

````markdown
In the concurrency package I am relying on RVO being performed, essentially I want to ensure placement of a struct on the callee's stack. I am aware I cannot get 100% guarantee of RVO since the compiler is free to perform a blit anywhere it likes.

Regardless, I have tests that ensure it applies RVO. It works fine on all 3 compilers until I turn on DMD's -inline.

I am aware RVO isn't guaranteed to be performed, but since it works fine without inlining, I suspect there is something afoul there (since, by definition, if it is inlined it need not blit anymore).

As a workaround I am using NVRO.

---
struct S {
    @disable this(ref return scope typeof(this) rhs);
    @disable this(this);
    void* cons;
    this(int i) {
        cons = cast(void*)&this;
    }
    void start() {
        void* s = cast(void*)&this;
        assert(cons == s);  // fails on dmd when build with -inline
    }
}

auto fun() {
//    auto s = S(42); // NVRO does work though...
//    return s;
    return S(42);
}

void main() {
    auto op = fun();
    op.start();
}
---
````

### PR DESCRIPTION
**Pull request by limepoutine**
Fixes #18043.

### CODE REVIEW

**Comment by limepoutine** [comment]
This is ready for review.

File: compiler/test/runnable/rvalue1.d [hunk 1]
```diff
@@ -288,19 +288,15 @@ struct V12
...
-
-S12 bar()
+S12 foo12()
 {
     return __rvalue(V12(1).s);
 }
 
 void test12()
 {
-    foo(bar());
```
Comment (thewilsonator) [inline compiler/test/runnable/rvalue1.d:303]: is the reason this test is altered because it wasn't actually tested and therefore what was there originally did not work?

**Review by thewilsonator — APPROVED** [review]
This otherwise looks good.

File: compiler/test/runnable/rvalue1.d (hunk 1 above)
Comment (limepoutine) [reply compiler/test/runnable/rvalue1.d:303]: Yes. I accidentally removed the call when rebasing, and the inliner is not designed to avoid blitting, so it was not expected to work.

Comment (thewilsonator) [reply compiler/test/runnable/rvalue1.d:303]: Thanks
