### PR TITLE
Fix #21317 : Wrong Location for error messages

### LINKED ISSUE #21317: Wrong Location for error messages
The Code:
<pre>
int[writeln] arr1;
</pre>
Outputs:
<pre>
test.d(1): Error: `writeln` is not defined, perhaps `import std.stdio;` ?
int[writeln] arr1;
             ^
</pre>
But, it shouldn't point to the `arr` but to `writeln`.

Expected Output:
<pre>
test.d(1): Error: `writeln` is not defined, perhaps `import std.stdio;` ?
int[writeln] arr1;
    ^
</pre>

The same is for all these codes:
<pre>
int[writeln] arr1;

int zero = 0;
int [Zero] arr2;

int [NULL] arr3;

struct S4
{
    enum E4 : this
    {
        fail,
    } 
}

int [unknown] arr5;
</pre>

Current Output:
<pre>
test.d(1): Error: `writeln` is not defined, perhaps `import std.stdio;` ?
int[writeln] arr1;
             ^
ttest.d.d(4): Error: undefined identifier `Zero`, did you mean variable `zero`?
int [Zero] arr2;
           ^
test.d(6): Error: undefined identifier `NULL`, did you mean `null`?
int [NULL] arr3;
           ^
test.d(10): Error: undefined identifier `this`, did you mean `typeof(this)`?
    enum E4 : this
    ^
test.d(16): Error: undefined identifier `unknown`
int [unknown] arr5;
              ^
</pre>

Expected:
<pre>
test.d(1): Error: `writeln` is not defined, perhaps `import std.stdio;` ?
int[writeln] arr1;
    ^
ttest.d.d(4): Error: undefined identifier `Zero`, did you mean variable `zero`?
int [Zero] arr2;
     ^
test.d(6): Error: undefined identifier `NULL`, did you mean `null`?
int [NULL] arr3;
     ^
test.d(10): Error: undefined identifier `this`, did you mean `typeof(this)`?
    enum E4 : this
              ^
test.d(16): Error: undefined identifier `unknown`
int [unknown] arr4;
     ^
</pre>

### PR DESCRIPTION
**Pull request by Ay1nDas**
- fixed #21317

### CODE REVIEW

File: compiler/test/fail_compilation/b23686.d [hunk 1]
```diff
@@ -1,10 +1,10 @@
 /*
 TEST_OUTPUT:
 ---
-fail_compilation/b23686.d(107): Error: undefined identifier `eFN1`, did you mean template `eFN0()()`?
+fail_compilation/b23686.d-mixin-107(107): Error: undefined identifier `eFN1`, did you mean template `eFN0()()`?
```
Comment (Ay1nDas) [inline compiler/test/fail_compilation/b23686.d:4]: To apply the changes, at lines `4` & `7` `-mixin- ` was added. 
Please let me know if it is undesirable.

Comment (thewilsonator) [reply compiler/test/fail_compilation/b23686.d:4]: the location is what he location is. This is fine.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Please squash the commits and set the title to `Fix  #21317`. Also why is this going into stable? It should probably target master unless there is specific reason to do so.

**Comment by Ay1nDas** [comment]
> Please squash the commits and set the title to `Fix #21317`. Also why is this going into stable? It should probably target master unless there is specific reason to do so.
I think the issue #21317 can be considered a bug. So, that's why I decided to use stable branch

**Comment by thewilsonator** [comment]
> I think the issue https://github.com/dlang/dmd/issues/21317 can be considered a bug.

Technically it is a bug. Functionally it is a _very_ low priority bug. 

Things that go straight to stable are thing that fix: regressions; crashes (of the generated program); internal compiler errors (crashes of the compiler); security fixes; critical bugs; major bugs; blockers; code changes that are already in stable but not in master (e.g. fixing an error message for one of the above categories).

**Comment by Ay1nDas** [comment]
Should I just close this PR and open a new one for dmd-master?

**Comment by thewilsonator** [comment]
Ah, welcome to the joy of retargeting git branches. Short answer you may find it easiest to do just that, but you should learn how to do it properly at some point, e.g. to preserve any useful conversation and reviews.

I see you have figured out how to change the branch already. You also need to rebase your changes locally on `master` and then force push to your fork. If you don't understand what that means or how to do it, please don't hesitate to ask.

**Comment by Ay1nDas** [comment]
😆 Okay, I am taking the hard route.

**Comment by Ay1nDas** [comment]
After rebase, 8 other commits are also merging with master. Is it okay?

**Comment by thewilsonator** [comment]
In this case, yes, because you originally targeted `stable`. Merging stable into master is always a safe thing to do the opposite, merging master into stable is not and is only done as part of the release process. 

However you still need to learn how to rebase your commits. I'm about to go to sleep, and I have a cold, but I will ping some others to explain it for you.

**Comment by schveiguy** [comment]
@Ay1nDas to rebase you need to run the `git rebase` command locally. There isn't a way to do it in github.

In my setup, I usually have an `upstream` remote that refers to the main repository. In that case, for this PR, what I would do is:

```console
> git fetch upstream
> git rebase --onto upstream/master stable fix-argLoc
```
What this does is replay the changes you made on fix-argLoc *since* the last time you got the table branch *onto* the upstream master branch. If this works properly, you should see just your commits in this PR (after you force-push).

For more info on git rebase, you can look at the documentation here: https://git-scm.com/docs/git-rebase

**Comment by Ay1nDas** [comment]
Thanks @schveiguy. I will update it to reflect only my changes.

**Comment by ibuclaw** [comment]
Massages->Messages

File: compiler/src/dmd/typesem.d [hunk 2]
```diff
@@ -168,18 +168,19 @@ private void resolveHelper(TypeQualified mt, Loc loc, Scope* sc, Dsymbol s, Dsym
         /* Look for what user might have intended
          */
         const p = mt.mutableOf().unSharedOf().toChars();
+        auto argLoc = ((mt.loc != Loc.initial) ? mt.loc : loc ); //Location of p is present else uses loc
```
Comment (ibuclaw) [inline compiler/src/dmd/typesem.d:171]: Should this instead be bubbled up to the resolveHelper caller?

File: compiler/test/fail_compilation/b23686.d (hunk 1 above)
Comment (ibuclaw) [reply compiler/test/fail_compilation/b23686.d:4]: Don't think this is correct. Mixin errors should have mixin locations if it occurs inside the context of a mixin.

Here the mixin succeeded in compiling, it's the template that subsequently failed because it can't find the result of the mixin.

File: compiler/src/dmd/typesem.d [hunk 3]
```diff
@@ -1945,7 +1945,18 @@ Type typeSemantic(Type type, Loc loc, Scope* sc)
...
+            switch (mtype.index.ty)
+            {
+                case Tident:    indexLoc = mtype.index.isTypeIdentifier().loc;  break;
+                case Tinstance: indexLoc = mtype.index.isTypeInstance().loc;    break;
+                case Ttypeof:   indexLoc = mtype.index.isTypeTypeof().loc;      break;
+                case Treturn:   indexLoc = mtype.index.isTypeReturn().loc;      break;
+                case Tmixin:    indexLoc = mtype.index.isTypeMixin().loc;       break;
+                default: indexLoc = mtype.loc;
+            }
+                mtype.index.resolve(indexLoc, sc, e, t, s);
```
Comment (thewilsonator) [inline compiler/src/dmd/typesem.d:1959]: why is this indented?

File: compiler/src/dmd/typesem.d [hunk 4]
```diff
@@ -2748,7 +2759,11 @@ Type typeSemantic(Type type, Loc loc, Scope* sc)
         Expression e;
         Dsymbol s;
         //printf("TypeIdentifier::semantic(%s)\n", mtype.toChars());
-        mtype.resolve(loc, sc, e, t, s);
+        if(mtype.loc!=Loc.initial)
```
Comment (thewilsonator) [inline compiler/src/dmd/typesem.d:2762]: space between `if (`

File: compiler/src/dmd/typesem.d [hunk 5]
```diff
@@ -2748,7 +2760,11 @@ Type typeSemantic(Type type, Loc loc, Scope* sc)
         Expression e;
         Dsymbol s;
         //printf("TypeIdentifier::semantic(%s)\n", mtype.toChars());
-        mtype.resolve(loc, sc, e, t, s);
+        if (mtype.loc!=Loc.initial)
```
Comment (thewilsonator) [inline compiler/src/dmd/typesem.d:2763]: sorry, spaces between `mtype.loc != Loc.initial` too

**Review by thewilsonator — APPROVED** [review]
otherwise looks good

File: compiler/src/dmd/typesem.d (hunk 5 above)
Comment (Ay1nDas) [reply compiler/src/dmd/typesem.d:2763]: It's Okay 😃. I should have followed the best practices before pushing.
