### PR TITLE
Fix #20859 - ICE: class with __vtbl field name causes segfault in Sco…

### LINKED ISSUE #20859: ICE: class with __vtbl field name causes segfault in Scope::inCfile
Code:
```
class ICE
{
    void **__vtbl;
}
```

Backtrace
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555559ab620 in Scope::inCfile() const (this=...) at src/dmd/dscope.d-mixin-184:248
248     in src/dmd/dscope.d-mixin-184
#0  0x00005555559ab620 in Scope::inCfile() const (this=...) at src/dmd/dscope.d-mixin-184:248
#1  0x00005555559c0b73 in AddMemberVisitor::visit(Dsymbol*) (this=0x7ffff76398c0, dsym=0x7ffff767cf00) at src/dmd/dsymbolsem.d:4183
#2  0x0000555555b0310a in ParseTimeVisitor<ASTCodegen>::visit(Declaration*) (this=0x7ffff76398c0, s=0x7ffff767cf00) at src/dmd/visitor/parsetime.d:31
#3  0x0000555555b03303 in ParseTimeVisitor<ASTCodegen>::visit(VarDeclaration*) (this=0x7ffff76398c0, s=0x7ffff767cf00) at src/dmd/visitor/parsetime.d:51
#4  0x0000555555976b7a in VarDeclaration::accept(Visitor*) (this=0x7ffff767cf00, v=0x7ffff76398c0) at src/dmd/declaration.d:1233
#5  0x00005555559c0977 in _D3dmd10dsymbolsem9addMemberFCQBc7dsymbol7DsymbolPSQBx6dscope5ScopeCQCoQBm12ScopeDsymbolZv (sds=0x7ffff7b7f330, sc=0x0, dsym=0x7ffff767cf00) at src/dmd/dsymbolsem.d:4123
#6  0x0000555555973c2c in ClassDeclaration::vtblSymbol() (this=0x7ffff7b7f330) at src/dmd/dclass.d:930
#7  0x0000555555b439b0 in _D3dmd6tocsym12toVtblSymbolFCQBb6dclass16ClassDeclarationbZPSQCh7backend2cc6Symbol (genCsymbol=true, cd=0x7ffff7b7f330) at src/dmd/tocsym.d:673
#8  0x0000555555b50021 in toObjFile::ToObjFile::visit(ClassDeclaration*) (this=0x7fffffffc898, cd=0x7ffff7b7f330) at src/dmd/toobj.d:387
#9  0x0000555555973cd6 in ClassDeclaration::accept(Visitor*) (this=0x7ffff7b7f330, v=0x7fffffffc898) at src/dmd/dclass.d:951
#10 0x0000555555b4fd8d in _D3dmd5toobj9toObjFileFCQw7dsymbol7DsymbolbZv (multiobj=false, ds=0x7ffff7b7f330) at src/dmd/toobj.d:1043
#11 0x0000555555b36cb9 in _D3dmd4glue10genObjFileFCQx7dmodule6ModulebZv (multiobj=false, m=0x7ffff7b7f000) at src/dmd/glue.d:1418
#12 0x0000555555b3322e in _D3dmd4glue20generateCodeAndWriteFACQBi7dmodule6ModuleAPxaAxaQdbbbbbZv (verbose=false, multiobj=false, oneobj=true, obj=true, writeLibrary=false, objdir=..., libname=...,
    libmodules=..., modules=...) at src/dmd/glue.d:338
#13 0x0000555555932bca in _D3dmd4main7tryMainFmPPxaKSQz7globals5ParamZi (params=..., argv=0x7fffffffd978, argc=2) at src/dmd/main.d:760
#14 0x0000555555931001 in _Dmain (__param_0=...) at src/dmd/main.d:143
```

### PR DESCRIPTION
**Pull request by dkorpel**
…pe::inCfile

### CODE REVIEW

File: compiler/test/fail_compilation/test20859.d [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/**
+TEST_OUTPUT:
+---
+fail_compilation/test20859.d(8): Error: variable `test20859.ICE.__vtbl` conflicts with variable `test20859.ICE.__vtbl` at fail_compilation/test20859.d(10)
```
Comment (thewilsonator) [inline compiler/test/fail_compilation/test20859.d:4]: can we give a better error message here?

Comment (dkorpel) [reply compiler/test/fail_compilation/test20859.d:4]: In general, there should be an error for using identifiers starting with `__` because they are reserved, but so far I haven't found a good place to do that since there isn't always a clear distinction between 'generated/druntime' code and user code. So I think it's a more involved problem than simply fixing this ICE.
