### PR TITLE
fix some misc test suite null pointer usage

### LINKED ISSUE #21697: Test in xtest46 test796 asserting on null pointer should be a throw
The test ``test796`` is asserting on a null pointer, which results in an ``Error`` class always throwing.

https://github.com/dlang/dmd/blob/fc25ce92f3d102eb5840312af812311fb714c71b/compiler/test/runnable/xtest46.d#L2583

Instead of using assert for this, which could never succeed, throw an ``Error`` directly.

I.e.

``throw new Error("Always throws");``

There is nothing wrong with wanting the ``Error`` to be thrown, but the assert could never succeed so the ``Error`` should be thrown directly.

Here is the bug report that introduced this test: https://issues.dlang.org/show_bug.cgi?id=796

Changing the assert to the throw will not change the validity of the test.

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by rikkimax** [comment]
The xtest46 is failing, due to the test not being broken for nullability.
It's broken due to truthiness.

Replace the assert with a ``throw new Error("");`` and it should pass.

Fixes https://github.com/dlang/dmd/issues/21697

File: compiler/test/runnable/xtest46.d [hunk 1]
```diff
@@ -2583,7 +2583,7 @@ struct Foo126
 void test796()
 {
     struct S { invariant() { throw new Exception(""); } }
-    S* s;
+    S* s = new S;
     try {
         assert(s);
     } catch (Error) {
```
Comment (ibuclaw) [inline compiler/test/runnable/xtest46.d]: This'll fail though as an Error wouldn't be raised.

**Comment by ibuclaw** [comment]
> Replace the assert with a ``throw new Error("");`` and it should pass.
> 

But then you're no longer checking the codegen does the right thing.

File: compiler/test/runnable/xtest46.d (hunk 1 above)
Comment (rikkimax) [reply compiler/test/runnable/xtest46.d]: Yes the CI is failing due to that.

**Comment by rikkimax** [comment]
Remove the xtest46 changes please, it seems that the assert is in fact required to exhibit the bug its testing for.

**Comment by thewilsonator** [comment]
done
