### PR TITLE
SAOC 25 fix #20433: ImportC:typeof in initializer expression at function scope errors with "circular typeof definition"

### LINKED ISSUE #20433: ImportC: typeof in initializer expression at function scope errors with "circular `typeof` definition"
### Description

````markdown
This valid C code:

int x = sizeof(typeof(x));
int main(){
    int y = sizeof(typeof(y));
}

Errors with: 

t.c(3): Error: circular `typeof` definition.

As you can see it does not error at file scope however.
````

### PR DESCRIPTION
**Pull request by Emmankoko**
fixes #20433.

@dkorpel @thewilsonator

### CODE REVIEW

File: compiler/test/runnable/fix20433.c [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+int x = sizeof(typeof(typeof(x))); // supported in C
+int main()
+{
+
+    int y = sizeof(typeof(y));
+    assert(y == 4);
+    assert(x == 4);
+
+}
```
Comment (thewilsonator) [inline compiler/test/runnable/fix20433.c]: newline at end of file

**Review by thewilsonator — APPROVED** [review]
otherwise looks good
