### PR TITLE
Fix issue #21744 - ImportC: four-digit UCN identifiers \unnnn don't match eight-digit \Unnnnnnnn

### LINKED ISSUE #21744: ImportC: four-digit UCN identifiers \unnnn don't match eight-digit \Unnnnnnnn
@rikkimax 

The ImportC lexer relies on the C preprocessor to replace all 4-digit UCN short identifiers with 8-digit identifiers.  Meaning while this compiles when file has the extension `ucn.c`, it fails when it's `ucn.i`.
```c
int main (void)
{
    struct \u00C0 { int \u00C1; } x;
    struct \u00C0 *y = &x;
    y->\u00C1 = 1;
    if (x.\U000000C1 != 1)
        return 1;
    goto \U000000ff;
    \u00ff: ;
    enum e { \u00C2 = 4 };
    if (\U000000C2 != 4)
        return 1;
    return 0;
}
```

```
ucn.i(6): Error: `\U000000C1` is not a member of `\u00C0`
    if (x.\U000000C1 != 1)
        ^
ucn.i(11): Error: undefined identifier `\U000000C2`
    if (\U000000C2 != 4)
        ^
ucn.i(8): Error: function `ucn.main` label `\U000000ff` is undefined
    goto \U000000ff;
    ^
```

This should compile as per C11 6.4.3-4
> **Semantics**
> The universal character name \U nnnnnnnn designates the character whose eight-digit short identifier
(as specified by ISO/IEC 10646) is nnnnnnnn.80) Similarly, the universal character name \u nnnn
designates the character whose four-digit short identifier is nnnn (and whose eight-digit short
identifier is 0000nnnn).

### PR DESCRIPTION
**Pull request by rikkimax**
…Fix issue #21740 - ImportC: UCN accepts invalid characters as part of the symbol name

@ibuclaw both should be fixed in this PR.

### CODE REVIEW

File: compiler/src/dmd/lexer.d [hunk 1]
```diff
@@ -701,12 +704,94 @@ class Lexer
...
+                            p += times - 1;  // skip to last character in the hex value
                             continue;
                         }
                         break;
                     }
 
-                    Identifier id = Identifier.idPool((cast(char*)t.ptr)[0 .. p - t.ptr], false);
+                    Identifier id;
+
+                    if (universalCharacterName4 > 0 || universalCharacterName8 > 0)
```
Comment (thewilsonator) [inline compiler/src/dmd/lexer.d]: please write this as 
```
if (universalCharacterName4 == 0 && universalCharacterName8 == 0)
{
    id = Identifier.idPool((cast(char*)t.ptr)[0 .. p - t.ptr], false);
}
else 
{
    // ...
}
```

File: compiler/src/dmd/lexer.d [hunk 2]
```diff
@@ -701,12 +704,96 @@ class Lexer
...
+                                {
+                                    if (!charLookup.isStart(tempDchar))
+                                        warning(t.loc, "char 0x%x is not allowed start character for an identifier", tempDchar);
+                                }
+                                else
+                                {
+                                    if (!charLookup.isContinue(tempDchar))
+                                        warning(t.loc, "char 0x%x is not allowed continue character for an identifier", tempDchar);
+                                }
+                            }
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: This isn't conforming to C11 spec.

**Review by ibuclaw — CHANGES_REQUESTED** [review]

File: compiler/src/dmd/lexer.d [hunk 3]
```diff
@@ -701,12 +704,96 @@ class Lexer
...
+                                        c -= 'a' - 10;
+                                    else if (c >= 'A' && c <= 'F')
+                                        c -= 'A' - 10;
+
+                                    tempDchar <<= 4;
+                                    tempDchar |= c;
+                                }
+
+                                priorVPtr += times - 1;
+                                utf_encodeChar(&storage[offset], tempDchar);
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: Missing `utf_isValidDchar`

File: compiler/src/dmd/lexer.d (hunk 2 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Is this for universal character name constraints, or something else?

Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: > A universal character name shall not specify a character whose short identifier is less than
00A0 other than 0024 ($), 0040 (@), or 0060 (‘), nor one in the range D800 through
DFFF inclusive.73)

**shall not** is to be interpreted as a prohibition.

Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: I'm going to swap the C11 version of this for the C23 one.

> A universal character name shall not designate a code point where the hexadecimal value is:
— in the range D800 through DFFF inclusive; or
— greater than 10FFFF.67)

This is handled via the call to ``utf_isValidDchar`` which I'll add.

File: compiler/src/dmd/lexer.d (hunk 3 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Done.

File: compiler/src/dmd/lexer.d (hunk 2 above)
Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: Hmm, that's not in C23, C2Y perhaps?

Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Let's see if I am reading the rest correctly in C23.

I suspect it doesn't want the character set test isStart/isContinue, and it wants a test for > 255 for valid UCN.

If so, I hate it, but I'll change it if you are reading it the same.

> A universal character name outside the c-char sequence of a character constant, or the s-char
sequence of a string literal shall not designate a control character or a character in the basic character
set.

Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Its from last public draft. If it isn't the final description please post it.

Comment (rikkimax) [reply compiler/src/dmd/lexer.d]:
```c
int \U0003134B;
```

clang: ``<source>:1:5: error: expected identifier or '('``

gcc: accepts it

Okay, that is right down the middle for if isStart/isContinue being checked.

File: compiler/src/dmd/lexer.d [hunk 4]
```diff
@@ -701,12 +704,102 @@ class Lexer
...
+
+                                    tempDchar <<= 4;
+                                    tempDchar |= c;
+                                }
+
+                                priorVPtr += times - 1;
+
+                                if (!utf_isValidDchar(tempDchar))
+                                {
+                                    warning(t.loc, "char 0x%x code point is outside of valid UTF-8 encoding range and cannot be in an identifier", tempDchar);
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: "shall not" -> error
```suggestion
                                    error(t.loc, "character 0x%x is not allowed in an identifier", tempDchar);
```

Although, given a few random characters a test, gcc and clang refuse characters that are within the range that isn't explicitly rejected in spec.

i.e:
```
int \uE0000(void)
{
    return 0;
}
```
Maybe its rejected in ISO/IEC 10646, but I don't have access to that spec paper?

File: compiler/src/dmd/lexer.d [hunk 5]
```diff
@@ -701,12 +704,102 @@ class Lexer
...
+                                    else if (c >= 'a' && c <= 'f')
+                                        c -= 'a' - 10;
+                                    else if (c >= 'A' && c <= 'F')
+                                        c -= 'A' - 10;
+
+                                    tempDchar <<= 4;
+                                    tempDchar |= c;
+                                }
+
+                                priorVPtr += times - 1;
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: This looks odd, given that `priovVPtr` is not adjusted again after this, copy pasto?
```suggestion
                                priorVPtr += times;
```

File: compiler/src/dmd/lexer.d [hunk 6]
```diff
@@ -701,12 +704,102 @@ class Lexer
...
+                            priorValidation.length - (
+                                    (universalCharacterName4 * 6) +
+                                    (universalCharacterName8 * 10)
+                            )) + (
+                                (universalCharacterName4 * 3) +
+                                (universalCharacterName8 * 4)
+                        );
+
+                        char[64] buffer = void;
+                        SmallBuffer!char sb = SmallBuffer!char(possibleLength + 1, buffer[]);
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: There's a `stringbuffer` field accessible from this method, perhaps would be simpler just to reuse that instead.

https://github.com/dlang/dmd/blob/659adc359ae35ac27d425b2ff0d71edad4d070b9/compiler/src/dmd/lexer.d#L64

File: compiler/src/dmd/lexer.d (hunk 5 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: It should be the same as the previous logic and its used afterwards for the isStart/isContinue check.

File: compiler/src/dmd/lexer.d (hunk 4 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: I tried ``int \U000E0000;`` with clang and gcc, same results as above.
Note: I'm explicitly setting ``-std=c23``

I got the previous value from looking at the character table for C23 and grabbing something outside its range.

File: compiler/src/dmd/lexer.d (hunk 6 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: I did not know about that. I'll swap it out after we figure the other stuff out.

File: compiler/src/dmd/lexer.d (hunk 2 above)
Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: Are you sure you're setting `-std` correctly?

https://compiler-explorer.com/z/nMPxK3sqK

Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: You used C11, I used C23, hence different results.

File: compiler/src/dmd/lexer.d [hunk 7]
```diff
@@ -701,12 +704,102 @@ class Lexer
...
+                                if (priorVPtr is priorValidation.ptr)
+                                {
+                                    if (!charLookup.isStart(tempDchar))
+                                        warning(t.loc, "char 0x%x is not allowed start character for an identifier", tempDchar);
+                                }
+                                else
+                                {
+                                    if (!charLookup.isContinue(tempDchar))
+                                        warning(t.loc, "char 0x%x is not allowed continue character for an identifier", tempDchar);
+                                }
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]:
```suggestion
                                utf_encodeChar(&storage[offset], tempDchar);
                                offset += utf_codeLengthChar(tempDchar);

                                if (priorVPtr is priorValidation.ptr)
                                {
                                    if (!charLookup.isStart(tempDchar))
                                        error(t.loc, "char 0x%x is not allowed start character for an identifier", tempDchar);
                                }
                                else
                                {
                                    if (!charLookup.isContinue(tempDchar))
                                        error(t.loc, "char 0x%x is not allowed continue character for an identifier", tempDchar);
                                }
```
Maybe just stick to the original - which I assume is controlled by `-identifiers-importc=` - but give errors same as the regular identifier path?

File: compiler/src/dmd/lexer.d (hunk 2 above)
Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: Maybe best to stay with just isStart/isContinue, same as the regular identifier path.  Best to be consistent rather than have two different checks for identifiers and ucn.

Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: If you try a C11 character that is not in the character set: ``int \U000EFFFF;``

GCC: ``<source>:1:5: error: universal character \U000EFFFF is not valid in an identifier``

clang: ``<source>:1:5: error: expected identifier or '('``

And that is definitely out of range, I checked C11 spec again.

File: compiler/src/dmd/lexer.d [hunk 8]
```diff
@@ -701,12 +704,102 @@ class Lexer
...
+                            }
+                            else
+                            {
+                                storage[offset++] = *priorVPtr;
+                                priorVPtr++;
+                            }
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: By the way, what would happen if there's mixed ucn and unicode characters in the identifier symbol?

File: compiler/src/dmd/lexer.d (hunk 2 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: > Maybe best to stay with just isStart/isContinue, same as the regular identifier path. Best to be consistent rather than have two different checks for identifiers and ucn.

Yeah, that is basically my original thinking. Allowing identifiers to be indeterminate within a single file is just asking for trouble.

File: compiler/src/dmd/lexer.d (hunk 7 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Okay yeah I'll swap it back to how it was but with error instead of warning.

File: compiler/src/dmd/lexer.d (hunk 8 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Only partially tested.

https://github.com/dlang/dmd/blob/master/compiler/test/compilable/ident_UAX31.c

File: compiler/src/dmd/lexer.d (hunk 5 above)
Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: The first loop:
```
p += times - 1;
continue;
```
`p` is then incremented again at the top of the loop before being read.  So when adjusting, you must leave it pointing at the end of the UCN, the next iteration will `p++` the pointer to the beginning of the next identifier or `\`.

Here, there's no such adjusting of `priorVPtr` at the beginning of the loop.  So I don't think it'll consume correctly.
i.e: `\u00c4\u00c4` I guess will end up as `Ä4Ä` because `4` is scanned twice.

File: compiler/src/dmd/lexer.d (hunk 8 above)
Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: Hmm, so that means unicode characters won't be decoded properly then.  So that makes 3 times calling decodeUTF8/isStart/isContinue within this case block -> screaming that it should be factored out somehow.

File: compiler/src/dmd/lexer.d (hunk 5 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Confirmed.

Fixed.

File: compiler/src/dmd/lexer.d (hunk 8 above)
Comment (rikkimax) [reply compiler/src/dmd/lexer.d]: Once this PR is done, if you want to rewrite you can.

Gotta get it working first.

**Comment by rikkimax** [comment]
CI is green @ibuclaw anything else you need from this PR?

**Comment by ibuclaw** [comment]
> CI is green @ibuclaw anything else you need from this PR?

Yes, I think I mentioned mixed UCN and Unicode.

I see a test for mixed UCN and ascii
```
typedef int \u0441b\U000003b4;
```
Also should check
```
typedef int \u0441😄\U000003b4;
```

**Comment by rikkimax** [comment]
Ok added one to ``compilable/test21740.i``.

**Comment by ibuclaw** [comment]
Checking compiler output usually helps. :-)

I managed to find time to pull this PR and check it against gcc, there is disparity.
```
$ gcc ucn.i -c; nm ucn.o
0000000000000008 B ↂ
0000000000000010 B Á
000000000000000c B À
0000000000000014 B Â
000000000000001c B aÄbсδe
0000000000000020 B b〡𗘰〣e
0000000000000004 B Ⅰ
0000000000000018 B whÿ
0000000000000000 B x²
$ dmd ucn.i -c; nm ucn.o
0000000000000000 t 
0000000000000008 B ↂ
0000000000000010 B Á
000000000000000c B À
0000000000000014 B Â
000000000000001c B aÄbсδ               # <- missing e
0000000000000020 B b〡𗘰〣              # <- missing e
0000000000000004 B Ⅰ
0000000000000018 B whÿ
0000000000000000 B x²
```

File: compiler/src/dmd/lexer.d [hunk 9]
```diff
@@ -701,12 +704,79 @@ class Lexer
...
+                    {
+                        id = Identifier.idPool((cast(char*)t.ptr)[0 .. p - t.ptr], false);
+                    }
+                    else
+                    {
+                        auto priorValidation = t.ptr[0 .. p - t.ptr];
+                        const(char)* priorVPtr = priorValidation.ptr;
+                        stringbuffer.setsize(0);
+
+                        while(priorVPtr < &priorValidation[$-1])
```
Comment (ibuclaw) [inline compiler/src/dmd/lexer.d]: I think either the slice needs to be +1'd, or the condition be the end of the slice inclusive. Otherwise the last byte ends up being chopped off.

[edit removed code suggestions]

Comment (ibuclaw) [reply compiler/src/dmd/lexer.d]: Actually, there's no need for the slice at all, since `p` points at the end of the identifier.
```suggestion
                        const(char)* priorVPtr = t.ptr;
                        stringbuffer.setsize(0);

                        while(priorVPtr < p)
```

**Comment by rikkimax** [comment]
> Checking compiler output usually helps. :-)
> 
> I managed to find time to pull this PR and check it against gcc, there is disparity.
> 
> ```
> $ gcc ucn.i -c; nm ucn.o
> 0000000000000008 B ↂ
> 0000000000000010 B Á
> 000000000000000c B À
> 0000000000000014 B Â
> 000000000000001c B aÄbсδe
> 0000000000000020 B b〡𗘰〣e
> 0000000000000004 B Ⅰ
> 0000000000000018 B whÿ
> 0000000000000000 B x²
> $ dmd ucn.i -c; nm ucn.o
> 0000000000000000 t 
> 0000000000000008 B ↂ
> 0000000000000010 B Á
> 000000000000000c B À
> 0000000000000014 B Â
> 000000000000001c B aÄbсδ               # <- missing e
> 0000000000000020 B b〡𗘰〣              # <- missing e
> 0000000000000004 B Ⅰ
> 0000000000000018 B whÿ
> 0000000000000000 B x²
> ```

Me was stupid, < instead of <= lol.

Anyway, I got sick of it, so now we have a dedicated UCN test with D handling the comparison.

**Review by ibuclaw — APPROVED** [review]
OK for now. Though the lexing of identifiers ought to go in its own routine, and squash UTF8 and UCN handling together in the same loop, rather than this double-looping going on for UCN.

@rikkimax I also note that decoding UCNs bypass the BIDI security feature, oversight perhaps?

**Comment by rikkimax** [comment]
> OK for now. Though the lexing of identifiers ought to go in its own routine, and squash UTF8 and UCN handling together in the same loop, rather than this double-looping going on for UCN.
> 
> @rikkimax I also note that decoding UCNs bypass the BIDI security feature, oversight perhaps?

Walter doesn't want normalization, so we're already bypassing known security concerns.

**Comment by rikkimax** [comment]
FreeBSD timed out in Phobos, not dmd.

**Comment by ibuclaw** [comment]
> Walter doesn't want normalization, so we're already bypassing known security concerns.

Don't know where you heard that from, we've been rejecting bidi control characters for a while now.

https://github.com/dlang/dmd/blob/eeb9f29bf0d13af86f85f15ac099b9cf7ba4ae83/compiler/src/dmd/lexer.d#L3328-L3329

**Comment by rikkimax** [comment]
> > Walter doesn't want normalization, so we're already bypassing known security concerns.
> 
> Don't know where you heard that from, we've been rejecting bidi control characters for a while now.
> 
> https://github.com/dlang/dmd/blob/eeb9f29bf0d13af86f85f15ac099b9cf7ba4ae83/compiler/src/dmd/lexer.d#L3328-L3329

When I originally did the identifier tables for UAX31, me and Walter got into quite a disagreement around normalization.
Its requirement for C23&UAX31 to use it.
It is classed as a security issue, due to the ability to have identifiers that look the same but are not.

**Comment by ibuclaw** [comment]
> Its requirement for C23&UAX31 to use it. It is classed as a security issue, due to the ability to have identifiers that look the same but are not.

Right, so it's one thing to have identifiers look the same in source code, but another for bidi control characters which can mess with the generated assembly, or the binary tools that interact with the object/program for debugging.

**Comment by rikkimax** [comment]
I checked, the UAX31 tables don't include bidi (which it shouldn't be doing).

It's the versions before C23 that are susceptible to it.

C11 basically went oh let's include basically the entire Unicode range. *sigh*

Ya know, the more I learn about the C11 tables in practice, the more I want to just dump the all identifier tables and just set us to UAX31 early. The Unicode people are smart, they've solved this already. C folk on the other hand...

**Comment by ibuclaw** [comment]
I did say the slice is not necessary. :-)
```
---
ERROR: This is a compiler bug.
Please report it via https://github.com/dlang/dmd/issues
with, preferably, a reduced, reproducible example and the information below.
DustMite (https://github.com/CyberShadow/DustMite/wiki) can help with the reduction.
---
core.exception.ArrayIndexError@src/dmd/lexer.d(725): index [18446744073709551615] is out of bounds for array of length 0
```
