### PR TITLE
Fix #20502 - importc: macro conflicts with struct of same name

### LINKED ISSUE #20502: importc: macro conflicts with struct of same name
### Description

````markdown
```
struct mg_str {

};

void mg_str_s() {

}

#define mg_str(s) mg_str_s(s)
```



The following fail with DMD

```
#defines(119): Error: template `bug.mg_str(__MP21)(__MP21 s)` conflicts with struct `bug.mg_str` at bug.c(1)
```


Perhaps this doesn't cover templates? https://github.com/dlang/dmd/pull/12567
````

### PR DESCRIPTION
**Pull request by drpriver**
Fixes https://github.com/dlang/dmd/issues/20502

Similar to `VarDeclaration`s, don't let `TemplateDeclaration`s from C defines shadow a real symbol.

### CODE REVIEW

File: compiler/src/dmd/dtemplate.d [hunk 1]
```diff
@@ -593,6 +593,7 @@ extern (C++) final class TemplateDeclaration : ScopeDsymbol
     bool isTrivialAliasSeq; /// matches pattern `template AliasSeq(T...) { alias AliasSeq = T; }`
     bool isTrivialAlias;    /// matches pattern `template Alias(T) { alias Alias = qualifiers(T); }`
     bool deprecated_;       /// this template declaration is deprecated
+    bool isCmacro;          /// Whether this template is a translation of a C macro
```
Comment (thewilsonator) [inline compiler/src/dmd/dtemplate.d:596]: Please update the corresponding header `template.h`

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Otherwise looks good.

File: compiler/src/dmd/dtemplate.d (hunk 1 above)
Comment (drpriver) [reply compiler/src/dmd/dtemplate.d:596]: Done.

**Review by thewilsonator — APPROVED** [review]
