### PR TITLE
SAOC 25: fix #20157: importC does not handle nested struct designated initializer

### LINKED ISSUE #20157: ImportC: only 1 designator currently allowed for C struct field initializer
### CC List

* Andrea Fontana

### Description

````markdown
struct Foo {
    int x;
    int y;
};

struct Bar {
    struct Foo f;
};

struct Bar b = {.f.x = 3}; // Error: only 1 designator currently allowed for C struct field initializer
struct Bar b2 = {
    .f.x = 3, // Error: only 1 designator currently allowed for C struct field initializer
    .f.y = 4,
};
````

### PR DESCRIPTION
**Pull request by Emmankoko**
This PR includes fix for issue 20157 about designated initializers.
link here: https://issues.dlang.org/show_bug.cgi?id=23374

```c
struct Foo {
    int x;
    int y;
};

struct Bar {
    struct Foo f;
};

struct Bar b = {.f.x = 3}; // Error: only 1 designator currently allowed for C struct field initializer
struct Bar b2 = {
    .f.x = 3, // Error: only 1 designator currently allowed for C struct field initializer
    .f.y = 4,
};
```

This fix also fixes it for arrays and unions. 

This fix has been tested thoroughly and tests are attached to this PR.

Additionally, the error message for not supporting more than 1 designators also has to be changed to print it for only base types since member arrays and structs can lead to multiple designators.

@dkorpel @WalterBright

### CODE REVIEW

File: compiler/src/dmd/initsem.d [hunk 1]
```diff
@@ -820,20 +820,105 @@ Initializer initializerSemantic(Initializer init, Scope* sc, ref Type tx, NeedIn
...
+                            }
+                            if (!found)
+                            {
+                                error(ci.loc, "`.%s` is not a field of `%s`\n", id.toChars(), nstsd.toChars());
+                                return err();
+                            }
+
+                            auto base = field.type.toBasetype();
+
+                            if (i < length - 1)
```
Comment (thewilsonator) [inline compiler/src/dmd/initsem.d]: this is a heavily indented function as it is. Please rewrite this as 
```d
if (i >= length - 1)
{
    subsi.addInit(id, di.initializer);
    continue;
}
```

Comment (Emmankoko) [reply compiler/src/dmd/initsem.d]: alright. true. so that code. no longer lives in the if block.

File: compiler/src/dmd/initsem.d [hunk 2]
```diff
@@ -820,20 +820,105 @@ Initializer initializerSemantic(Initializer init, Scope* sc, ref Type tx, NeedIn
             {
                 DesigInit di = ci.initializerList[index];
                 Designators* dlist = di.designatorList;
+                VarDeclaration field;
                 if (dlist)
                 {
                     const length = (*dlist).length;
+                    auto id = (*dlist)[0].ident;
```
Comment (thewilsonator) [inline compiler/src/dmd/initsem.d:827]: this should be declared where it is used, on line 845

File: compiler/src/dmd/initsem.d [hunk 3]
```diff
@@ -909,7 +994,7 @@ Initializer initializerSemantic(Initializer init, Scope* sc, ref Type tx, NeedIn
                         continue Loop1;
                 }
 
-                VarDeclaration field;
+                //VarDeclaration field;
```
Comment (thewilsonator) [inline compiler/src/dmd/initsem.d]: this is declared above and should be removed

File: compiler/src/dmd/initsem.d (hunk 2 above)
Comment (Emmankoko) [reply compiler/src/dmd/initsem.d:827]: it is used throughout the whole if(dlist block). also used when length is 1. it is also used from line 924.
when it is parsing single designators.

File: compiler/src/dmd/initsem.d (hunk 3 above)
Comment (Emmankoko) [reply compiler/src/dmd/initsem.d]: yep.
