### PR TITLE
Fix dlang#18262 - Fix expected error message for enum auto-increment

### LINKED ISSUE #18262: Bad diagnostic for an enum member in an enum that use another enum as base type
### Description

````markdown
For

```
enum A1 : int
{
    a,
    b,
}

enum A2 : A1
{
    c, // does not require +1
    d, // requires + 1
}  
```

The definition of A2.d causes the error

> /tmp/temp_7F4942E9C090.d(10,5): Error: comparison between different enumeration types `A2` and `A1`; If this behavior is intended consider using `std.conv.asOriginalType`

which makes no sense.

In fact the real problem is that `A2.d` violates the specification 18.1.5 (https://dlang.org/spec/enum.html#named_enums), specifically _"it is given the value of the previous EnumMember + 1_".

In consequence a better message would be that `d` value cannot be automatically defined because the base type does not support increment.
````

### PR DESCRIPTION
**Pull request by samrendra-singh**
Fix #18262 

The original error message for "auto-incrementing enum members whose base type is another enum" stated that - Error: comparison between different enumeration types `A2` and `A1`; If this behavior is intended consider using `std.conv.asOriginalType`
which made no sense. 

This pull request improves the diagnostic message for auto-incrementing enum members when the base type is another enum. Now, it clearly instructs the user to provide an explicit initializer.

The fix: 
1. In enumsem.d, within the enumMemberSemantic function, I added a check to determine if the enum's base type is an enum. If it is, a clear error message is issued, and the auto-increment is aborted. This change prevents the confusing diagnostic previously encountered.
2. I added a test case file in ../test/fail_compilation/enum_auto_increment.d that replicates the issue. The new error message is correctly displayed when compiling the file with the updated DMD.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -61,3 +61,8 @@ untracked_files/
 
 # Just in case
 /dmd
+/compiler/src/dmd_backend_x86
+/compiler/src/dmd_lib
+/compiler/src/dmd_mangle
+/compiler/src/dmd_visitor
+/compiler/src
```
Comment (thewilsonator) [inline .gitignore:68]: remove these, also there is a merge conflict here

**Review by thewilsonator — CHANGES_REQUESTED** [review]

**Review by thewilsonator — APPROVED** [review]
Otherwise looks good

File: .gitignore (hunk 1 above)
Comment (solo-source) [reply .gitignore]: Hey, @thewilsonator the fix that i have proposed, keeps failing on three existing test cases. These three test cases i have listed below.
- compilable/issue20599.d
- fail_compilation/fail109.d
- fail_compilation/fail98.d

what should i do to resolve them.

File: compiler/test/fail_compilation/enum_auto_increment.d [hunk 2]
```diff
@@ -0,0 +1,18 @@
+/*
+TEST_OUTPUT:
+---
+fail_compilation\enum_auto_increment.d(17): Error: cannot automatically assign value to enum member `enum_auto_increment.A2.d` because base type `A1` is an enum; please provide an explicit value
```
[the remark this answers is not in the document]
Comment (solo-source) [reply compiler/test/fail_compilation/enum_auto_increment.d:4]: ok, will do that.

[the remark this answers is not in the document]
Comment (solo-source) [reply compiler/test/fail_compilation/enum_auto_increment.d:4]: hey, @thewilsonator the fix that i have proposed, keeps failing on three existing test cases. These three test cases i have listed below.
- compilable/issue20599.d
- fail_compilation/fail109.d
- fail_compilation/fail98.d

I would like to hear your suggestions on these as well.

File: compiler/src/dmd/enumsem.d [hunk 3]
```diff
@@ -524,6 +524,16 @@ void enumMemberSemantic(Scope* sc, EnumMember em)
         });
 
         assert(emprev);
+
+        // New check: if the base type is an enum, auto-increment is not supported.
+        if (em.ed.memtype && em.ed.memtype.isTypeEnum())
```
Comment (thewilsonator) [inline compiler/src/dmd/enumsem.d:529]: Ooh, good catch. In which case
```d
if (auto te = em.ed.memtype ? em.ed.memtype.isTypeEnum() : null)
{
    if (!te.sym.isSpecial()
        // error case goes here
```

**Comment by solo-source** [comment]
hey @thewilsonator I have edited the error message by removing "Please", also fixed the special enum case that resolved the failing testcase "compilable/issue20599.d", and edited the error messages in "fail_compilation/fail109.d" and "fail_compilation/fail98.d" to display the correct error messages.

**Review by thewilsonator — APPROVED** [review]

File: compiler/test/fail_compilation/fail98.d [hunk 4]
```diff
@@ -34,3 +37,4 @@ enum E
     D3DTS_TEXTURE7, // = 23
     D3DTS_FORCE_DWORD  = 0xffffffff
 }
+
```
Comment (thewilsonator) [inline compiler/test/fail_compilation/fail98.d:40]: remove this, `pre-commit` is complaining about it.

**Comment by thewilsonator** [comment]
Apparently this has merge conflicts? I can't see what they are though. Anyway, please rebase and we can get this merged.

**Comment by solo-source** [comment]
> Apparently this has merge conflicts? I can't see what they are though. Anyway, please rebase and we can get this merged.

i have rebased it, i think now it should work.
