### PR TITLE
Fix #21408 : Array comparison with recursive inferred opEquals gives confusing error message

### LINKED ISSUE #21408: Array comparison with recursive inferred opEquals gives confusing error message
The following code:
```d
struct A {
    A[] as;
    auto opEquals(A x) {
        return as == x.as;
    }
}

void main() {
    
}
```
produces the compiler error: 
```
 Error: incompatible types for array comparison: `A[]` and `A[]`
```
Replacing `auto` with `bool` causes it to compile.
I guess one would expect an error of the form:
```
can't infer return type  in function opEquals...
```

### PR DESCRIPTION
**Pull request by Ay1nDas**
- fixed #21408

### CODE REVIEW

File: compiler/src/dmd/expressionsem.d [hunk 1]
```diff
@@ -13416,8 +13429,8 @@ private extern (C++) final class ExpressionSemanticVisitor : Visitor
             __equals = __equals.trySemantic(sc); // for better error message
             if (!__equals)
             {
-                error(exp.loc, "incompatible types for array comparison: `%s` and `%s`",
-                          exp.e1.type.toChars(), exp.e2.type.toChars());
+                if(sc.func)
+                    error(exp.loc, "can't infer return type in function `%s`", sc.func.toChars());
                 __equals = ErrorExp.get();
```
Comment (thewilsonator) [inline compiler/src/dmd/expressionsem.d:13434]: either `sc.func` should always be true or you want
```d
if (!__equals)
{
    if (sc.func)
        error(exp.loc, "can't infer return type in function `%s`", sc.func.toChars());
    else
        error(exp.loc, "incompatible types for array comparison: `%s` and `%s`",
                  exp.e1.type.toChars(), exp.e2.type.toChars());
    __equals = ErrorExp.get();
}
```
here. A path that returns an `ErrorExp` should always issue an error.
Also, space between `if (` for `if(sc.func)`.

**Review by thewilsonator — APPROVED** [review]
