### PR TITLE
druntime: fix on x86/arm musl

### LINKED ISSUE #21800: stat_t layout and size on MIPS32-musl-linux is seemingly wrong
The size of `stat_t` when printed by C program on OpenWRT (mipsel32 platform using the musl libc) is 160. The following D code asserts here in `core.sys.posix.sys.stat`:
```d
        static if (!__USE_FILE_OFFSET64)
            static assert(stat_t.sizeof == 144);
        else
            static assert(stat_t.sizeof == 160);
```

Error:
```
core/sys/posix/sys/stat.d(319): Error: static assert:  `168u == 144u` is false
```

There seems to be multiple things wrong here. First I guess the second assert must be used when using musl libc, since multiple fields in the struct are 64-bit wide (like `off_t`).

Second there're multiple mismatches of the struct compared to [here](https://github.com/bminor/musl/blob/0b86d60badad6a69b37fc06d18b5763fbbf47b58/arch/mips/kstat.h#L1):
```c
//kstat.h
struct kstat {
	unsigned st_dev;
	long __st_padding1[3];
	ino_t st_ino;
	mode_t st_mode;
	nlink_t st_nlink;
	uid_t st_uid;
	gid_t st_gid;
	unsigned st_rdev;
	long __st_padding2[3];
	off_t st_size;
	long st_atime_sec;
	long st_atime_nsec;
	long st_mtime_sec;
	long st_mtime_nsec;
	long st_ctime_sec;
	long st_ctime_nsec;
	blksize_t st_blksize;
	long __st_padding3;
	blkcnt_t st_blocks;
        long __st_padding4[14];
};
``` 
Compare the D code:
```d
        struct stat_t
        {
            c_ulong     st_dev;
            c_long[3]   st_pad1;
            ino_t       st_ino;
            mode_t      st_mode;
            nlink_t     st_nlink;
            uid_t       st_uid;
            gid_t       st_gid;
            c_ulong     st_rdev;
            static if (!__USE_FILE_OFFSET64)
            {
                c_long[2]   st_pad2;
                off_t       st_size;
                c_long      st_pad3;
            }
            else
            {
                c_long[3]   st_pad2;
                off_t       st_size;
            }
            static if (_DEFAULT_SOURCE || _XOPEN_SOURCE >= 700)
            {
                timespec    st_atim;
                timespec    st_mtim;
                timespec    st_ctim;
                extern(D) @safe @property inout pure nothrow
                {
                    ref inout(time_t) st_atime() return { return st_atim.tv_sec; }
                    ref inout(time_t) st_mtime() return { return st_mtim.tv_sec; }
                    ref inout(time_t) st_ctime() return { return st_ctim.tv_sec; }
                }
            }
            else
            {
                time_t      st_atime;
                c_ulong     st_atimensec;
                time_t      st_mtime;
                c_ulong     st_mtimensec;
                time_t      st_ctime;
                c_ulong     st_ctimensec;
            }
            blksize_t   st_blksize;
            static if (!__USE_FILE_OFFSET64)
            {
                blkcnt_t    st_blocks;
            }
            else
            {
                c_long      st_pad4;
                blkcnt_t    st_blocks;
            }
            c_long[14]  st_pad5;
        }
```

The fields `st_atime`, `st_mtime` and `st_ctime` must be of type `c_ulong`, not `time_t` since `time_t` is always 64-bit on musl even on 32-bit systems.

Third, because `__USE_FILE_OFFSET64` is `false`, the struct layout does not match the one in the link. However, If i set `__USE_FILE_OFFSET64` to `true`, the struct grows to approx 180 bytes, so I'm not sure about the correct corrective action needed here.

### PR DESCRIPTION
**Pull request by sertonix**
tested on alpine linux x86 and armv7

code shrink suggestions welcome! I am not that familiar with dlang

Fixes https://github.com/dlang/dmd/issues/21800

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Looks fine to me, but I'll let someone who actually knows something about this a chance to chime in. cc @Geod24

**Comment by sertonix** [comment]
Is this still stuck in review?

**Comment by ibuclaw** [comment]
> Is this still stuck in review?

Do you have a reference to the headers? It might help.

File: druntime/src/core/sys/posix/dirent.d [hunk 1]
```diff
@@ -396,15 +396,7 @@ else version (CRuntime_Musl)
...
-    static if ( __USE_FILE_OFFSET64 )
-    {
-        dirent* readdir64(DIR*);
-        alias   readdir64 readdir;
-    }
-    else
-    {
-        dirent* readdir(DIR*);
-    }
+    dirent* readdir(DIR*);
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/dirent.d:399]: These cleanups for dead code, whilst understandable given the config module, are just unnecessary noise.

File: druntime/src/core/sys/posix/sys/stat.d [hunk 2]
```diff
@@ -93,7 +93,14 @@ version (linux)
...
             blkcnt_t    st_blocks;
-            static if (_DEFAULT_SOURCE || _XOPEN_SOURCE >= 700)
+            version (CRuntime_Musl) {
+                c_long      __st_atime;
+                c_long      __st_atimensec;
+                c_long      __st_mtime;
+                c_long      __st_mtimensec;
+                c_long      __st_ctime;
+                c_long      __st_ctimensec;
+            } else static if (_DEFAULT_SOURCE || _XOPEN_SOURCE >= 700)
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/sys/stat.d:103]: This is very suspicious wrt portability. At a glance it looks like `__time_t` might just be wrong for 32-bit archs. So fix that instead?

File: druntime/src/core/sys/posix/time.d [hunk 3]
```diff
@@ -200,8 +200,21 @@ version (linux)
 {
     struct timespec
     {
+        version (CRuntime_Musl) {
+            this(time_t tv_sec_, c_long tv_nsec_) @safe pure nothrow
+            {
+                tv_sec = tv_sec_;
+                tv_nsec = tv_nsec_;
+            }
+        }
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/time.d:209]: Preferred to be without constructors to avoid making in non-POD.

File: druntime/src/core/sys/posix/dirent.d (hunk 1 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/dirent.d:399]: I need to set `__USE_FILE_OFFSET64` to true again. If I don't remove the dead code before that it tries to use `*64` symbols which don't exist for musl.

File: druntime/src/core/sys/posix/sys/stat.d (hunk 2 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/sys/stat.d]: These are unused dummy variables in musl libc due to the switch from 32-bit `time_t` to 64-bit `time_t`. See this musl commit: https://git.musl-libc.org/cgit/musl/commit/arch/?id=38143339646a4ccce8afe298c34467767c899f51

**Comment by sertonix** [comment]
> Do you have a reference to the headers?

Sure, musl sources for reference (I hope I didn't forgot any important ones):

- `struct stat` on arm https://git.musl-libc.org/cgit/musl/tree/arch/arm/bits/stat.h
- `struct stat` on x86 https://git.musl-libc.org/cgit/musl/tree/arch/i386/bits/stat.h
- `struct stat` on mips https://git.musl-libc.org/cgit/musl/tree/arch/mips/bits/stat.h
- `struct timespec` (commit includes some explainations) https://git.musl-libc.org/cgit/musl/commit/include/alltypes.h.in?id=9b2921bea1d5017832e1b45d1fd64220047a9802

File: druntime/src/core/sys/posix/time.d (hunk 3 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/time.d]: Currently phobos is using the default constructor: https://github.com/dlang/phobos/blob/832cc465998b1ea77051cd3fd014b544442a4f8c/std/datetime/systime.d#L2617

If that could be changed it would be possible to not overwrite the default constructor here.

**Comment by kaniini** [comment]
What is the status on this?  We would like to enable D on 32-bit archs in Alpine, but are blocked by this.

File: druntime/src/core/sys/posix/time.d (hunk 3 above)
Comment (the-horo) [reply druntime/src/core/sys/posix/time.d]: https://dlang.org/spec/struct.html#POD says that *copy* constructors are not allowed on a POD, plain constructors are fine. `__traits(isPOD)` does return `true` for this sample and allowing non-copy constructors has been a conclusion in an old [discussion](https://forum.dlang.org/post/kbmblk$2jg8$1@digitalmars.com) as well.

File: druntime/src/core/sys/posix/sys/stat.d (hunk 2 above)
Comment (the-horo) [reply druntime/src/core/sys/posix/sys/stat.d]: Maybe it's worth renaming the variable to include the `tim32` suffix like they to in the musl headers and adding a comment explaining that these fields are only for ABI-compatibility with the `32`-bit  variant of the struct.

Other than that the struct matches the [musl declaration](https://git.musl-libc.org/cgit/musl/tree/arch/i386/bits/stat.h) (outside of using `ushort` instead of `int` for padding but the 4-byte alignment makes the declarations equivalent) and the `static assert` checking the size is a nice added safety.

File: druntime/src/core/sys/posix/sys/stat.d [hunk 4]
```diff
@@ -313,7 +341,22 @@ version (linux)
...
+                    ref inout(time_t) st_atime() return { return st_atim.tv_sec; }
+                    ref inout(time_t) st_mtime() return { return st_mtim.tv_sec; }
+                    ref inout(time_t) st_ctime() return { return st_ctim.tv_sec; }
+                }
+                c_long[2]   st_pad5;
+            }
+            else
+            {
+                c_long[14]  st_pad6;
+            }
```
Comment (the-horo) [inline druntime/src/core/sys/posix/sys/stat.d:403]: The timespec changes look good.

However, the `st_dev` declaration is not correct. https://git.musl-libc.org/cgit/musl/tree/arch/mips/bits/stat.h declares it as `dev_t` which is always `ulong` on musl: https://git.musl-libc.org/cgit/musl/tree/include/alltypes.h.in#n31. I don't think this should be a blocker for this PR, just something worth noting

File: druntime/src/core/sys/posix/sys/stat.d [hunk 5]
```diff
@@ -651,8 +701,21 @@ version (linux)
...
+                {
+                    ref inout(time_t) st_atime() return { return st_atim.tv_sec; }
+                    ref inout(time_t) st_mtime() return { return st_mtim.tv_sec; }
+                    ref inout(time_t) st_ctime() return { return st_ctim.tv_sec; }
+                }
+            }
         }
-        static if (__USE_FILE_OFFSET64)
+        version (CRuntime_Musl) {
+            static assert(stat_t.sizeof == 152);
```
Comment (the-horo) [inline druntime/src/core/sys/posix/sys/stat.d]: looks good

File: druntime/src/core/sys/posix/dirent.d (hunk 1 above)
Comment (ibuclaw) [reply druntime/src/core/sys/posix/dirent.d]: What about leaving `__USE_FILE_OFFSET64` to false?

It's fine that the `*64` symbols don't exist in musl, it's likely that these bindings are just cargo cult from the Glibc/UClibc code paths.  The clean-ups are warranted in their own right.

**Review by the-horo — APPROVED** [review]
The changes work for me and I've tested building gdc-11 through gdc-15 on x86 musl.

---

My only concern is that the D bindings still contain the time32 function declarations https://github.com/dlang/dmd/blob/c397436871bfb8051e2a3d4989cbfd5d87b195c9/druntime/src/core/sys/posix/sys/time.d#L92-L95
which makes it possible for someone to build druntime/phobos with time32 functions while using the time64 structs. This wouldn't be necessarily broken as the structs are meant to be ABI compatible, however, this can still lead to runtime errors because a consumer of the function wouldn't be aware that the 64-bit fields wouldn't contain anything meaningful.

For example, the struct `stat_t` on `x86` musl now looks like:
```d
struct stat_t
{
    dev_t       st_dev;
    ushort      __pad1;
    uint        __st_ino;
    mode_t      st_mode;
    nlink_t     st_nlink;
    uid_t       st_uid;
    gid_t       st_gid;
    dev_t       st_rdev;
    ushort      __pad2;
    off_t       st_size;
    blksize_t   st_blksize;
    blkcnt_t    st_blocks;
	c_long      __st_atime;
	c_long      __st_atimensec;
	c_long      __st_mtime;
	c_long      __st_mtimensec;
	c_long      __st_ctime;
	c_long      __st_ctimensec;
    ino_t       st_ino;
	timespec    st_atim;
	timespec    st_mtim;
	timespec    st_ctim;
	extern(D) @safe @property inout pure nothrow
	{
	    ref inout(time_t) st_atime() return { return st_atim.tv_sec; }
	    ref inout(time_t) st_mtime() return { return st_mtim.tv_sec; }
	    ref inout(time_t) st_ctime() return { return st_ctim.tv_sec; }
	}
}
```
and the 32bit variant was supposed to look like:
```d
struct stat_t
{
    dev_t       st_dev;
    ushort      __pad1;
    uint        __st_ino;
    mode_t      st_mode;
    nlink_t     st_nlink;
    uid_t       st_uid;
    gid_t       st_gid;
    dev_t       st_rdev;
    ushort      __pad2;
    off_t       st_size;
    blksize_t   st_blksize;
    blkcnt_t    st_blocks;
	time_t      st_atime;
	ulong_t     st_atimensec;
	time_t      st_mtime;
	ulong_t     st_mtimensec;
	time_t      st_ctime;
	ulong_t     st_ctimensec;
   ino_t       st_ino;
}
```

The issue here is that the `st_atime` symbol now resolves to different members. Then, consumers like phobos:
https://github.com/dlang/phobos/blob/24711b9c41aae447ff7079017bbe2d1416248fea/std/file.d#L1224-L1243, with this PR applied, would work correctly with time64 but they would be accessing uninitialized memory with the time32 function declarations.

Solving this would require to condition the new symbols on the value of `muslRedirTime64`: https://github.com/dlang/dmd/blob/670f8c6288b78da03d92dc3176a7c51c6f5ef1b6/druntime/src/core/stdc/config.d#L655-L661

Given that currently 32-bit musl is broken I think it's fine to accept this PR which fixes 32-bit musl with the default time64 functions and leave 32-bit musl with the opt-in time32 functions for some other time or until somebody opens an issue requesting support for this, which should only happen if trying to use new D compilers on pre-time64 musl versions.

File: druntime/src/core/sys/posix/dirent.d (hunk 1 above)
Comment (the-horo) [reply druntime/src/core/sys/posix/dirent.d]: No, it's not fine. musl only provides symbols like `readdir`, not `readdit64`. Using the latter leads to linker errors and is why https://github.com/dlang/dmd/pull/16361 was merged, as it fixed those symbol declarations on 64-bit arches.

Comment (ibuclaw) [reply druntime/src/core/sys/posix/dirent.d]: #21639

File: druntime/src/core/sys/posix/sys/stat.d (hunk 4 above)
Comment (ibuclaw) [reply druntime/src/core/sys/posix/sys/stat.d:403]: Yeah, so using alltypes.h.in as a reference, D runtime's bindings for [core.sys.posix.sys.types](https://github.com/dlang/dmd/blob/c397436871bfb8051e2a3d4989cbfd5d87b195c9/druntime/src/core/sys/posix/sys/types.d#L90-L143) may not be accurate.

File: druntime/src/core/sys/posix/dirent.d (hunk 1 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/dirent.d]: Thanks for merging that already.

> What about leaving __USE_FILE_OFFSET64 to false?

However that doesn't work. Other code paths are also affected by setting that to true. For example https://github.com/dlang/dmd/blob/415db752b5741663cdccc885120ddc33f0f8b452/druntime/src/core/sys/posix/sys/types.d#L90-L102

File: druntime/src/core/sys/posix/sys/stat.d (hunk 4 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/sys/stat.d:403]: Looks like you already fixed that in https://github.com/dlang/dmd/pull/21641

Thanks!

File: druntime/src/core/sys/posix/sys/stat.d (hunk 2 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/sys/stat.d]: I changed the names to include tim32. I am uncertain if comments are worth it cause checking upstream headers seems to be an implicit assumption in the whole file.

**Comment by sertonix** [comment]
> Given that currently 32-bit musl is broken I think it's fine to accept this PR which fixes 32-bit musl with the default time64 functions and leave 32-bit musl with the opt-in time32 functions for some other time or until somebody opens an issue requesting support for this, which should only happen if trying to use new D compilers on pre-time64 musl versions.

I currently don't have the time and setup to fix that as well. So I would prefer to ignore that in this MR (especially since this only affects old musl versions).

File: druntime/src/core/sys/posix/dirent.d (hunk 1 above)
Comment (ibuclaw) [reply druntime/src/core/sys/posix/dirent.d]: Yes, which I've noted here https://github.com/dlang/dmd/pull/21249#discussion_r2249931632

That module is clearly incorrectly written for musl.  I suggest making a new code path for Musl that reflects its default 64 bit type sizes.

Comment (sertonix) [reply druntime/src/core/sys/posix/dirent.d]: And what should be done with these? https://github.com/dlang/dmd/blob/1a51bc60703c361fa902713ba9c21d1ab8236322/druntime/src/core/sys/posix/fcntl.d#L146-L157 https://github.com/dlang/dmd/blob/1a51bc60703c361fa902713ba9c21d1ab8236322/druntime/src/core/sys/posix/fcntl.d#L166-L177 https://github.com/dlang/dmd/blob/1a51bc60703c361fa902713ba9c21d1ab8236322/druntime/src/core/sys/posix/sys/resource.d#L84-L92

And also multiple conditions in https://github.com/dlang/dmd/blob/master/druntime/src/core/sys/posix/sys/stat.d

File: druntime/src/core/sys/posix/time.d (hunk 3 above)
Comment (ibuclaw) [reply druntime/src/core/sys/posix/time.d]: @sertonix - D has supported named arguments since 2023.

https://dlang.org/spec/expression.html#argument-list

https://dlang.org/spec/struct.html#struct-literal

That can be changed to:
```diff
             immutable tv_sec = toUnixTime!(typeof(timespec.tv_sec))();
             immutable fracHNSecs = removeUnitsFromHNSecs!"seconds"(_stdTime - 621_355_968_000_000_000L);
             immutable tv_nsec = cast(typeof(timespec.tv_nsec))convert!("hnsecs", "nsecs")(fracHNSecs);
-            return timespec(tv_sec, tv_nsec);
+            return timespec(tv_sec: tv_sec, tv_nsec: tv_nsec);
         }
 
         @safe unittest
```

Comment (ibuclaw) [reply druntime/src/core/sys/posix/time.d]: https://github.com/dlang/phobos/pull/10838

File: druntime/src/core/sys/posix/dirent.d (hunk 1 above)
Comment (ibuclaw) [reply druntime/src/core/sys/posix/dirent.d]: Thanks for pointing those out.  OK, let's keep `__USE_FILE_OFFSET64` to true then.

Comment (ibuclaw) [reply druntime/src/core/sys/posix/dirent.d]: I'll raise a PR to split up core.sys.posix.sys.types in the meantime.

If someone can correct the types for Musl as a follow-up to it and test, that would be appreciated.

File: druntime/src/core/sys/posix/time.d [hunk 6]
```diff
@@ -200,8 +200,21 @@ version (linux)
...
         time_t  tv_sec;
+        version (CRuntime_Musl)
+            version (BigEndian)
+                byte[time_t.sizeof - c_long.sizeof] __pad1;
         c_long  tv_nsec;
+        version (CRuntime_Musl)
+            version (LittleEndian)
+                byte[time_t.sizeof - c_long.sizeof] __pad2;
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/time.d]: @sertonix another solution would be to wait for #21625

```suggestion
        // this should exist with htobe16 and others,
        // there are variations of the same header on at least freebsd and darwin too.
        import core.sys.linux.endian : BYTE_ORDER;
        // ...
        time_t  tv_sec;
        version (CRuntime_Musl)
            int : 8 * (time_t.sizeof - c_long.sizeof) * (BYTE_ORDER == 4321);
        c_long  tv_nsec;
        version (CRuntime_Musl)
            int : 8 * (time_t.sizeof - c_long.sizeof) * (BYTE_ORDER != 4321);
```

Like C, `timespec(1, 2)` won't initialize the unnamed bit-fields in D.

Comment (sertonix) [reply druntime/src/core/sys/posix/time.d]: That would be awesome! I have no idea how long we need to wait but it seems worth it.

Comment (ibuclaw) [reply druntime/src/core/sys/posix/time.d]: Raised PR for POSIX bindings for endian.h, that'll be of help later down the line. #21644

**Comment by ibuclaw** [comment]
@sertonix WRT acceptance without the current pending PRs being merged.  My only comment is that making changes to the existing definitions inline is a bit unwieldy wrt any potential future maintenance.

So my preference would be to hoist out `version (CRuntime_Musl)` into its own independent definition of each of these structs.

To take stat_t as the unfortunate victim to pick on, this is simpler than the current static condition spaghetti this PR has the definition in:
```d
version (CRuntime_Musl)
{
    // Musl always uses 64 bit off_t
    struct stat_t
    {
        dev_t st_dev;
        int __st_dev_padding;
        c_long __st_ino_truncated;
        mode_t st_mode;
        nlink_t st_nlink;
        uid_t st_uid;
        gid_t st_gid;
        dev_t st_rdev;
        int __st_rdev_padding;
        off_t st_size;
        blksize_t st_blksize;
        blkcnt_t st_blocks;
        private struct __timespec32
        {
            c_long tv_sec;
            c_long tv_nsec;
        }
        __timespec32 __st_atim32;
        __timespec32 __st_mtim32;
        __timespec32 __st_ctim32;
        ino_t st_ino;
        timespec st_atim;
        timespec st_mtim;
        timespec st_ctim;
        extern(D) @safe @property inout pure nothrow
        {
            ref inout(time_t) st_atime() return { return st_atim.tv_sec; }
            ref inout(time_t) st_mtime() return { return st_mtim.tv_sec; }
            ref inout(time_t) st_ctime() return { return st_ctim.tv_sec; }
        }
    }
}
else
{
    struct stat_t
    {
        dev_t       st_dev;
        ushort      __pad1;
        static if (!__USE_FILE_OFFSET64)
        {
            ino_t       st_ino;
        }
        else
        {
            uint        __st_ino;
        }
        mode_t      st_mode;
        nlink_t     st_nlink;
        uid_t       st_uid;
        gid_t       st_gid;
        dev_t       st_rdev;
        ushort      __pad2;
        off_t       st_size;
        blksize_t   st_blksize;
        blkcnt_t    st_blocks;
        static if (_DEFAULT_SOURCE || _XOPEN_SOURCE >= 700) 
        {
            timespec    st_atim;
            timespec    st_mtim;
            timespec    st_ctim;
            extern(D) @safe @property inout pure nothrow
            {
                ref inout(time_t) st_atime() return { return st_atim.tv_sec; }
                ref inout(time_t) st_mtime() return { return st_mtim.tv_sec; }
                ref inout(time_t) st_ctime() return { return st_ctim.tv_sec; }
            }
        }
        else
        {
            time_t      st_atime;
            ulong_t     st_atimensec;
            time_t      st_mtime;
            ulong_t     st_mtimensec;
            time_t      st_ctime;
            ulong_t     st_ctimensec;
        }
        static if (__USE_FILE_OFFSET64)
        {
            ino_t       st_ino;
        }
        else
        {
            c_ulong     __unused4;
            c_ulong     __unused5;
        }
    }
}

**Comment by sertonix** [comment]
> So my preference would be to hoist out version (CRuntime_Musl) into its own independent definition of each of these structs.

If that is limited to `timespec` and the `stat_t` that differ I would be fine with that

**Comment by ibuclaw** [comment]
> > So my preference would be to hoist out version (CRuntime_Musl) into its own independent definition of each of these structs.
> 
> If that is limited to `timespec` and the `stat_t` that differ I would be fine with that

That's fine. Its only 32bit platforms affected.

File: druntime/src/core/sys/posix/time.d (hunk 3 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/time.d]: I now used unnamed bitfields instead

File: druntime/src/core/sys/posix/sys/stat.d [hunk 7]
```diff
@@ -72,29 +72,37 @@ version (linux)
 {
     version (X86)
     {
-        struct stat_t
-        {
-            dev_t       st_dev;
-            ushort      __pad1;
-            static if (!__USE_FILE_OFFSET64)
+        version (CRuntime_Musl) {
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/sys/stat.d]:
```suggestion
        version (CRuntime_Musl)
        {
```

File: druntime/src/core/sys/posix/sys/stat.d [hunk 8]
```diff
@@ -572,98 +650,137 @@ version (linux)
...
-        {
-            __dev_t st_dev;
-            ushort __pad1;
-
-            static if (!__USE_FILE_OFFSET64)
-            {
-                __ino_t st_ino;
-            }
-            else
+        version (CRuntime_Musl) {
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/sys/stat.d]:
```suggestion
        version (CRuntime_Musl)
        {
```

**Review by ibuclaw — APPROVED** [review]
Just a couple of style nits, but otherwise looks OK.

File: druntime/src/core/sys/posix/sys/stat.d (hunk 7 above)
Comment (sertonix) [reply druntime/src/core/sys/posix/sys/stat.d]: Done

File: druntime/src/core/sys/posix/time.d [hunk 9]
```diff
@@ -201,7 +202,11 @@ version (linux)
     struct timespec
     {
         time_t  tv_sec;
+        version (CRuntime_Musl)
+            int : 8 * (time_t.sizeof - c_long.sizeof) * (endian.BYTE_ORDER == endian.BIG_ENDIAN);
         c_long  tv_nsec;
+        version (CRuntime_Musl)
+            int : 8 * (time_t.sizeof - c_long.sizeof) * (endian.BYTE_ORDER != endian.BIG_ENDIAN);
```
Comment (thewilsonator) [inline druntime/src/core/sys/posix/time.d]:
```
/__w/dmd/dmd/_generated/linux/release/64/../../../../druntime/import/core/sys/posix/time.d(206): Error: undefined identifier `endian`
            int : 8 * (time_t.sizeof - c_long.sizeof) * (endian.BYTE_ORDER == endian.BIG_ENDIAN);
                                                         ^
/__w/dmd/dmd/_generated/linux/release/64/../../../../druntime/import/core/sys/posix/time.d(206): Error: undefined identifier `endian`
            int : 8 * (time_t.sizeof - c_long.sizeof) * (endian.BYTE_ORDER == endian.BIG_ENDIAN);
                                                                              ^
Error: bitfield width `cast(ulong)8 * (8LU - 8LU) * (endian.BYTE_ORDER == endian.BIG_ENDIAN)` is not an integer constant
/__w/dmd/dmd/_generated/linux/release/64/../../../../druntime/import/core/sys/posix/time.d(209): Error: undefined identifier `endian`
            int : 8 * (time_t.sizeof - c_long.sizeof) * (endian.BYTE_ORDER != endian.BIG_ENDIAN);
                                                         ^
/__w/dmd/dmd/_generated/linux/release/64/../../../../druntime/import/core/sys/posix/time.d(209): Error: undefined identifier `endian`
            int : 8 * (time_t.sizeof - c_long.sizeof) * (endian.BYTE_ORDER != endian.BIG_ENDIAN);
                                                                              ^
Error: bitfield width `cast(ulong)8 * (8LU - 8LU) * (endian.BYTE_ORDER != endian.BIG_ENDIAN)` is not an integer constant
```

File: druntime/src/core/sys/posix/time.d [hunk 10]
```diff
@@ -16,6 +16,7 @@
 module core.sys.posix.time;
 
 import core.sys.posix.config;
+import core.sys.posix.endian;
```
Comment (ibuclaw) [inline druntime/src/core/sys/posix/time.d:19]:
```suggestion
import core.sys.posix.endian = endian;
```

File: druntime/src/core/sys/posix/time.d [hunk 11]
```diff
@@ -16,6 +16,7 @@
 module core.sys.posix.time;
 
 import core.sys.posix.config;
+import core.sys.posix.endian : endian;
```
Comment (the-horo) [inline druntime/src/core/sys/posix/time.d]:
```suggestion
import endian = core.sys.posix.endian;
```

**Review by the-horo — DISMISSED** [review]
