### PR TITLE
fix #21479: Correctly handle casts inlining

### LINKED ISSUE #21479: Unable to compile cast expression with `-inline` flag
Starting with commit `9e7f0af277b7762efa6ae1a3a35a0b6cb7257d17` (after PR  #21440 was merged), the following snippet of code, which is a simplified version of what is found in a test from the buildkite pipeline, will not compile when using the `-inline` flag:
```d
class A{}
class B : A{}

A get_B(int n)
{
    return new B();
}

int get_int(int m)
{
     return 42;
}

void main(){
     int a = 123;
     auto x = cast(B)get_B(get_int(a));
}
```
This is the output is the following:
```bash
---
ERROR: This is a compiler bug.
Please report it via https://github.com/dlang/dmd/issues
with, preferably, a reduced, reproducible example and the information below.
DustMite (https://github.com/CyberShadow/DustMite/wiki) can help with the reduction.
---
DMD v2.111.0
predefs  DigitalMars LittleEndian D_Version2 all D_SIMD Posix ELFv1 linux CRuntime_Glibc CppRuntime_GNU CppRuntime_Gcc D_InlineAsm_X86_64 X86_64 D_LP64 D_PIC assert D_PreConditions D_PostConditions D_Invariants D_ModuleInfo D_Exceptions D_TypeInfo D_HardFloat
binary    ../dlang/dmd/generated/linux/release/64/dmd
version   v2.111.0
config    ../dlang/dmd/generated/linux/release/64/dmd.conf
DFLAGS    -I../dlang/dmd/generated/linux/release/64/../../../../druntime/import -I../dlang/dmd/generated/linux/release/64/../../../../../phobos -L-L../dlang/dmd/generated/linux/release/64/../../../../../phobos/generated/linux/release/64 -L--export-dynamic -fPIC
---
core.exception.AssertError@src/dmd/backend/symbol.d(669): Assertion failure
----------------
??:? _d_assertp [0x55c58bf94d34]
src/dmd/backend/symbol.d:669 nothrow @trusted ulong dmd.backend.symbol.symbol_add(ref dmd.backend.barray.Barray!(dmd.backend.cc.Symbol*).Barray, dmd.backend.cc.Symbol*) [0x55c58beb282d]
src/dmd/backend/symbol.d:641 nothrow @trusted ulong dmd.backend.symbol.symbol_add(dmd.backend.cc.Symbol*) [0x55c58beb2776]
src/dmd/e2ir.d:4401 dmd.backend.el.elem* dmd.e2ir.Dsymbol_toElem(dmd.dsymbol.Dsymbol, ref dmd.toir.IRState) [0x55c58be12837]
src/dmd/e2ir.d:925 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitDeclaration(dmd.expression.DeclarationExp) [0x55c58be08134]
src/dmd/e2ir.d:4347 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06d9f]
src/dmd/e2ir.d:3138 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitComma(dmd.expression.CommaExp) [0x55c58be0ef50]
src/dmd/e2ir.d:4350 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06ded]
src/dmd/e2ir.d:5561 dmd.backend.el.elem* dmd.e2ir.callfunc(dmd.location.Loc, ref dmd.toir.IRState, int, dmd.mtype.Type, dmd.backend.el.elem*, dmd.mtype.Type, dmd.func.FuncDeclaration, dmd.mtype.Type, dmd.backend.el.elem*, dmd.root.array.Array!(dmd.expression.Expression).Array*, dmd.backend.el.elem*, dmd.backend.el.elem*) [0x55c58be15f3e]
src/dmd/e2ir.d:3585 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitCall(dmd.expression.CallExp) [0x55c58be103d2]
src/dmd/e2ir.d:4356 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06e89]
src/dmd/e2ir.d:5561 dmd.backend.el.elem* dmd.e2ir.callfunc(dmd.location.Loc, ref dmd.toir.IRState, int, dmd.mtype.Type, dmd.backend.el.elem*, dmd.mtype.Type, dmd.func.FuncDeclaration, dmd.mtype.Type, dmd.backend.el.elem*, dmd.root.array.Array!(dmd.expression.Expression).Array*, dmd.backend.el.elem*, dmd.backend.el.elem*) [0x55c58be15f3e]
src/dmd/e2ir.d:3585 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitCall(dmd.expression.CallExp) [0x55c58be103d2]
src/dmd/e2ir.d:4356 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06e89]
src/dmd/e2ir.d:4772 dmd.backend.el.elem* dmd.e2ir.toElemCast(dmd.expression.CastExp, dmd.backend.el.elem*, bool, ref dmd.toir.IRState) [0x55c58be13909]
src/dmd/e2ir.d:3838 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitCast(dmd.expression.CastExp) [0x55c58be10ed8]
src/dmd/e2ir.d:4359 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06ed7]
src/dmd/e2ir.d:2871 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitAssign(dmd.expression.AssignExp) [0x55c58be0e50c]
src/dmd/e2ir.d:4304 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be0695b]
src/dmd/e2ir.d:4406 dmd.backend.el.elem* dmd.e2ir.Dsymbol_toElem(dmd.dsymbol.Dsymbol, ref dmd.toir.IRState) [0x55c58be12875]
src/dmd/e2ir.d:925 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState).visitDeclaration(dmd.expression.DeclarationExp) [0x55c58be08134]
src/dmd/e2ir.d:4347 dmd.backend.el.elem* dmd.e2ir.toElem(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06d9f]
src/dmd/e2ir.d:397 dmd.backend.el.elem* dmd.e2ir.toElemDtor(dmd.expression.Expression, ref dmd.toir.IRState) [0x55c58be06159]
src/dmd/s2ir.d:692 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*).visitExp(dmd.statement.ExpStatement) [0x55c58be30e5d]
src/dmd/statement.d:1886 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*).visit.VisitStatement(dmd.statement.Statement) [0x55c58be33407]
src/dmd/s2ir.d:1466 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*) [0x55c58be2f45b]
src/dmd/s2ir.d:718 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*).visitCompound(dmd.statement.CompoundStatement) [0x55c58be30f41]
src/dmd/statement.d:1886 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*).visit.VisitStatement(dmd.statement.Statement) [0x55c58be3342c]
src/dmd/s2ir.d:1466 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*) [0x55c58be2f45b]
src/dmd/s2ir.d:718 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*).visitCompound(dmd.statement.CompoundStatement) [0x55c58be30f41]
src/dmd/statement.d:1886 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*).visit.VisitStatement(dmd.statement.Statement) [0x55c58be3342c]
src/dmd/s2ir.d:1466 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState, dmd.stmtstate.StmtState!(dmd.backend.cc.block).StmtState*) [0x55c58be2f45b]
src/dmd/s2ir.d:93 void dmd.s2ir.Statement_toIR(dmd.statement.Statement, ref dmd.toir.IRState) [0x55c58be2f439]
src/dmd/glue.d:884 void dmd.glue.FuncDeclaration_toObjFile(dmd.func.FuncDeclaration, bool) [0x55c58be26d86]
src/dmd/toobj.d:330 _ZN9toObjFile9ToObjFile5visitEP15FuncDeclaration [0x55c58be41de5]
src/dmd/func.d:1051 _ZN15FuncDeclaration6acceptEP7Visitor [0x55c58bd24535]
src/dmd/toobj.d:1043 void dmd.toobj.toObjFile(dmd.dsymbol.Dsymbol, bool) [0x55c58be41d4c]
src/dmd/glue.d:1420 void dmd.glue.genObjFile(dmd.dmodule.Module, bool) [0x55c58be28dec]
src/dmd/glue.d:338 void dmd.glue.generateCodeAndWrite(dmd.dmodule.Module[], const(char)*[], const(char)[], const(char)[], bool, bool, bool, bool, bool) [0x55c58be25379]
src/dmd/main.d:768 int dmd.main.tryMain(ulong, const(char)**, out dmd.globals.Param) [0x55c58bc25a2f]
src/dmd/main.d:148 _Dmain [0x55c58bc23dc2]
```
My guess is that something related to the cast's lowering is not handled properly in the inlined version, perhaps both the original expression and the lowering are getting converted to backend `elem*`, causing multiple indentical symbols to be added and therefore leading to assertion failure.

### PR DESCRIPTION
**Pull request by Albert24GG**
This PR addresses #21479 by handling some previously uncovered inlining scenarios.

### CODE REVIEW

File: compiler/src/dmd/inline.d [hunk 1]
```diff
@@ -754,18 +754,12 @@ public:
             ue.e1 = doInlineAs!Expression(e.e1, ids);
             if (auto ce = ue.isCastExp())
             {
-                if (ce.lowering is null)
-                    goto LskipCastLowering;
-
-                if (auto lowering = ce.lowering.isCallExp())
+                if (ce.lowering !is null)
```
Comment (teodutu) [inline compiler/src/dmd/inline.d]:
```suggestion
                if (auto lowering = ce.lowering)
```
This is usually more elegant than `!is null`.

File: compiler/src/dmd/inline.d [hunk 2]
```diff
@@ -754,18 +754,12 @@ public:
...
                 {
-                    if (lowering.f.ident == Id._d_cast)
-                    {
-                        ce.lowering = doInlineAs!Expression(lowering, ids);
-                    }
+                    ce.lowering = doInlineAs!Expression(ce.lowering, ids);
```
Comment (teodutu) [inline compiler/src/dmd/inline.d]:
```suggestion
                    ce.lowering = doInlineAs!Expression(lowering, ids);
```

File: compiler/src/dmd/inline.d [hunk 3]
```diff
@@ -1288,6 +1282,14 @@ public:
 
     override void visit(UnaExp e)
     {
+        if (auto ce = e.isCastExp())
+        {
+            if (ce.lowering !is null)
+            {
+                inlineScan(ce.lowering);
```
Comment (teodutu) [inline compiler/src/dmd/inline.d]:
```suggestion
            if (auto lowering = ce.lowering)
            {
                inlineScan(lowering);
```

**Review by teodutu — APPROVED** [review]
I just nit-picked some code formatting. Otherwise this is good stuff.

File: compiler/src/dmd/inline.d [hunk 4]
```diff
@@ -1288,6 +1282,14 @@ public:
 
     override void visit(UnaExp e)
     {
+        if (auto ce = e.isCastExp())
```
Comment (rainers) [inline compiler/src/dmd/inline.d]: You should override visit(CastExp) instead of the "dynamic cast" here. Probably in the other case, too.

**Review by rainers — APPROVED** [review]
LGTM wrt inlining.

Other visitors tend to be forgotten regarding lowerings, too, e.g. resolveLoc and toDelegate.

**Review by thewilsonator — APPROVED** [review]
