### PR TITLE
Fix opBinaryRight error message to suggest lhs instead of rhs

### LINKED ISSUE #22147: Improve error message when `opBinaryRight` is missing
This is the error message you get on a missing `opBinaryRight`:
```
onlineapp.d(17): Error: operator `/` is not defined for type `T`
onlineapp.d(6):        perhaps overload the operator with `auto opBinaryRight(string op : "/")(int rhs) {}`
```

The suggested parameter should be named `lhs`.

### PR DESCRIPTION
**Pull request by abulgit**
Close: #22147 

For `opBinaryRight`, the parameter represents the left-hand side operand, so it should be `lhs`

### CODE REVIEW

File: compiler/test/fail_compilation/issue22147.d [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+fail_compilation/issue22147.d(15): Error: operator `/` is not defined for type `T`
+fail_compilation/issue22147.d(9):        perhaps overload the operator with `auto opBinaryRight(string op : "/")(int lhs) {}`
+---
+*/
+
+struct T
+{
+}
+
+void main()
```
Comment (thewilsonator) [inline compiler/test/fail_compilation/issue22147.d]: only runnable rest function should contain a `main`, please call this `test` or something. Otherwise looks great!

Comment (abulgit) [reply compiler/test/fail_compilation/issue22147.d]: Oops, I totally Forgot that

**Review by thewilsonator — APPROVED** [review]
