### PR TITLE
fix #21976 Array comparison performance regression

### LINKED ISSUE #21976: [REG 2.112.0] Array comparison performance regression
```d
import std.stdio;
import std.range;
import std.array;
import std.datetime.stopwatch;
int[] arr = iota(1000).array;
int[] arr2 = iota(1000).array;

void main()
{
    StopWatch sw;
    sw.start();
    int val;
    foreach(i; 0 .. 1_000_000) {
        val += arr == arr2;
    }
    writeln(sw.peek);
}
```

On my system, running with 2.110.0 (unoptimized):

```
54 ms, 400 μs, and 3 hnsecs
```

Running with stable (d027882ba291a31a81e26400e3119dfe459a5f98):

```
2 secs, 466 ms, 468 μs, and 5 hnsecs
```

A slowdown of about 45x.

I believe this is because we are not using memcmp anymore. See https://github.com/dlang/dmd/pull/21513

### PR DESCRIPTION
**Pull request by WalterBright**
Call memcmp() instead of generating string instructions.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: compiler/src/dmd/glue/e2ir.d [hunk 1]
```diff
@@ -2193,8 +2193,16 @@ elem* toElem(Expression e, ref IRState irs)
 
                 elem* esize = t2.ty == Tsarray ? esiz2 : esiz1;
 
-                e = el_param(eptr1, eptr2);
-                e = el_bin(OPmemcmp, TYint, e, esize);
+                if (1)
```
Comment (ibuclaw) [inline compiler/src/dmd/glue/e2ir.d:2196]: There are valid reasons not to use libc (such as embedded/bare metal) but likely not a concern for dmd.

**Comment by kinke** [comment]
Thx Walter! As the performance regression is for v2.112, targeting `stable` would fix it for that version still.

File: compiler/src/dmd/glue/e2ir.d (hunk 1 above)
Comment (dkorpel) [reply compiler/src/dmd/glue/e2ir.d:2196]: I agree but at the same time, I found LDC emits `memcpy` and `memset` calls for WebAssembly targets as well so I'm used to it being an implicit dependency.

Comment (WalterBright) [reply compiler/src/dmd/glue/e2ir.d:2196]: True, but memcmp() is also a trivial function to write anyway. dmd also calls memcpy() and memset().
