### PR TITLE
Fix #21189 - wrong/missing error line when source file isn't regular

### LINKED ISSUE #21189: wrong/missing error line when source file isn't regular
To show the line on which an error occurs, the compiler reloads the file using the location's filename. This goes wrong in several scenario's:

- preprocessed C files
- mixin files with a pseudo filename
- files with an UTF Byte Order Mark
- `#file` directives (similar to #20929)

### PR DESCRIPTION
**Pull request by dkorpel**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: compiler/test/fail_compilation/fail_pretty_errors.d [hunk 1]
```diff
@@ -1,22 +1,24 @@
-/*
+﻿/*
```
Comment (dkorpel) [inline compiler/test/fail_compilation/fail_pretty_errors.d:1]: N.b. I added a UTF8 BOM here
